--region *.lua
--Date
--此文件由[BabeLua]插件自动生成
--佣兵日常任务
--YJX


--endregion
local nPuzzleTempData = 1006 --解谜掩码
--local nMercenaryDailyTask_GetAward = 90049
local tMercenaryDaily = {}

tMercenaryDaily.Task_1 =  90010         --拜访桑妮           --湖畔
tMercenaryDaily.Task_2 =  90011         --海莉大妈的鲜花
tMercenaryDaily.Task_3 =  90012         --采集青湖贝
tMercenaryDaily.Task_4 =  90013         --驱逐野蛮孤狼
tMercenaryDaily.Task_5 =  90014         --驱逐半鱼人
tMercenaryDaily.Task_6 =  90015         --旅馆老板的家具
--tMercenaryDaily.Task_7 =  90016         --寻找渔网
--tMercenaryDaily.Task_8 =  90017         --寻找密信
tMercenaryDaily.Task_9	=  90018         --饿狼巢穴			--讨伐白狼领主雷加
tMercenaryDaily.Task_10 = 90019        --驱逐玫瑰团追随者   --罗兰
tMercenaryDaily.Task_11 = 90020        --拜访镇长大卫
tMercenaryDaily.Task_12 = 90021        --采集血霜草
tMercenaryDaily.Task_13 = 90022        --夺回被偷的钱袋
tMercenaryDaily.Task_14 = 90023        --收集蜂蜜
tMercenaryDaily.Task_15 = 90024        --康奎斯特
tMercenaryDaily.Task_16 = 90025        --玫瑰团驻地		--讨伐暗夜蔷薇维拉
tMercenaryDaily.Task_17 = 90026        --拜访库伯拉长老     --风车
tMercenaryDaily.Task_18 = 90027        --吟游诗人的竖琴
tMercenaryDaily.Task_19 = 90028        --采集黑胡桃木
tMercenaryDaily.Task_20 = 90029        --驱逐黑袍哥布林
tMercenaryDaily.Task_21 = 90030        --驱逐丛林偷猎者
tMercenaryDaily.Task_22 = 90031        --看望安可
--tMercenaryDaily.Task_23 = 90032        --木匠的工具
tMercenaryDaily.Task_24 = 90033        --采集臭臭草
tMercenaryDaily.Task_25 = 90034        --采集五角枫叶
tMercenaryDaily.Task_26 = 90035        --收集神秘符石
tMercenaryDaily.Task_27 = 90036        --哥布林巢穴		  --讨伐暗夜蔷薇维拉
tMercenaryDaily.Task_28 = 90037        --花店老板的书      --阿克莱斯
tMercenaryDaily.Task_29 = 90038        --采集三色堇
tMercenaryDaily.Task_30 = 90039        --驱逐不死者
tMercenaryDaily.Task_31 = 90040        --看望管家
tMercenaryDaily.Task_32 = 90041        --露西蒂尼之墓	    --讨伐无魂不死者瑞恩
tMercenaryDaily.Task_33 = 90042        --驱逐亡魂死徒      --哀嚎神殿
tMercenaryDaily.Task_34 = 90043        --收集亡者之剑
tMercenaryDaily.Task_35 = 90044        --佣兵的美酒
tMercenaryDaily.Task_36 = 90045        --哀嚎神殿			--讨伐禁卫军长蓝斯
--tMercenaryDaily.Task_37 = 90046        --收集魔法石·冰    --魔族之心
--tMercenaryDaily.Task_38 = 90047        --收集魔法石·暗
tMercenaryDaily.Task_39 = 90048        --魔族之心		     --讨伐鹿角伯爵赛尔

tMercenaryDaily.Task_40 = 90050			-- 宫廷书记员的文件  	11057 	11058	  20240	   3199
tMercenaryDaily.Task_41 = 90051			-- 提琴师的邀请函  	 11059 11060	   20236  3195
tMercenaryDaily.Task_42 = 90052 		-- 粘贴帝国公告  	   11061	  60179
tMercenaryDaily.Task_43 = 90053 		-- 帮助商贩整理商货    11062	  60180
tMercenaryDaily.Task_44 = 90054 		-- 詹尼佛大妈的信  	11063 11064	   20229  3201
tMercenaryDaily.Task_45 = 90055 		-- 联盟的采购单  	  11065 11066   20150  3269
tMercenaryDaily.Task_46 = 90056 		-- 收取联盟信件  		11067	   60181
tMercenaryDaily.Task_47 = 90057 		-- 龟小豆的零食  		 11068 11069    20390  3365
tMercenaryDaily.Task_48 = 90058 		-- 取回码头货箱  		   11070	  60182
tMercenaryDaily.Task_49 = 90059 		-- 找回被盗的食物  		11071		 900299
tMercenaryDaily.Task_50 = 90060 		-- 采集椰子  			11072	   60183
tMercenaryDaily.Task_51 = 90061 		-- 采集血色花  		   11073	  60184
tMercenaryDaily.Task_52 = 90062 		-- 收集熊掌  		   11074	  900300
tMercenaryDaily.Task_53 = 90063			-- 采集魔铜矿 		  11075		  60185
tMercenaryDaily.Task_54 = 90064 		-- 密探的密函  		 11076 11077	 泽欧密探 20406 3376
tMercenaryDaily.Task_55 = 90065 		-- 采集魔族水晶	   11078	   60186




--NPC
local nNpc_Pier =  3043 --皮尔         


--新NPC（仅每日用）
local nNpc_Xier = 3239   --希尔
rwtNpc[nNpc_Xier] = rwtNpc[nNpc_Xier] or {}
local nNpc_Haili = 3240  --海莉大妈
rwtNpc[nNpc_Haili] = rwtNpc[nNpc_Haili] or {}
local nNpc_Chadian = 3241  --齐娜
rwtNpc[nNpc_Chadian] = rwtNpc[nNpc_Chadian] or {}
local nNpc_Qigai = 3242  --乞丐查理
rwtNpc[nNpc_Qigai] = rwtNpc[nNpc_Qigai] or {}
local nNpc_Maiti = 3243  --麦提
rwtNpc[nNpc_Maiti] = rwtNpc[nNpc_Maiti] or {}
local nNpc_Kubola = 3244 --库伯拉
rwtNpc[nNpc_Kubola] = rwtNpc[nNpc_Kubola] or {}
local nNpc_Miujkh = 3245 --吟游诗人缪吉克辉
rwtNpc[nNpc_Miujkh] = rwtNpc[nNpc_Miujkh] or {}
local nNpc_Anke = 3246 --安可
rwtNpc[nNpc_Anke] = rwtNpc[nNpc_Anke] or {}
local nNpc_Huadian = 3247 -- 花店老板
rwtNpc[nNpc_Huadian] = rwtNpc[nNpc_Huadian] or {}
local nNpc_Bangni = 3248  -- 邦妮
rwtNpc[nNpc_Bangni] = rwtNpc[nNpc_Bangni] or {}
local nNpc_Tuoni = 3249 -- 佣兵托尼
rwtNpc[nNpc_Tuoni] = rwtNpc[nNpc_Tuoni] or {}
local nNpc_ZeOuMiTAn = 3376 -- 泽欧密探
rwtNpc[nNpc_ZeOuMiTAn] = rwtNpc[nNpc_ZeOuMiTAn] or {}


--采集
local nCollect_Qinghubei = 60072
local nCollect_Xieweicao = 60065
local nCollect_Mucai =60066
local nCollect_Chouchoucao = 60067
local nCollect_Hongfengye = 60068  --60048
local nCollect_Fushicao = 60069
local nCollect_GongGao = 60179
local nCollect_TanWei = 60180
local nCollect_XinXiang = 60181
local nCollect_HuoXiang = 60182
local nCollect_YeiZi = 60183
local nCollect_XueSeHua = 60184
local nCollect_MoTongKuang = 60185
local nCollect_MoZuShuiJing = 60186


rwtNpcGroup[nCollect_Xieweicao] = rwtNpcGroup[nCollect_Xieweicao] or {}
rwtNpcGroup[nCollect_Xieweicao]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_Mucai] = rwtNpcGroup[nCollect_Mucai] or {}
rwtNpcGroup[nCollect_Mucai]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_Chouchoucao] = rwtNpcGroup[nCollect_Chouchoucao] or {}
rwtNpcGroup[nCollect_Chouchoucao]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_Hongfengye] = rwtNpcGroup[nCollect_Hongfengye] or {}
rwtNpcGroup[nCollect_Hongfengye]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_Fushicao] = rwtNpcGroup[nCollect_Fushicao] or {}
rwtNpcGroup[nCollect_Fushicao]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_Qinghubei] = rwtNpcGroup[nCollect_Qinghubei] or {}
rwtNpcGroup[nCollect_Qinghubei]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_GongGao] = rwtNpcGroup[nCollect_GongGao] or {}
rwtNpcGroup[nCollect_GongGao]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_TanWei] = rwtNpcGroup[nCollect_TanWei] or {}
rwtNpcGroup[nCollect_TanWei]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_XinXiang] = rwtNpcGroup[nCollect_XinXiang] or {}
rwtNpcGroup[nCollect_XinXiang]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_HuoXiang] = rwtNpcGroup[nCollect_HuoXiang] or {}
rwtNpcGroup[nCollect_HuoXiang]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_YeiZi] = rwtNpcGroup[nCollect_YeiZi] or {}
rwtNpcGroup[nCollect_YeiZi]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_XueSeHua] = rwtNpcGroup[nCollect_XueSeHua] or {}
rwtNpcGroup[nCollect_XueSeHua]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_MoTongKuang] = rwtNpcGroup[nCollect_MoTongKuang] or {}
rwtNpcGroup[nCollect_MoTongKuang]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[nCollect_MoZuShuiJing] = rwtNpcGroup[nCollect_MoZuShuiJing] or {}
rwtNpcGroup[nCollect_MoZuShuiJing]["Type"] = CONST_NPCGROUP_TYPE.Collect

--新NPC
local nNpcGroup_Xier = 20283
local nNpcGroup_Haili = 20284
local nNpcGroup_Chadian = 20285
local nNpcGroup_Qigai = 20286
local nNpcGroup_Maiti = 20287
local nNpcGroup_Kubola = 20288
local nNpcGroup_Shiren = 20289
local nNpcGroup_Anke = 20290
local nNpcGroup_Huadian = 20291
local nNpcGroup_Bangni = 20292
local nNpcGroup_Tuoni = 20293
local nNpcGroup_ZeOuMiTan = 20406

rwtNpcGroup[nNpcGroup_Xier] = rwtNpcGroup[nNpcGroup_Xier] or {}
rwtNpcGroup[nNpcGroup_Xier]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Xier]["NpcId"]= nNpc_Xier

rwtNpcGroup[nNpcGroup_Haili] = rwtNpcGroup[nNpcGroup_Haili] or {}
rwtNpcGroup[nNpcGroup_Haili]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Haili]["NpcId"]= nNpc_Haili

rwtNpcGroup[nNpcGroup_Chadian] = rwtNpcGroup[nNpcGroup_Chadian] or {}
rwtNpcGroup[nNpcGroup_Chadian]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Chadian]["NpcId"]= nNpc_Chadian

rwtNpcGroup[nNpcGroup_Qigai] = rwtNpcGroup[nNpcGroup_Qigai] or {}
rwtNpcGroup[nNpcGroup_Qigai]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Qigai]["NpcId"]= nNpc_Qigai

rwtNpcGroup[nNpcGroup_Maiti] = rwtNpcGroup[nNpcGroup_Maiti] or {}
rwtNpcGroup[nNpcGroup_Maiti]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Maiti]["NpcId"]= nNpc_Maiti

rwtNpcGroup[nNpcGroup_Kubola] = rwtNpcGroup[nNpcGroup_Kubola] or {}
rwtNpcGroup[nNpcGroup_Kubola]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Kubola]["NpcId"]= nNpc_Kubola

rwtNpcGroup[nNpcGroup_Shiren] = rwtNpcGroup[nNpcGroup_Shiren] or {}
rwtNpcGroup[nNpcGroup_Shiren]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Shiren]["NpcId"]= nNpc_Miujkh

rwtNpcGroup[nNpcGroup_Anke] = rwtNpcGroup[nNpcGroup_Anke] or {}
rwtNpcGroup[nNpcGroup_Anke]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Anke]["NpcId"]= nNpc_Anke

rwtNpcGroup[nNpcGroup_Huadian] = rwtNpcGroup[nNpcGroup_Huadian] or {}
rwtNpcGroup[nNpcGroup_Huadian]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Huadian]["NpcId"]= nNpc_Huadian

rwtNpcGroup[nNpcGroup_Bangni] = rwtNpcGroup[nNpcGroup_Bangni] or {}
rwtNpcGroup[nNpcGroup_Bangni]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Bangni]["NpcId"]= nNpc_Bangni

rwtNpcGroup[nNpcGroup_Tuoni] = rwtNpcGroup[nNpcGroup_Tuoni] or {}
rwtNpcGroup[nNpcGroup_Tuoni]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_Tuoni]["NpcId"]= nNpc_Tuoni

rwtNpcGroup[nNpcGroup_ZeOuMiTan] = rwtNpcGroup[nNpcGroup_ZeOuMiTan] or {}
rwtNpcGroup[nNpcGroup_ZeOuMiTan]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[nNpcGroup_ZeOuMiTan]["NpcId"]= 3376

--怪物
local nMonsterGroup_Gulang = 900213
local nMonsterGroup_Yuren = 900214
local nMonsterGroup_MeiguiZhui = 900215
local nMonsterGroup_MeiguiLiu = 900216
local nMonsterGroup_Hubanfeng = 900217
local nMonsterGroup_Goblin = 900218
local nMonsterGroup_Touliezhe = 900219
local nMonsterGroup_Gunshi = 900220
local nMonsterGroup_Busizhe = 900221
local nMonsterGroup_Situ = 900222
local nMonsterGroup_Sishi = 900223
local nMonsterGroup_SaiTe = 900224
local nMonsterGroup_FeiMa = 900225
local nMonsterGroup_BuLu = 900226
local nMonsterGroup_NiuQu = 900227
local nMonsterGroup_YaSuo = 900228
local nMonsterGroup_YouDe = 900229

--Genid
local nGenID_Qinghubei = 2001727
local nGenID_Xieweicao1 = 2001709
local nGenID_Xieweicao2 = 2001710
local nGenID_Xieweicao3 = 2001711
local nGenID_Mucai = 2001712
local nGenID_Chouchoucao = 2001713
local nGenID_Hongfengye = 2001714  --2001714
local nGenID_Fushicao = 2001715

local nGenID_GongGao = 1000133
local nGenID_TanWei = 1000134
local nGenID_XinXiang = 1000135
local nGenID_HuoXiang = 2001960
local nGenID_YeiZi = 2001962
local nGenID_XueSeHua = 2001963
local nGenID_MoTongKuang = 2001965
local nGenID_MoZuShuiJing = 2001967

--新gen
local nGenId_NpcGroup_Xier = 2001763
local nGenId_NpcGroup_Haili = 2001764
local nGenId_NpcGroup_Chadian = 2001765
local nGenId_NpcGroup_Qigai = 2001766
local nGenId_NpcGroup_Maiti = 2001767
local nGenId_NpcGroup_Kubola = 2001768
local nGenId_NpcGroup_Shiren = 2001769
local nGenId_NpcGroup_Anke = 2001770
local nGenId_NpcGroup_Huadian = 2001771
local nGenId_NpcGroup_Bangni = 2001772
local nGenId_NpcGroup_Tuoni = 2001773

local nGenId_MonsterGroup_Gulang     = 2001774
local nGenId_MonsterGroup_Yuren      = 2001775
local nGenId_MonsterGroup_MeiguiZhui = 2001776
local nGenId_MonsterGroup_MeiguiLiu  = 2001777
local nGenId_MonsterGroup_Hubanfeng  = 2001778
local nGenId_MonsterGroup_Goblin     = 2001779
local nGenId_MonsterGroup_Touliezhe  = 2001780
local nGenId_MonsterGroup_Gunshi     = 2001781
local nGenId_MonsterGroup_Busizhe    = 2001782
local nGenId_MonsterGroup_Situ       = 2001783
local nGenId_MonsterGroup_Sishi      = 2001784
local nGenId_MonsterGroup_SaiTe      = 2001785
local nGenId_MonsterGroup_FeiMa      = 2001786
local nGenId_MonsterGroup_BuLu       = 2001787
local nGenId_MonsterGroup_NiuQu      = 2001788
local nGenId_MonsterGroup_YaSuo      = 2001789
local nGenId_MonsterGroup_YouDe      = 2001790

--寻路用
local nFindWayPosType = 0
local nFindWayNpcType = 1
local nFindWayMonsterType = 2
local nFindWayMapId = 2001



----***************************任务***************************----
-- 新字段说明 TaskTimes 任务可存在的环数 DailyTaskAreaId 任务地图 DailyTaskTownId 任务城镇

rwtTask[tMercenaryDaily.Task_1] = {}
rwtTask[tMercenaryDaily.Task_1]["Title"] = tLuaText[LANGUAGE_CONFIG][20527]
rwtTask[tMercenaryDaily.Task_1]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_1]["TaskNpc"] = nNpc_Xier
rwtTask[tMercenaryDaily.Task_1]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_1]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_1]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Xier 
rwtTask[tMercenaryDaily.Task_1]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_1]["DialogId"] = 10442
rwtTask[tMercenaryDaily.Task_1]["TaskTimes"] = 1   --第一环才可能被随机到该任务
rwtTask[tMercenaryDaily.Task_1]["DailyTaskAreaId"] = 2001    --任务地图
rwtTask[tMercenaryDaily.Task_1]["DailyTaskTownId"] = 200101  --任务城镇
rwtTask[tMercenaryDaily.Task_1]["AcceptDialogId"] = 10441
rwtTask[tMercenaryDaily.Task_1]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_1]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_1]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_1]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Xier
rwtTask[tMercenaryDaily.Task_1]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Xier

rwtTask[tMercenaryDaily.Task_2] = {}
rwtTask[tMercenaryDaily.Task_2]["Title"] = tLuaText[LANGUAGE_CONFIG][20528]
rwtTask[tMercenaryDaily.Task_2]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_2]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_2]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_2]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Haili 
rwtTask[tMercenaryDaily.Task_2]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_2]["TaskNpc"] = nNpc_Haili
rwtTask[tMercenaryDaily.Task_2]["DialogId"] = 10452
rwtTask[tMercenaryDaily.Task_2]["TaskTimes"] = 2
rwtTask[tMercenaryDaily.Task_2]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_2]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_2]["AcceptDialogId"] = 10451
rwtTask[tMercenaryDaily.Task_2]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_2]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_2]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_2]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Haili
rwtTask[tMercenaryDaily.Task_2]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Haili

rwtTask[tMercenaryDaily.Task_3] = {}
rwtTask[tMercenaryDaily.Task_3]["Title"] = tLuaText[LANGUAGE_CONFIG][20529]
rwtTask[tMercenaryDaily.Task_3]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_3]["ReqCollectId1"] = nCollect_Qinghubei
rwtTask[tMercenaryDaily.Task_3]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_3]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_3]["DynaNpcGroupGen"][1]["GenId"] = nGenID_Qinghubei 
rwtTask[tMercenaryDaily.Task_3]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_3]["TaskTimes"] = 3
rwtTask[tMercenaryDaily.Task_3]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_3]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_3]["AcceptDialogId"] = 10478
rwtTask[tMercenaryDaily.Task_3]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_3]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_3]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_3]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_3]["StartAutoWay"]["FindWayGroupId"] = nCollect_Qinghubei
rwtTask[tMercenaryDaily.Task_3]["StartAutoWay"]["FindWayGenId"] = nGenID_Qinghubei

rwtTask[tMercenaryDaily.Task_4] = {}
rwtTask[tMercenaryDaily.Task_4]["Title"] = tLuaText[LANGUAGE_CONFIG][20530]
rwtTask[tMercenaryDaily.Task_4]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_4]["TaskTimes"] = 4
rwtTask[tMercenaryDaily.Task_4]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_4]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_4]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_4]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_4]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Gulang 
rwtTask[tMercenaryDaily.Task_4]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_4]["KillMonsterGroup1" ]= nMonsterGroup_Gulang
rwtTask[tMercenaryDaily.Task_4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_4]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_4]["AcceptDialogId"] = 10465
rwtTask[tMercenaryDaily.Task_4]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_4]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_4]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_4]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Gulang
rwtTask[tMercenaryDaily.Task_4]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Gulang

rwtTask[tMercenaryDaily.Task_5] = {}
rwtTask[tMercenaryDaily.Task_5]["Title"] = tLuaText[LANGUAGE_CONFIG][20531]
rwtTask[tMercenaryDaily.Task_5]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_5]["TaskTimes"] = 4
rwtTask[tMercenaryDaily.Task_5]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_5]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_5]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_5]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_5]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Yuren 
rwtTask[tMercenaryDaily.Task_5]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_5]["KillMonsterGroup1" ]= nMonsterGroup_Yuren
rwtTask[tMercenaryDaily.Task_5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_5]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_5]["AcceptDialogId"] = 10466
rwtTask[tMercenaryDaily.Task_5]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_5]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_5]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_5]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Yuren
rwtTask[tMercenaryDaily.Task_5]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Yuren

rwtTask[tMercenaryDaily.Task_6] = {}
rwtTask[tMercenaryDaily.Task_6]["Title"] = tLuaText[LANGUAGE_CONFIG][20532]
rwtTask[tMercenaryDaily.Task_6]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_6]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_6]["TaskNpc"] = nNpc_Chadian
rwtTask[tMercenaryDaily.Task_6]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_6]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_6]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Chadian 
rwtTask[tMercenaryDaily.Task_6]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_6]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_6]["DialogId"] = 10454
rwtTask[tMercenaryDaily.Task_6]["TaskTimes"] = 6
rwtTask[tMercenaryDaily.Task_6]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_6]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_6]["AcceptDialogId"] = 10453
rwtTask[tMercenaryDaily.Task_6]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_6]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_6]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_6]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Chadian
rwtTask[tMercenaryDaily.Task_6]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Chadian

--region 1.05版本暂时屏蔽
--rwtTask[tMercenaryDaily.Task_7] = {}
--rwtTask[tMercenaryDaily.Task_7]["Title"] = tLuaText[LANGUAGE_CONFIG][20533]
--rwtTask[tMercenaryDaily.Task_7]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
--rwtTask[tMercenaryDaily.Task_7]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.PUZZLE
--rwtTask[tMercenaryDaily.Task_7]["TaskTimes"] = 6
--rwtTask[tMercenaryDaily.Task_7]["DailyTaskAreaId"] = 2001
--rwtTask[tMercenaryDaily.Task_7]["DailyTaskTownId"] = 200101
--rwtTask[tMercenaryDaily.Task_7]["IsClickComplete"] = 1
--rwtTask[tMercenaryDaily.Task_7]["AcceptDialogId"] = 10520
--rwtTask[tMercenaryDaily.Task_7]["ReqPuzzleId"] = 101
--rwtTask[tMercenaryDaily.Task_7]["ReqPuzzleDataIndex"] = {CONST_TEMP_DATA.Data3}
--rwtTask[tMercenaryDaily.Task_7]["AcceptFunc"] = function ()
--    rwTempDataSet(nPuzzleTempData,0,CONST_TEMP_DATA.Data3)
--end


--rwtTask[tMercenaryDaily.Task_8] = {}
--rwtTask[tMercenaryDaily.Task_8]["Title"] = tLuaText[LANGUAGE_CONFIG][20534]
--rwtTask[tMercenaryDaily.Task_8]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
--rwtTask[tMercenaryDaily.Task_8]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.PUZZLE
--rwtTask[tMercenaryDaily.Task_8]["TaskTimes"] = 9
--rwtTask[tMercenaryDaily.Task_8]["DailyTaskAreaId"] = 2001
--rwtTask[tMercenaryDaily.Task_8]["DailyTaskTownId"] = 200101
--rwtTask[tMercenaryDaily.Task_8]["IsClickComplete"] = 1
--rwtTask[tMercenaryDaily.Task_8]["AcceptDialogId"] = 10521
--rwtTask[tMercenaryDaily.Task_8]["ReqPuzzleId"] = 101
--rwtTask[tMercenaryDaily.Task_8]["ReqPuzzleDataIndex"] = {CONST_TEMP_DATA.Data4}
--rwtTask[tMercenaryDaily.Task_8]["AcceptFunc"] = function ()
--    rwTempDataSet(nPuzzleTempData,0,CONST_TEMP_DATA.Data4)
--end
--endregion

rwtTask[tMercenaryDaily.Task_9] = {}
rwtTask[tMercenaryDaily.Task_9]["Title"] = tLuaText[LANGUAGE_CONFIG][20535]
rwtTask[tMercenaryDaily.Task_9]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_9]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_9]["TaskTimes"] = 10
rwtTask[tMercenaryDaily.Task_9]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_9]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_9]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_SaiTe 
rwtTask[tMercenaryDaily.Task_9]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_9]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_9]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_9]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_9]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_9]["KillMonsterGroup1" ]= nMonsterGroup_SaiTe
--rwtTask[tMercenaryDaily.Task_9]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_9]["AcceptDialogId"] = 10484
rwtTask[tMercenaryDaily.Task_9]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_9]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_9]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_9]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_SaiTe
rwtTask[tMercenaryDaily.Task_9]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_SaiTe


rwtTask[tMercenaryDaily.Task_10] = {}
rwtTask[tMercenaryDaily.Task_10]["Title"] = tLuaText[LANGUAGE_CONFIG][20536]
rwtTask[tMercenaryDaily.Task_10]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_10]["TaskTimes"] = 4
rwtTask[tMercenaryDaily.Task_10]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_10]["DailyTaskTownId"] = 200102
rwtTask[tMercenaryDaily.Task_10]["KillMonsterGroup1" ]= nMonsterGroup_MeiguiZhui
rwtTask[tMercenaryDaily.Task_10]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_10]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_10]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_MeiguiZhui 
rwtTask[tMercenaryDaily.Task_10]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_10]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_10]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_10]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_10]["AcceptDialogId"] = 10467
rwtTask[tMercenaryDaily.Task_10]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_10]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_10]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_10]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_MeiguiZhui
rwtTask[tMercenaryDaily.Task_10]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_MeiguiZhui

rwtTask[tMercenaryDaily.Task_11] = {}
rwtTask[tMercenaryDaily.Task_11]["Title"] = tLuaText[LANGUAGE_CONFIG][20537]
rwtTask[tMercenaryDaily.Task_11]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_11]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_11]["TaskNpc"] = nNpc_Qigai
rwtTask[tMercenaryDaily.Task_11]["DialogId"] = 10444
rwtTask[tMercenaryDaily.Task_11]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_11]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_11]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Qigai 
rwtTask[tMercenaryDaily.Task_11]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_11]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_11]["TaskTimes"] = 5
rwtTask[tMercenaryDaily.Task_11]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_11]["DailyTaskTownId"] = 200102
rwtTask[tMercenaryDaily.Task_11]["AcceptDialogId"] = 10443
rwtTask[tMercenaryDaily.Task_11]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_11]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_11]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_11]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Qigai
rwtTask[tMercenaryDaily.Task_11]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Qigai

rwtTask[tMercenaryDaily.Task_12] = {}
rwtTask[tMercenaryDaily.Task_12]["Title"] = tLuaText[LANGUAGE_CONFIG][20538]
rwtTask[tMercenaryDaily.Task_12]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_12]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_12]["ReqCollectId1"] = nCollect_Xieweicao
rwtTask[tMercenaryDaily.Task_12]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_12]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_12]["DynaNpcGroupGen"][1]["GenId"] = nGenID_Xieweicao1 
rwtTask[tMercenaryDaily.Task_12]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_12]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_12]["TaskTimes"] = 7
rwtTask[tMercenaryDaily.Task_12]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_12]["DailyTaskTownId"] = 200102
rwtTask[tMercenaryDaily.Task_12]["AcceptDialogId"] = 10479
rwtTask[tMercenaryDaily.Task_12]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_12]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_12]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_12]["StartAutoWay"]["FindWayGroupId"] = nCollect_Xieweicao
rwtTask[tMercenaryDaily.Task_12]["StartAutoWay"]["FindWayGenId"] = nGenID_Xieweicao1

rwtTask[tMercenaryDaily.Task_13] = {}
rwtTask[tMercenaryDaily.Task_13]["Title"] = tLuaText[LANGUAGE_CONFIG][20539]
rwtTask[tMercenaryDaily.Task_13]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_13]["TaskTimes"] = 8
rwtTask[tMercenaryDaily.Task_13]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_13]["DailyTaskTownId"] = 200102
rwtTask[tMercenaryDaily.Task_13]["KillMonsterGroup1" ]= nMonsterGroup_MeiguiLiu
rwtTask[tMercenaryDaily.Task_13]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_13]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_13]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_MeiguiLiu 
rwtTask[tMercenaryDaily.Task_13]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_13]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_13]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_13]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_13]["AcceptDialogId"] = 10472
rwtTask[tMercenaryDaily.Task_13]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_13]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_13]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_13]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_MeiguiLiu
rwtTask[tMercenaryDaily.Task_13]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_MeiguiLiu

rwtTask[tMercenaryDaily.Task_14] = {}
rwtTask[tMercenaryDaily.Task_14]["Title"] = tLuaText[LANGUAGE_CONFIG][20540]
rwtTask[tMercenaryDaily.Task_14]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_14]["TaskTimes"] = 8
rwtTask[tMercenaryDaily.Task_14]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_14]["DailyTaskTownId"] = 200102
rwtTask[tMercenaryDaily.Task_14]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_14]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_14]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Hubanfeng 
rwtTask[tMercenaryDaily.Task_14]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_14]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_14]["KillMonsterGroup1" ]= nMonsterGroup_Hubanfeng
rwtTask[tMercenaryDaily.Task_14]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_14]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_14]["AcceptDialogId"] = 10474
rwtTask[tMercenaryDaily.Task_14]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_14]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_14]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_14]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Hubanfeng
rwtTask[tMercenaryDaily.Task_14]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Hubanfeng

rwtTask[tMercenaryDaily.Task_15] = {}
rwtTask[tMercenaryDaily.Task_15]["Title"] = tLuaText[LANGUAGE_CONFIG][20541]
rwtTask[tMercenaryDaily.Task_15]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_15]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_15]["TaskNpc"] = nNpc_Maiti
rwtTask[tMercenaryDaily.Task_15]["DialogId"] = 10458
rwtTask[tMercenaryDaily.Task_15]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_15]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_15]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Maiti 
rwtTask[tMercenaryDaily.Task_15]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_15]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_15]["TaskTimes"] = 9
rwtTask[tMercenaryDaily.Task_15]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_15]["DailyTaskTownId"] = 200102
rwtTask[tMercenaryDaily.Task_15]["AcceptDialogId"] = 10457									  
rwtTask[tMercenaryDaily.Task_15]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_15]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_15]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_15]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Maiti
rwtTask[tMercenaryDaily.Task_15]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Maiti

rwtTask[tMercenaryDaily.Task_16] = {}
rwtTask[tMercenaryDaily.Task_16]["Title"] = tLuaText[LANGUAGE_CONFIG][20542]
rwtTask[tMercenaryDaily.Task_16]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_16]["TaskTimes"] = 10
rwtTask[tMercenaryDaily.Task_16]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_16]["DailyTaskTownId"] = 200102
rwtTask[tMercenaryDaily.Task_16]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_16]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_16]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_16]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_FeiMa 
rwtTask[tMercenaryDaily.Task_16]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_16]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_16]["KillMonsterGroup1" ]= nMonsterGroup_FeiMa
rwtTask[tMercenaryDaily.Task_16]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_16]["AcceptDialogId"] = 10485
rwtTask[tMercenaryDaily.Task_16]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_16]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_16]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_16]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_FeiMa
rwtTask[tMercenaryDaily.Task_16]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_FeiMa

rwtTask[tMercenaryDaily.Task_17] = {}
rwtTask[tMercenaryDaily.Task_17]["Title"] = tLuaText[LANGUAGE_CONFIG][20543]
rwtTask[tMercenaryDaily.Task_17]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_17]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_17]["TaskNpc"] = nNpc_Kubola
rwtTask[tMercenaryDaily.Task_17]["DialogId"] = 10446
rwtTask[tMercenaryDaily.Task_17]["TaskTimes"] = 1
rwtTask[tMercenaryDaily.Task_17]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_17]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_17]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Kubola 
rwtTask[tMercenaryDaily.Task_17]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_17]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_17]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_17]["DailyTaskTownId"] = 200103												  
rwtTask[tMercenaryDaily.Task_17]["AcceptDialogId"] = 10445
rwtTask[tMercenaryDaily.Task_17]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_17]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_17]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_17]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Kubola
rwtTask[tMercenaryDaily.Task_17]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Kubola

rwtTask[tMercenaryDaily.Task_18] = {}
rwtTask[tMercenaryDaily.Task_18]["Title"] = tLuaText[LANGUAGE_CONFIG][20544]
rwtTask[tMercenaryDaily.Task_18]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_18]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_18]["TaskNpc"] = nNpc_Miujkh
rwtTask[tMercenaryDaily.Task_18]["DialogId"] = 10462
rwtTask[tMercenaryDaily.Task_18]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_18]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_18]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Shiren 
rwtTask[tMercenaryDaily.Task_18]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_18]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_18]["TaskTimes"] = 2
rwtTask[tMercenaryDaily.Task_18]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_18]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_18]["AcceptDialogId"] = 10461
rwtTask[tMercenaryDaily.Task_18]["StartAutoWay"] = {}															  
rwtTask[tMercenaryDaily.Task_18]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_18]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_18]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Shiren
rwtTask[tMercenaryDaily.Task_18]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Shiren

rwtTask[tMercenaryDaily.Task_19] = {}
rwtTask[tMercenaryDaily.Task_19]["Title"] = tLuaText[LANGUAGE_CONFIG][20545]
rwtTask[tMercenaryDaily.Task_19]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_19]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_19]["ReqCollectId1"] = nCollect_Mucai
rwtTask[tMercenaryDaily.Task_19]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_19]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_19]["DynaNpcGroupGen"][1]["GenId"] = nGenID_Mucai 
rwtTask[tMercenaryDaily.Task_19]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_19]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_19]["TaskTimes"] = 3
rwtTask[tMercenaryDaily.Task_19]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_19]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_19]["AcceptDialogId"] = 10480
rwtTask[tMercenaryDaily.Task_19]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_19]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_19]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_19]["StartAutoWay"]["FindWayGroupId"] = nCollect_Mucai
rwtTask[tMercenaryDaily.Task_19]["StartAutoWay"]["FindWayGenId"] = nGenID_Mucai

rwtTask[tMercenaryDaily.Task_20] = {}
rwtTask[tMercenaryDaily.Task_20]["Title"] = tLuaText[LANGUAGE_CONFIG][20546]
rwtTask[tMercenaryDaily.Task_20]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_20]["TaskTimes"] = 4
rwtTask[tMercenaryDaily.Task_20]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_20]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_20]["KillMonsterGroup1" ]= nMonsterGroup_Goblin
rwtTask[tMercenaryDaily.Task_20]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_20]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_20]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Goblin 
rwtTask[tMercenaryDaily.Task_20]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_20]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_20]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_20]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_20]["AcceptDialogId"] = 10468
rwtTask[tMercenaryDaily.Task_20]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_20]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_20]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_20]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Goblin
rwtTask[tMercenaryDaily.Task_20]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Goblin

rwtTask[tMercenaryDaily.Task_21] = {}
rwtTask[tMercenaryDaily.Task_21]["Title"] = tLuaText[LANGUAGE_CONFIG][20547]
rwtTask[tMercenaryDaily.Task_21]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_21]["TaskTimes"] = 4
rwtTask[tMercenaryDaily.Task_21]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_21]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_21]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_21]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_21]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Touliezhe 
rwtTask[tMercenaryDaily.Task_21]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_21]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_21]["KillMonsterGroup1" ]= nMonsterGroup_Touliezhe
rwtTask[tMercenaryDaily.Task_21]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_21]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_21]["AcceptDialogId"] = 10469
rwtTask[tMercenaryDaily.Task_21]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_21]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_21]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_21]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Touliezhe
rwtTask[tMercenaryDaily.Task_21]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Touliezhe

rwtTask[tMercenaryDaily.Task_22] = {}
rwtTask[tMercenaryDaily.Task_22]["Title"] =tLuaText[LANGUAGE_CONFIG][20548]
rwtTask[tMercenaryDaily.Task_22]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_22]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_22]["TaskNpc"] = nNpc_Anke
rwtTask[tMercenaryDaily.Task_22]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_22]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_22]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Anke 
rwtTask[tMercenaryDaily.Task_22]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_22]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_22]["DialogId"] = 10448
rwtTask[tMercenaryDaily.Task_22]["TaskTimes"] = 5
rwtTask[tMercenaryDaily.Task_22]["DailyTaskAreaId"] = 2001												  
rwtTask[tMercenaryDaily.Task_22]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_22]["AcceptDialogId"] = 10447
rwtTask[tMercenaryDaily.Task_22]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_22]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_22]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_22]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Anke
rwtTask[tMercenaryDaily.Task_22]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Anke

--rwtTask[tMercenaryDaily.Task_23] = {}
--rwtTask[tMercenaryDaily.Task_23]["Title"] = tLuaText[LANGUAGE_CONFIG][20549]
--rwtTask[tMercenaryDaily.Task_23]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
--rwtTask[tMercenaryDaily.Task_23]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tMercenaryDaily.Task_23]["TaskNpc"] = nNpc_KakaMj
--rwtTask[tMercenaryDaily.Task_23]["DiologId"] = 10464
--rwtTask[tMercenaryDaily.Task_23]["TaskTimes"] = 6
--rwtTask[tMercenaryDaily.Task_23]["DailyTaskAreaId"] = 2001
--rwtTask[tMercenaryDaily.Task_23]["DailyTaskTownId"] = 200103
--rwtTask[tMercenaryDaily.Task_23]["AcceptDialogId"] = 10463





rwtTask[tMercenaryDaily.Task_24] = {}
rwtTask[tMercenaryDaily.Task_24]["Title"] = tLuaText[LANGUAGE_CONFIG][20550]
rwtTask[tMercenaryDaily.Task_24]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_24]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_24]["ReqCollectId1"] = nCollect_Chouchoucao
rwtTask[tMercenaryDaily.Task_24]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_24]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_24]["DynaNpcGroupGen"][1]["GenId"] = nGenID_Chouchoucao 
rwtTask[tMercenaryDaily.Task_24]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_24]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_24]["TaskTimes"] = 7
rwtTask[tMercenaryDaily.Task_24]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_24]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_24]["AcceptDialogId"] = 10482
rwtTask[tMercenaryDaily.Task_24]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_24]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_24]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_24]["StartAutoWay"]["FindWayGroupId"] = nCollect_Chouchoucao
rwtTask[tMercenaryDaily.Task_24]["StartAutoWay"]["FindWayGenId"] = nGenID_Chouchoucao

rwtTask[tMercenaryDaily.Task_25] = {}
rwtTask[tMercenaryDaily.Task_25]["Title"] = tLuaText[LANGUAGE_CONFIG][20551]
rwtTask[tMercenaryDaily.Task_25]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_25]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_25]["ReqCollectId1"] = nCollect_Hongfengye
rwtTask[tMercenaryDaily.Task_25]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_25]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_25]["DynaNpcGroupGen"][1]["GenId"] = nGenID_Hongfengye 
rwtTask[tMercenaryDaily.Task_25]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_25]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_25]["TaskTimes"] = 7
rwtTask[tMercenaryDaily.Task_25]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_25]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_25]["AcceptDialogId"] = 10481
rwtTask[tMercenaryDaily.Task_25]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_25]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_25]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_25]["StartAutoWay"]["FindWayGroupId"] = nCollect_Hongfengye
rwtTask[tMercenaryDaily.Task_25]["StartAutoWay"]["FindWayGenId"] = nGenID_Hongfengye

rwtTask[tMercenaryDaily.Task_26] = {}
rwtTask[tMercenaryDaily.Task_26]["Title"] = tLuaText[LANGUAGE_CONFIG][20552]
rwtTask[tMercenaryDaily.Task_26]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_26]["TaskTimes"] = 8
rwtTask[tMercenaryDaily.Task_26]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_26]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_26]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_26]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_26]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Gunshi 
rwtTask[tMercenaryDaily.Task_26]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_26]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_26]["KillMonsterGroup1" ]= nMonsterGroup_Gunshi
rwtTask[tMercenaryDaily.Task_26]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_26]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_26]["AcceptDialogId"] = 10473
rwtTask[tMercenaryDaily.Task_26]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_26]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_26]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_26]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Gunshi
rwtTask[tMercenaryDaily.Task_26]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Gunshi

rwtTask[tMercenaryDaily.Task_27] = {}
rwtTask[tMercenaryDaily.Task_27]["Title"] = tLuaText[LANGUAGE_CONFIG][20553]
rwtTask[tMercenaryDaily.Task_27]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_27]["TaskTimes"] = 10
rwtTask[tMercenaryDaily.Task_27]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_27]["DailyTaskTownId"] = 200103
rwtTask[tMercenaryDaily.Task_27]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_27]["KillMonsterGroup1" ]= nMonsterGroup_BuLu
rwtTask[tMercenaryDaily.Task_27]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_27]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_27]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_BuLu 
rwtTask[tMercenaryDaily.Task_27]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_27]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_27]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_27]["AcceptDialogId"] = 10486
rwtTask[tMercenaryDaily.Task_27]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_27]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_27]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_27]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_BuLu
rwtTask[tMercenaryDaily.Task_27]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_BuLu

rwtTask[tMercenaryDaily.Task_28] = {}
rwtTask[tMercenaryDaily.Task_28]["Title"] = tLuaText[LANGUAGE_CONFIG][20554]
rwtTask[tMercenaryDaily.Task_28]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_28]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_28]["TaskNpc"] = nNpc_Huadian
rwtTask[tMercenaryDaily.Task_28]["DialogId"] = 10460
rwtTask[tMercenaryDaily.Task_28]["TaskTimes"] = 2
rwtTask[tMercenaryDaily.Task_28]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_28]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_28]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Huadian 
rwtTask[tMercenaryDaily.Task_28]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_28]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_28]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_28]["DailyTaskTownId"] = 200104
rwtTask[tMercenaryDaily.Task_28]["AcceptDialogId"] = 10459
rwtTask[tMercenaryDaily.Task_28]["StartAutoWay"] = {}																   
rwtTask[tMercenaryDaily.Task_28]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_28]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_28]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Huadian
rwtTask[tMercenaryDaily.Task_28]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Huadian

rwtTask[tMercenaryDaily.Task_29] = {}
rwtTask[tMercenaryDaily.Task_29]["Title"] = tLuaText[LANGUAGE_CONFIG][20555]
rwtTask[tMercenaryDaily.Task_29]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_29]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_29]["ReqCollectId1"] = nCollect_Fushicao
rwtTask[tMercenaryDaily.Task_29]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_29]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_29]["DynaNpcGroupGen"][1]["GenId"] = nGenID_Fushicao 
rwtTask[tMercenaryDaily.Task_29]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_29]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_29]["TaskTimes"] = 3
rwtTask[tMercenaryDaily.Task_29]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_29]["DailyTaskTownId"] = 200104
rwtTask[tMercenaryDaily.Task_29]["AcceptDialogId"] = 10483
rwtTask[tMercenaryDaily.Task_29]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_29]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_29]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_29]["StartAutoWay"]["FindWayGroupId"] = nCollect_Fushicao
rwtTask[tMercenaryDaily.Task_29]["StartAutoWay"]["FindWayGenId"] = nGenID_Fushicao

rwtTask[tMercenaryDaily.Task_30] = {}
rwtTask[tMercenaryDaily.Task_30]["Title"] = tLuaText[LANGUAGE_CONFIG][20556]
rwtTask[tMercenaryDaily.Task_30]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_30]["TaskTimes"] = 4
rwtTask[tMercenaryDaily.Task_30]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_30]["DailyTaskTownId"] = 200104
rwtTask[tMercenaryDaily.Task_30]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_30]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_30]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Busizhe 
rwtTask[tMercenaryDaily.Task_30]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_30]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_30]["KillMonsterGroup1" ]= nMonsterGroup_Busizhe
rwtTask[tMercenaryDaily.Task_30]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_30]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_30]["AcceptDialogId"] = 10470
rwtTask[tMercenaryDaily.Task_30]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_30]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_30]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_30]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Busizhe
rwtTask[tMercenaryDaily.Task_30]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Busizhe

rwtTask[tMercenaryDaily.Task_31] = {}
rwtTask[tMercenaryDaily.Task_31]["Title"] = tLuaText[LANGUAGE_CONFIG][20557]
rwtTask[tMercenaryDaily.Task_31]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_31]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_31]["TaskNpc"] = nNpc_Bangni
rwtTask[tMercenaryDaily.Task_31]["DialogId"] = 10450
rwtTask[tMercenaryDaily.Task_31]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_31]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_31]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Bangni 
rwtTask[tMercenaryDaily.Task_31]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_31]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_31]["TaskTimes"] = 5
rwtTask[tMercenaryDaily.Task_31]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_31]["DailyTaskTownId"] = 200104
rwtTask[tMercenaryDaily.Task_31]["AcceptDialogId"] = 10449														
rwtTask[tMercenaryDaily.Task_31]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_31]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_31]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_31]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Bangni
rwtTask[tMercenaryDaily.Task_31]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Bangni

rwtTask[tMercenaryDaily.Task_32] = {}
rwtTask[tMercenaryDaily.Task_32]["Title"] = tLuaText[LANGUAGE_CONFIG][20558]
rwtTask[tMercenaryDaily.Task_32]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_32]["TaskTimes"] = 10
rwtTask[tMercenaryDaily.Task_32]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_32]["DailyTaskTownId"] = 200104
rwtTask[tMercenaryDaily.Task_32]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_32]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_32]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_NiuQu 
rwtTask[tMercenaryDaily.Task_32]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_32]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_32]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_32]["KillMonsterGroup1" ]= nMonsterGroup_NiuQu
rwtTask[tMercenaryDaily.Task_32]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_32]["AcceptDialogId"] = 10487
rwtTask[tMercenaryDaily.Task_32]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_32]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_32]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_32]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NiuQu
rwtTask[tMercenaryDaily.Task_32]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_NiuQu

rwtTask[tMercenaryDaily.Task_33] = {}
rwtTask[tMercenaryDaily.Task_33]["Title"] = tLuaText[LANGUAGE_CONFIG][20559]
rwtTask[tMercenaryDaily.Task_33]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_33]["TaskTimes"] = 4
rwtTask[tMercenaryDaily.Task_33]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_33]["DailyTaskTownId"] = 200105
rwtTask[tMercenaryDaily.Task_33]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_33]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_33]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Situ 
rwtTask[tMercenaryDaily.Task_33]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_33]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_33]["KillMonsterGroup1" ]= nMonsterGroup_Situ
rwtTask[tMercenaryDaily.Task_33]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_33]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_33]["AcceptDialogId"] = 10471
rwtTask[tMercenaryDaily.Task_33]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_33]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_33]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_33]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Situ
rwtTask[tMercenaryDaily.Task_33]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Situ

rwtTask[tMercenaryDaily.Task_34] = {}
rwtTask[tMercenaryDaily.Task_34]["Title"] = tLuaText[LANGUAGE_CONFIG][20560]
rwtTask[tMercenaryDaily.Task_34]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_34]["TaskTimes"] = 8
rwtTask[tMercenaryDaily.Task_34]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_34]["DailyTaskTownId"] = 200105
rwtTask[tMercenaryDaily.Task_34]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_34]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_34]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_Sishi 
rwtTask[tMercenaryDaily.Task_34]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_34]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_34]["KillMonsterGroup1" ]= nMonsterGroup_Sishi
rwtTask[tMercenaryDaily.Task_34]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_34]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_34]["AcceptDialogId"] = 10475
rwtTask[tMercenaryDaily.Task_34]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_34]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_34]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_34]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_Sishi
rwtTask[tMercenaryDaily.Task_34]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_Sishi

rwtTask[tMercenaryDaily.Task_35] = {}
rwtTask[tMercenaryDaily.Task_35]["Title"] = tLuaText[LANGUAGE_CONFIG][20561]
rwtTask[tMercenaryDaily.Task_35]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_35]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_35]["TaskNpc"] = nNpc_Tuoni
rwtTask[tMercenaryDaily.Task_35]["DialogId"] = 10456
rwtTask[tMercenaryDaily.Task_35]["TaskTimes"] = 9
rwtTask[tMercenaryDaily.Task_35]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_35]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_35]["DynaNpcGroupGen"][1]["GenId"] = nGenId_NpcGroup_Tuoni 
rwtTask[tMercenaryDaily.Task_35]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_35]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Success
rwtTask[tMercenaryDaily.Task_35]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_35]["DailyTaskTownId"] = 200105
rwtTask[tMercenaryDaily.Task_35]["AcceptDialogId"] = 10455													   
rwtTask[tMercenaryDaily.Task_35]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_35]["StartAutoWay"]["FindWayTypeId"] = nFindWayNpcType
rwtTask[tMercenaryDaily.Task_35]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_35]["StartAutoWay"]["FindWayGroupId"] = nNpcGroup_Tuoni
rwtTask[tMercenaryDaily.Task_35]["StartAutoWay"]["FindWayGenId"] = nGenId_NpcGroup_Tuoni

rwtTask[tMercenaryDaily.Task_36] = {}
rwtTask[tMercenaryDaily.Task_36]["Title"] = tLuaText[LANGUAGE_CONFIG][20562]
rwtTask[tMercenaryDaily.Task_36]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_36]["TaskTimes"] = 10
rwtTask[tMercenaryDaily.Task_36]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_36]["DailyTaskTownId"] = 200105
rwtTask[tMercenaryDaily.Task_36]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_36]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_36]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_36]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_YaSuo 
rwtTask[tMercenaryDaily.Task_36]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_36]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_36]["KillMonsterGroup1" ]= nMonsterGroup_YaSuo
rwtTask[tMercenaryDaily.Task_36]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_36]["AcceptDialogId"] = 10488
rwtTask[tMercenaryDaily.Task_36]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_36]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_36]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_36]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_YaSuo
rwtTask[tMercenaryDaily.Task_36]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_YaSuo

--rwtTask[tMercenaryDaily.Task_37] = {}
--rwtTask[tMercenaryDaily.Task_37]["Title"] = tLuaText[LANGUAGE_CONFIG][20563]
--rwtTask[tMercenaryDaily.Task_37]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
--rwtTask[tMercenaryDaily.Task_37]["TaskTimes"] = 8
--rwtTask[tMercenaryDaily.Task_37]["DailyTaskAreaId"] = 2001
--rwtTask[tMercenaryDaily.Task_37]["DailyTaskTownId"] = 200106
--rwtTask[tMercenaryDaily.Task_37]["KillMonsterGroup1" ]= 300080
--rwtTask[tMercenaryDaily.Task_37]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_37]["AcceptDialogId"] = 10476

--rwtTask[tMercenaryDaily.Task_38] = {}
--rwtTask[tMercenaryDaily.Task_38]["Title"] = tLuaText[LANGUAGE_CONFIG][20564]
--rwtTask[tMercenaryDaily.Task_38]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
--rwtTask[tMercenaryDaily.Task_38]["TaskTimes"] = 8
--rwtTask[tMercenaryDaily.Task_38]["DailyTaskAreaId"] = 2001
--rwtTask[tMercenaryDaily.Task_38]["DailyTaskTownId"] = 200106
--rwtTask[tMercenaryDaily.Task_38]["KillMonsterGroup1" ]= 300081
--rwtTask[tMercenaryDaily.Task_38]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
--rwtTask[tMercenaryDaily.Task_38]["AcceptDialogId"] = 10477

rwtTask[tMercenaryDaily.Task_39] = {}
rwtTask[tMercenaryDaily.Task_39]["Title"] = tLuaText[LANGUAGE_CONFIG][20565]
rwtTask[tMercenaryDaily.Task_39]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_39]["TaskTimes"] = 10
rwtTask[tMercenaryDaily.Task_39]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_39]["DailyTaskTownId"] = 200106
rwtTask[tMercenaryDaily.Task_39]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_39]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_39]["DynaNpcGroupGen"][1]["GenId"] = nGenId_MonsterGroup_YouDe 
rwtTask[tMercenaryDaily.Task_39]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_39]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_39]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_39]["IsClickComplete"] = 1
rwtTask[tMercenaryDaily.Task_39]["KillMonsterGroup1" ]= nMonsterGroup_YouDe
rwtTask[tMercenaryDaily.Task_39]["AcceptDialogId"] = 10489
rwtTask[tMercenaryDaily.Task_39]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_39]["StartAutoWay"]["FindWayTypeId"] = nFindWayMonsterType
rwtTask[tMercenaryDaily.Task_39]["StartAutoWay"]["FindWayMapId"] = nFindWayMapId
rwtTask[tMercenaryDaily.Task_39]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_YouDe
rwtTask[tMercenaryDaily.Task_39]["StartAutoWay"]["FindWayGenId"] = nGenId_MonsterGroup_YouDe


rwtTask[tMercenaryDaily.Task_40] = {}
rwtTask[tMercenaryDaily.Task_40]["Title"] = tLuaText[LANGUAGE_CONFIG][20566]
rwtTask[tMercenaryDaily.Task_40]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_40]["TaskTimes"] = 1
rwtTask[tMercenaryDaily.Task_40]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_40]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_40]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_40]["TaskNpc"] = 3199
rwtTask[tMercenaryDaily.Task_40]["AcceptDialogId"] = 11057
rwtTask[tMercenaryDaily.Task_40]["DialogId"] = 11058
rwtTask[tMercenaryDaily.Task_40]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_40]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_40]["StartAutoWay"]["FindWayMapId"] = 1000
rwtTask[tMercenaryDaily.Task_40]["StartAutoWay"]["FindWayGroupId"] = 20240
rwtTask[tMercenaryDaily.Task_40]["StartAutoWay"]["FindWayGenId"] = 1000062

rwtTask[tMercenaryDaily.Task_41] = {}
rwtTask[tMercenaryDaily.Task_41]["Title"] = tLuaText[LANGUAGE_CONFIG][20567]
rwtTask[tMercenaryDaily.Task_41]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_41]["TaskTimes"] = 2
rwtTask[tMercenaryDaily.Task_41]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_41]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_41]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_41]["TaskNpc"] = 3195
rwtTask[tMercenaryDaily.Task_41]["AcceptDialogId"] = 11059
rwtTask[tMercenaryDaily.Task_41]["DialogId"] = 11060
rwtTask[tMercenaryDaily.Task_41]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_41]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_41]["StartAutoWay"]["FindWayMapId"] = 1000
rwtTask[tMercenaryDaily.Task_41]["StartAutoWay"]["FindWayGroupId"] = 20236
rwtTask[tMercenaryDaily.Task_41]["StartAutoWay"]["FindWayGenId"] = 1000055

rwtTask[tMercenaryDaily.Task_42] = {}
rwtTask[tMercenaryDaily.Task_42]["Title"] = tLuaText[LANGUAGE_CONFIG][20568]
rwtTask[tMercenaryDaily.Task_42]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_42]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_42]["ReqCollectId1"] = nCollect_GongGao
rwtTask[tMercenaryDaily.Task_42]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_42]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_42]["DynaNpcGroupGen"][1]["GenId"] = nGenID_GongGao 
rwtTask[tMercenaryDaily.Task_42]["DynaNpcGroupGen"][1]["MapId"] = 1000
rwtTask[tMercenaryDaily.Task_42]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_42]["TaskTimes"] = 3
rwtTask[tMercenaryDaily.Task_42]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_42]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_42]["AcceptDialogId"] = 11061
rwtTask[tMercenaryDaily.Task_42]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_42]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_42]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_42]["StartAutoWay"]["FindWayMapId"] = 1000
rwtTask[tMercenaryDaily.Task_42]["StartAutoWay"]["FindWayGroupId"] = nCollect_GongGao
rwtTask[tMercenaryDaily.Task_42]["StartAutoWay"]["FindWayGenId"] = nGenID_GongGao

rwtTask[tMercenaryDaily.Task_43] = {}
rwtTask[tMercenaryDaily.Task_43]["Title"] = tLuaText[LANGUAGE_CONFIG][20569]
rwtTask[tMercenaryDaily.Task_43]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_43]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_43]["ReqCollectId1"] = nCollect_TanWei
rwtTask[tMercenaryDaily.Task_43]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_43]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_43]["DynaNpcGroupGen"][1]["GenId"] = nGenID_TanWei
rwtTask[tMercenaryDaily.Task_43]["DynaNpcGroupGen"][1]["MapId"] = 1000
rwtTask[tMercenaryDaily.Task_43]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_43]["TaskTimes"] = 3
rwtTask[tMercenaryDaily.Task_43]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_43]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_43]["AcceptDialogId"] = 11062
rwtTask[tMercenaryDaily.Task_43]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_43]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_43]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_43]["StartAutoWay"]["FindWayMapId"] = 1000
rwtTask[tMercenaryDaily.Task_43]["StartAutoWay"]["FindWayGroupId"] = nCollect_TanWei
rwtTask[tMercenaryDaily.Task_43]["StartAutoWay"]["FindWayGenId"] = nGenID_TanWei

rwtTask[tMercenaryDaily.Task_44] = {}
rwtTask[tMercenaryDaily.Task_44]["Title"] = tLuaText[LANGUAGE_CONFIG][20570]
rwtTask[tMercenaryDaily.Task_44]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_44]["TaskTimes"] = 5
rwtTask[tMercenaryDaily.Task_44]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_44]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_44]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_44]["TaskNpc"] = 3201
rwtTask[tMercenaryDaily.Task_44]["AcceptDialogId"] = 11063
rwtTask[tMercenaryDaily.Task_44]["DialogId"] = 11064
rwtTask[tMercenaryDaily.Task_44]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_44]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_44]["StartAutoWay"]["FindWayMapId"] = 1000
rwtTask[tMercenaryDaily.Task_44]["StartAutoWay"]["FindWayGroupId"] = 20229
rwtTask[tMercenaryDaily.Task_44]["StartAutoWay"]["FindWayGenId"] = 1000048

rwtTask[tMercenaryDaily.Task_45] = {}
rwtTask[tMercenaryDaily.Task_45]["Title"] = tLuaText[LANGUAGE_CONFIG][20571]
rwtTask[tMercenaryDaily.Task_45]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_45]["TaskTimes"] = 6
rwtTask[tMercenaryDaily.Task_45]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_45]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_45]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_45]["TaskNpc"] = 3269
rwtTask[tMercenaryDaily.Task_45]["AcceptDialogId"] = 11065
rwtTask[tMercenaryDaily.Task_45]["DialogId"] = 11066
rwtTask[tMercenaryDaily.Task_45]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_45]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_45]["StartAutoWay"]["FindWayMapId"] = 1000
rwtTask[tMercenaryDaily.Task_45]["StartAutoWay"]["FindWayGroupId"] = 20150
rwtTask[tMercenaryDaily.Task_45]["StartAutoWay"]["FindWayGenId"] = 1000016

rwtTask[tMercenaryDaily.Task_46] = {}
rwtTask[tMercenaryDaily.Task_46]["Title"] = tLuaText[LANGUAGE_CONFIG][20572]
rwtTask[tMercenaryDaily.Task_46]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_46]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_46]["ReqCollectId1"] = nCollect_XinXiang
rwtTask[tMercenaryDaily.Task_46]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_46]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_46]["DynaNpcGroupGen"][1]["GenId"] = nGenID_XinXiang
rwtTask[tMercenaryDaily.Task_46]["DynaNpcGroupGen"][1]["MapId"] = 1000
rwtTask[tMercenaryDaily.Task_46]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_46]["TaskTimes"] = 7
rwtTask[tMercenaryDaily.Task_46]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_46]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_46]["AcceptDialogId"] = 11067
rwtTask[tMercenaryDaily.Task_46]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_46]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_46]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_46]["StartAutoWay"]["FindWayMapId"] = 1000
rwtTask[tMercenaryDaily.Task_46]["StartAutoWay"]["FindWayGroupId"] = nCollect_XinXiang
rwtTask[tMercenaryDaily.Task_46]["StartAutoWay"]["FindWayGenId"] = nGenID_XinXiang

rwtTask[tMercenaryDaily.Task_47] = {}
rwtTask[tMercenaryDaily.Task_47]["Title"] = tLuaText[LANGUAGE_CONFIG][20573]
rwtTask[tMercenaryDaily.Task_47]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_47]["TaskTimes"] = 9
rwtTask[tMercenaryDaily.Task_47]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_47]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_47]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_47]["TaskNpc"] = 3365
rwtTask[tMercenaryDaily.Task_47]["AcceptDialogId"] = 11068
rwtTask[tMercenaryDaily.Task_47]["DialogId"] = 11069
rwtTask[tMercenaryDaily.Task_47]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_47]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_47]["StartAutoWay"]["FindWayMapId"] = 1000
rwtTask[tMercenaryDaily.Task_47]["StartAutoWay"]["FindWayGroupId"] = 20390
rwtTask[tMercenaryDaily.Task_47]["StartAutoWay"]["FindWayGenId"] = 1000120

rwtTask[tMercenaryDaily.Task_48] = {}
rwtTask[tMercenaryDaily.Task_48]["Title"] = tLuaText[LANGUAGE_CONFIG][20574]
rwtTask[tMercenaryDaily.Task_48]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_48]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_48]["ReqCollectId1"] = nCollect_HuoXiang
rwtTask[tMercenaryDaily.Task_48]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_48]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_48]["DynaNpcGroupGen"][1]["GenId"] = nGenID_HuoXiang
rwtTask[tMercenaryDaily.Task_48]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_48]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_48]["TaskTimes"] = 7
rwtTask[tMercenaryDaily.Task_48]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_48]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_48]["AcceptDialogId"] = 11070
rwtTask[tMercenaryDaily.Task_48]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_48]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_48]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_48]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tMercenaryDaily.Task_48]["StartAutoWay"]["FindWayGroupId"] = nCollect_HuoXiang
rwtTask[tMercenaryDaily.Task_48]["StartAutoWay"]["FindWayGenId"] = nGenID_HuoXiang


rwtTask[tMercenaryDaily.Task_49] = {}
rwtTask[tMercenaryDaily.Task_49]["Title"] = tLuaText[LANGUAGE_CONFIG][20575]
rwtTask[tMercenaryDaily.Task_49]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_49]["TaskTimes"] = 8
rwtTask[tMercenaryDaily.Task_49]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_49]["DailyTaskTownId"] = 200101
rwtTask[tMercenaryDaily.Task_49]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_49]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_49]["DynaNpcGroupGen"][1]["GenId"] = 2001961 
rwtTask[tMercenaryDaily.Task_49]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_49]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_49]["KillMonsterGroup1" ]= 900299
rwtTask[tMercenaryDaily.Task_49]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_49]["AcceptDialogId"] = 11071
rwtTask[tMercenaryDaily.Task_49]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_49]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tMercenaryDaily.Task_49]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tMercenaryDaily.Task_49]["StartAutoWay"]["FindWayGroupId"] = 900299
rwtTask[tMercenaryDaily.Task_49]["StartAutoWay"]["FindWayGenId"] = 2001961

rwtTask[tMercenaryDaily.Task_50] = {}
rwtTask[tMercenaryDaily.Task_50]["Title"] = tLuaText[LANGUAGE_CONFIG][20576]
rwtTask[tMercenaryDaily.Task_50]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_50]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_50]["ReqCollectId1"] = nCollect_YeiZi
rwtTask[tMercenaryDaily.Task_50]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_50]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_50]["DynaNpcGroupGen"][1]["GenId"] = nGenID_YeiZi
rwtTask[tMercenaryDaily.Task_50]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_50]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_50]["TaskTimes"] = 3
rwtTask[tMercenaryDaily.Task_50]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_50]["DailyTaskTownId"] = 200102
rwtTask[tMercenaryDaily.Task_50]["AcceptDialogId"] = 11072
rwtTask[tMercenaryDaily.Task_50]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_50]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_50]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_50]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tMercenaryDaily.Task_50]["StartAutoWay"]["FindWayGroupId"] = nCollect_YeiZi
rwtTask[tMercenaryDaily.Task_50]["StartAutoWay"]["FindWayGenId"] = nGenID_YeiZi

rwtTask[tMercenaryDaily.Task_51] = {}
rwtTask[tMercenaryDaily.Task_51]["Title"] = tLuaText[LANGUAGE_CONFIG][20577]
rwtTask[tMercenaryDaily.Task_51]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_51]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_51]["ReqCollectId1"] = nCollect_XueSeHua
rwtTask[tMercenaryDaily.Task_51]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_51]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_51]["DynaNpcGroupGen"][1]["GenId"] = nGenID_XueSeHua
rwtTask[tMercenaryDaily.Task_51]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_51]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_51]["TaskTimes"] = 7
rwtTask[tMercenaryDaily.Task_51]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_51]["DailyTaskTownId"] = 200104
rwtTask[tMercenaryDaily.Task_51]["AcceptDialogId"] = 11073
rwtTask[tMercenaryDaily.Task_51]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_51]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_51]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_51]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tMercenaryDaily.Task_51]["StartAutoWay"]["FindWayGroupId"] = nCollect_XueSeHua
rwtTask[tMercenaryDaily.Task_51]["StartAutoWay"]["FindWayGenId"] = nGenID_XueSeHua

rwtTask[tMercenaryDaily.Task_52] = {}
rwtTask[tMercenaryDaily.Task_52]["Title"] = tLuaText[LANGUAGE_CONFIG][20578]
rwtTask[tMercenaryDaily.Task_52]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_52]["TaskTimes"] = 8
rwtTask[tMercenaryDaily.Task_52]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_52]["DailyTaskTownId"] = 200104
rwtTask[tMercenaryDaily.Task_52]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_52]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_52]["DynaNpcGroupGen"][1]["GenId"] = 2001964 
rwtTask[tMercenaryDaily.Task_52]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_52]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_52]["KillMonsterGroup1" ]= 900300
rwtTask[tMercenaryDaily.Task_52]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tMercenaryDaily.Task_52]["AcceptDialogId"] = 11074
rwtTask[tMercenaryDaily.Task_52]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_52]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tMercenaryDaily.Task_52]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tMercenaryDaily.Task_52]["StartAutoWay"]["FindWayGroupId"] = 900300
rwtTask[tMercenaryDaily.Task_52]["StartAutoWay"]["FindWayGenId"] = 2001964

rwtTask[tMercenaryDaily.Task_53] = {}
rwtTask[tMercenaryDaily.Task_53]["Title"] = tLuaText[LANGUAGE_CONFIG][20579]
rwtTask[tMercenaryDaily.Task_53]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_53]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_53]["ReqCollectId1"] = nCollect_MoTongKuang
rwtTask[tMercenaryDaily.Task_53]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_53]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_53]["DynaNpcGroupGen"][1]["GenId"] = nGenID_MoTongKuang
rwtTask[tMercenaryDaily.Task_53]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_53]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_53]["TaskTimes"] = 3
rwtTask[tMercenaryDaily.Task_53]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_53]["DailyTaskTownId"] = 200105
rwtTask[tMercenaryDaily.Task_53]["AcceptDialogId"] = 11075
rwtTask[tMercenaryDaily.Task_53]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_53]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_53]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_53]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tMercenaryDaily.Task_53]["StartAutoWay"]["FindWayGroupId"] = nCollect_MoTongKuang
rwtTask[tMercenaryDaily.Task_53]["StartAutoWay"]["FindWayGenId"] = nGenID_MoTongKuang

rwtTask[tMercenaryDaily.Task_54] = {}
rwtTask[tMercenaryDaily.Task_54]["Title"] = tLuaText[LANGUAGE_CONFIG][20580]
rwtTask[tMercenaryDaily.Task_54]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_54]["TaskTimes"] = 6
rwtTask[tMercenaryDaily.Task_54]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_54]["DailyTaskTownId"] = 200105
rwtTask[tMercenaryDaily.Task_54]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tMercenaryDaily.Task_54]["TaskNpc"] = 3376
rwtTask[tMercenaryDaily.Task_54]["AcceptDialogId"] = 11076
rwtTask[tMercenaryDaily.Task_54]["DialogId"] = 11077
rwtTask[tMercenaryDaily.Task_54]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_54]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_54]["DynaNpcGroupGen"][1]["GenId"] = 2001966
rwtTask[tMercenaryDaily.Task_54]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_54]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_54]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_54]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_54]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tMercenaryDaily.Task_54]["StartAutoWay"]["FindWayGroupId"] = 20406
rwtTask[tMercenaryDaily.Task_54]["StartAutoWay"]["FindWayGenId"] = 2001966

rwtTask[tMercenaryDaily.Task_55] = {}
rwtTask[tMercenaryDaily.Task_55]["Title"] = tLuaText[LANGUAGE_CONFIG][20581]
rwtTask[tMercenaryDaily.Task_55]["TaskType"] = CONST_TASK_TYPE.MERCENARY_DAILY
rwtTask[tMercenaryDaily.Task_55]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tMercenaryDaily.Task_55]["ReqCollectId1"] = nCollect_MoZuShuiJing
rwtTask[tMercenaryDaily.Task_55]["DynaNpcGroupGen"] = {}
rwtTask[tMercenaryDaily.Task_55]["DynaNpcGroupGen"][1] = {}
rwtTask[tMercenaryDaily.Task_55]["DynaNpcGroupGen"][1]["GenId"] = nGenID_MoZuShuiJing
rwtTask[tMercenaryDaily.Task_55]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tMercenaryDaily.Task_55]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tMercenaryDaily.Task_55]["TaskTimes"] = 7
rwtTask[tMercenaryDaily.Task_55]["DailyTaskAreaId"] = 2001
rwtTask[tMercenaryDaily.Task_55]["DailyTaskTownId"] = 200106
rwtTask[tMercenaryDaily.Task_55]["AcceptDialogId"] = 11078
rwtTask[tMercenaryDaily.Task_55]["StartAutoWay"] = {}
rwtTask[tMercenaryDaily.Task_55]["StartAutoWay"]["FindWayData"] = {}
rwtTask[tMercenaryDaily.Task_55]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tMercenaryDaily.Task_55]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tMercenaryDaily.Task_55]["StartAutoWay"]["FindWayGroupId"] = nCollect_MoZuShuiJing
rwtTask[tMercenaryDaily.Task_55]["StartAutoWay"]["FindWayGenId"] = nGenID_MoZuShuiJing
