----region *.lua
----Date
----此文件由[BabeLua]插件自动生成
----湖畔镇佣兵任务

--10259-10271
----endregion

--陷阱
local nGenId_Trap_1 = 2001664
local nGenId_Trap_2 = 2001665

--怪物
local nGenId_Monster_1 = 2001666
local nGenId_Monster_2 = 2001667

--NPC
local nNpc_HaiLi = 3036 -- 海莉大妈


local nHuPanZhenMercenaryTask_1 = 20021         --桑妮的信
local nHuPanZhenMercenaryTask_2 = 20022         --桑妮的信
local nHuPanZhenMercenaryTask_3 = 20023         --桑妮的信
local nHuPanZhenMercenaryTask_4 = 20024         --桑妮的信
local nHuPanZhenMercenaryTask_5 = 20025         --桑妮的信
local nHuPanZhenMercenaryTask_6 = 20026         --新鲜食材
local nHuPanZhenMercenaryTask_7 = 20027         --新鲜食材
local nHuPanZhenMercenaryTask_8 = 20028         --新鲜食材
local nHuPanZhenMercenaryTask_9 = 20029         --新鲜食材
local nHuPanZhenMercenaryTask_10 = 20030         --新鲜食材
local nHuPanZhenMercenaryTask_11 = 20031         --嘘，密信
local nHuPanZhenMercenaryTask_12 = 20032         --嘘，密信
local nHuPanZhenMercenaryTask_13 = 20033         --嘘，密信
local nHuPanZhenMercenaryTask_14 = 20034         --嘘，密信
local nHuPanZhenMercenaryTask_15 = 20035         --嘘，密信
--local nHuPanZhenMercenaryTask_16 = 20036         --宝贝回家
--local nHuPanZhenMercenaryTask_17 = 20037         --宝贝回家
--local nHuPanZhenMercenaryTask_18 = 20038         --宝贝回家
--local nHuPanZhenMercenaryTask_19 = 20039         --宝贝回家
--local nHuPanZhenMercenaryTask_20 = 20040         --宝贝回家
local nHuPanZhenMercenaryTask_21 = 20041         --宝贝回家
local nHuPanZhenMercenaryTask_22 = 20042         --宝贝回家
local nHuPanZhenMercenaryTask_23 = 20043         --宝贝回家
local nHuPanZhenMercenaryTask_24 = 20044         --宝贝回家
local nHuPanZhenMercenaryTask_25 = 20045         --宝贝回家
local nHuPanZhenMercenaryTask_26 = 20046         --走开！走开！
local nHuPanZhenMercenaryTask_27 = 20047         --走开！走开！
local nHuPanZhenMercenaryTask_28 = 20048         --走开！走开！
local nHuPanZhenMercenaryTask_29 = 20049         --走开！走开！
local nHuPanZhenMercenaryTask_30 = 20050         --走开！走开！
local nHuPanZhenMercenaryTask_31 = 20051         --舌尖上的湖畔镇	 --舌尖上的美食
local nHuPanZhenMercenaryTask_32 = 20052         --舌尖上的湖畔镇
local nHuPanZhenMercenaryTask_33 = 20053         --舌尖上的湖畔镇
local nHuPanZhenMercenaryTask_34 = 20054         --舌尖上的湖畔镇
local nHuPanZhenMercenaryTask_35 = 20055         --舌尖上的湖畔镇
local nHuPanZhenMercenaryTask_36 = 20056         --破坏者的末路	     --鹿角生物
local nHuPanZhenMercenaryTask_37 = 20057         --破坏者的末路
local nHuPanZhenMercenaryTask_38 = 20058         --破坏者的末路
local nHuPanZhenMercenaryTask_39 = 20059         --破坏者的末路
local nHuPanZhenMercenaryTask_40 = 20060         --破坏者的末路
local nHuPanZhenMercenaryTask_41 = 20061         --佣兵的自我修养
local nHuPanZhenMercenaryTask_42 = 20062         --佣兵的自我修养
local nHuPanZhenMercenaryTask_43 = 20063         --佣兵的自我修养
local nHuPanZhenMercenaryTask_44 = 20064         --佣兵的自我修养
local nHuPanZhenMercenaryTask_45 = 20065         --佣兵的自我修养
local nHuPanZhenMercenaryTask_46 = 20066         --《雷鸣大陆编年史》
local nHuPanZhenMercenaryTask_47 = 20067         --《雷鸣大陆编年史》
local nHuPanZhenMercenaryTask_48 = 20068         --《雷鸣大陆编年史》
local nHuPanZhenMercenaryTask_49 = 20069         --《雷鸣大陆编年史》
local nHuPanZhenMercenaryTask_50 = 20070         --《雷鸣大陆编年史》
local nHuPanZhenMercenaryTask_51 = 20071         --夺回密宝
local nHuPanZhenMercenaryTask_52 = 20072         --夺回密宝
local nHuPanZhenMercenaryTask_53 = 20073         --夺回密宝
local nHuPanZhenMercenaryTask_54 = 20074         --夺回密宝
local nHuPanZhenMercenaryTask_55 = 20075         --夺回密宝

--新增佣兵委托任务
local tHuPanZhenMercenaryTask = {}
--击退兽潮
tHuPanZhenMercenaryTask.NewAdd1 = 20336
tHuPanZhenMercenaryTask.NewAdd2 = 20337
tHuPanZhenMercenaryTask.NewAdd3 = 20338
tHuPanZhenMercenaryTask.NewAdd4 = 20339
tHuPanZhenMercenaryTask.NewAdd5 = 20340

--碎魂狼王的复仇
tHuPanZhenMercenaryTask.NewAdd6 = 20341
tHuPanZhenMercenaryTask.NewAdd7 = 20342
tHuPanZhenMercenaryTask.NewAdd8 = 20343
tHuPanZhenMercenaryTask.NewAdd9 = 20344
tHuPanZhenMercenaryTask.NewAdd10 = 20345

--神秘怪物的来历
tHuPanZhenMercenaryTask.NewAdd11 = 20346
tHuPanZhenMercenaryTask.NewAdd12 = 20347
tHuPanZhenMercenaryTask.NewAdd13 = 20348
tHuPanZhenMercenaryTask.NewAdd14 = 20349
tHuPanZhenMercenaryTask.NewAdd15 = 20350

--联盟通缉令
tHuPanZhenMercenaryTask.NewAdd16 = 20351
tHuPanZhenMercenaryTask.NewAdd17 = 20352
tHuPanZhenMercenaryTask.NewAdd18 = 20353
tHuPanZhenMercenaryTask.NewAdd19 = 20354
tHuPanZhenMercenaryTask.NewAdd20 = 20355


local nNpc_SanNi = 2035
local nNpc_LvGuanLaoBan = 3044 --旅馆老板
local nNpc_TanYuan = 3045 --秘密探员
local nNpc_XiEr = 3048   --老希尔

local nCollect_QingHuBei = 60047  --青湖贝	  --青花贝

local nMonsterGroup_PoHuaiZhe = 900147  --鹿角兽破坏者
local nMonsterGroup_ShouLing = 200156  --副本BOSS

--新增任务怪
local nMonsterGroup_NewAdd1 = 900320      --白眼独狼
local nMonsterGroup_NewAdd1_GenId = 20010043    
  
local nMonsterGroup_NewAdd2 = 900321      --碎魂狼王
local nMonsterGroup_NewAdd2_GenId = 20010044      
  
local nMonsterGroup_NewAdd4 = 900322      --劫匪哥布林
local nMonsterGroup_NewAdd4_GenId = 20010045      

local nMonster_NewAdd1 = 9000237
local nMonster_NewAdd2 = 9000238
local nMonster_NewAdd4 = 9000239
------------------------------------对白id-------------------
--护送陷阱战前对白
local nDialog_TrapMonsterDialog = 11041
    
rwtNpcGroup[nCollect_QingHuBei] = rwtNpcGroup[nCollect_QingHuBei] or {}
rwtNpcGroup[nCollect_QingHuBei]["Type"] = CONST_NPCGROUP_TYPE.Collect

--新增任务对白
--接受任务对白
local nAcceptDialog_NewAdd1 = 11289
local nAcceptDialog_NewAdd2 = 11290
local nAcceptDialog_NewAdd3 = 11291
local nAcceptDialog_NewAdd4 = 11292

-----------------坐标---------------
local sPos_ChuWuShi = "-7.79,0.05,-15.66"
----------------------------------------------------------------------
--------------------------------逻辑----------------------------------
--护送陷阱
rwtNpcGroup[30179] = rwtNpcGroup[30179] or {}
rwtNpcGroup[30179]["Type"] = CONST_NPCGROUP_TYPE.Trap
rwtNpcGroup[30179]["EscortMonsterGroupGen"] = nGenId_Monster_1
rwtNpcGroup[30179]["EscortDialog"] = nDialog_TrapMonsterDialog

--rwtNpcGroup[30179]["TrapFunc"] = function ()
--	if not rwHasGenEvent(nGenId_Monster_1) then  	
--		rwAddGenEvent(nGenId_Monster_1) 
--	end
--	rwDelGenEvent(2001664)
--	rwAutoBattle(nGenId_Monster_1)	
--end

rwtNpcGroup[30180] = rwtNpcGroup[30180] or {}
rwtNpcGroup[30180]["Type"] = CONST_NPCGROUP_TYPE.Trap
rwtNpcGroup[30180]["EscortMonsterGroupGen"] = nGenId_Monster_2
rwtNpcGroup[30180]["EscortDialog"] = nDialog_TrapMonsterDialog

rwtDialog[nDialog_TrapMonsterDialog] = rwtDialog[nDialog_TrapMonsterDialog] or {}
rwtDialog[nDialog_TrapMonsterDialog]["DialogEndInit"] = {}
rwtDialog[nDialog_TrapMonsterDialog]["DialogEndInit"]["Events"] = {}
rwtDialog[nDialog_TrapMonsterDialog]["DialogEndInit"]["Events"][1] = {}
rwtDialog[nDialog_TrapMonsterDialog]["DialogEndInit"]["Events"][1]["AutoBattle"] = {}
rwtDialog[nDialog_TrapMonsterDialog]["DialogEndInit"]["Events"][1]["AutoBattle"]["GenIdBynId"] = true

--rwtNpcGroup[30180]["TrapFunc"] = function ()
--	if not rwHasGenEvent(nGenId_Monster_2) then  	
--		rwAddGenEvent(nGenId_Monster_2) 
--	end
--	rwDelGenEvent(2001665)
--	rwAutoBattle(nGenId_Monster_2)	
--end


----***************************任务***************************----
rwtTask[nHuPanZhenMercenaryTask_1] = {}
rwtTask[nHuPanZhenMercenaryTask_1]["Title"] =tLuaText[LANGUAGE_CONFIG][20627]
rwtTask[nHuPanZhenMercenaryTask_1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_1]["TaskQuality"] = 1
rwtTask[nHuPanZhenMercenaryTask_1]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_1]["TaskNpc"] = nNpc_SanNi
rwtTask[nHuPanZhenMercenaryTask_1]["DialogId"] = 10193
rwtTask[nHuPanZhenMercenaryTask_1]["AcceptDialogId"] = 10259
rwtTask[nHuPanZhenMercenaryTask_1]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_1]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_1]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_1]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_1]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_1]["StartAutoWay"]["FindWayPos"] = "8.82,0.13,-18.23"

rwtTask[nHuPanZhenMercenaryTask_2] = {}
rwtTask[nHuPanZhenMercenaryTask_2]["Title"] = tLuaText[LANGUAGE_CONFIG][20628]
rwtTask[nHuPanZhenMercenaryTask_2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_2]["TaskQuality"] = 2
rwtTask[nHuPanZhenMercenaryTask_2]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_2]["TaskNpc"] = nNpc_SanNi
rwtTask[nHuPanZhenMercenaryTask_2]["DialogId"] = 10193
rwtTask[nHuPanZhenMercenaryTask_2]["AcceptDialogId"] = 10259
rwtTask[nHuPanZhenMercenaryTask_2]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_2]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_2]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_2]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_2]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_2]["StartAutoWay"]["FindWayPos"] = "8.82,0.13,-18.23"

rwtTask[nHuPanZhenMercenaryTask_3] = {}
rwtTask[nHuPanZhenMercenaryTask_3]["Title"] = tLuaText[LANGUAGE_CONFIG][20629]
rwtTask[nHuPanZhenMercenaryTask_3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_3]["TaskQuality"] = 3
rwtTask[nHuPanZhenMercenaryTask_3]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_3]["TaskNpc"] = nNpc_SanNi
rwtTask[nHuPanZhenMercenaryTask_3]["DialogId"] = 10193
rwtTask[nHuPanZhenMercenaryTask_3]["AcceptDialogId"] = 10259
rwtTask[nHuPanZhenMercenaryTask_3]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_3]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_3]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_3]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_3]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_3]["StartAutoWay"]["FindWayPos"] = "8.82,0.13,-18.23"

rwtTask[nHuPanZhenMercenaryTask_4] = {}
rwtTask[nHuPanZhenMercenaryTask_4]["Title"] = tLuaText[LANGUAGE_CONFIG][20630]
rwtTask[nHuPanZhenMercenaryTask_4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_4]["TaskQuality"] = 4
rwtTask[nHuPanZhenMercenaryTask_4]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_4]["TaskNpc"] = nNpc_SanNi
rwtTask[nHuPanZhenMercenaryTask_4]["DialogId"] = 10193
rwtTask[nHuPanZhenMercenaryTask_4]["AcceptDialogId"] = 10259
rwtTask[nHuPanZhenMercenaryTask_4]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_4]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_4]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_4]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_4]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_4]["StartAutoWay"]["FindWayPos"] = "8.82,0.13,-18.23"

rwtTask[nHuPanZhenMercenaryTask_5] = {}
rwtTask[nHuPanZhenMercenaryTask_5]["Title"] = tLuaText[LANGUAGE_CONFIG][20631]
rwtTask[nHuPanZhenMercenaryTask_5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_5]["TaskQuality"] = 5
rwtTask[nHuPanZhenMercenaryTask_5]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_5]["TaskNpc"] = nNpc_SanNi
rwtTask[nHuPanZhenMercenaryTask_5]["DialogId"] = 10193
rwtTask[nHuPanZhenMercenaryTask_5]["AcceptDialogId"] = 10259
rwtTask[nHuPanZhenMercenaryTask_5]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_5]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_5]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_5]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_5]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_5]["StartAutoWay"]["FindWayPos"] = "8.82,0.13,-18.23"

rwtTask[nHuPanZhenMercenaryTask_6] = {}
rwtTask[nHuPanZhenMercenaryTask_6]["Title"] = tLuaText[LANGUAGE_CONFIG][20632]
rwtTask[nHuPanZhenMercenaryTask_6]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_6]["TaskQuality"] = 1
rwtTask[nHuPanZhenMercenaryTask_6]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_6]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_6]["TaskNpc"] = nNpc_LvGuanLaoBan
rwtTask[nHuPanZhenMercenaryTask_6]["DialogId"] = 10194
rwtTask[nHuPanZhenMercenaryTask_6]["AcceptDialogId"] = 10260
rwtTask[nHuPanZhenMercenaryTask_6]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_6]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_6]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_6]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_6]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_6]["StartAutoWay"]["FindWayPos"] = "-2.33,0.05,-1.83"

rwtTask[nHuPanZhenMercenaryTask_7] = {}
rwtTask[nHuPanZhenMercenaryTask_7]["Title"] = tLuaText[LANGUAGE_CONFIG][20633]
rwtTask[nHuPanZhenMercenaryTask_7]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_7]["TaskQuality"] = 2
rwtTask[nHuPanZhenMercenaryTask_7]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_7]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_7]["TaskNpc"] = nNpc_LvGuanLaoBan
rwtTask[nHuPanZhenMercenaryTask_7]["DialogId"] = 10194
rwtTask[nHuPanZhenMercenaryTask_7]["AcceptDialogId"] = 10260
rwtTask[nHuPanZhenMercenaryTask_7]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_7]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_7]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_7]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_7]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_7]["StartAutoWay"]["FindWayPos"] = "-2.33,0.05,-1.83"

rwtTask[nHuPanZhenMercenaryTask_8] = {}
rwtTask[nHuPanZhenMercenaryTask_8]["Title"] = tLuaText[LANGUAGE_CONFIG][20634]
rwtTask[nHuPanZhenMercenaryTask_8]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_8]["TaskQuality"] = 3
rwtTask[nHuPanZhenMercenaryTask_8]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_8]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_8]["TaskNpc"] = nNpc_LvGuanLaoBan
rwtTask[nHuPanZhenMercenaryTask_8]["DialogId"] = 10194
rwtTask[nHuPanZhenMercenaryTask_8]["AcceptDialogId"] = 10260
rwtTask[nHuPanZhenMercenaryTask_8]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_8]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_8]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_8]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_8]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_8]["StartAutoWay"]["FindWayPos"] = "-2.33,0.05,-1.83"

rwtTask[nHuPanZhenMercenaryTask_9] = {}
rwtTask[nHuPanZhenMercenaryTask_9]["Title"] = tLuaText[LANGUAGE_CONFIG][20635]
rwtTask[nHuPanZhenMercenaryTask_9]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_9]["TaskQuality"] = 4
rwtTask[nHuPanZhenMercenaryTask_9]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_9]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_9]["TaskNpc"] = nNpc_LvGuanLaoBan
rwtTask[nHuPanZhenMercenaryTask_9]["DialogId"] = 10194
rwtTask[nHuPanZhenMercenaryTask_9]["AcceptDialogId"] = 10260
rwtTask[nHuPanZhenMercenaryTask_9]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_9]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_9]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_9]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_9]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_9]["StartAutoWay"]["FindWayPos"] = "-2.33,0.05,-1.83"

rwtTask[nHuPanZhenMercenaryTask_10] = {}
rwtTask[nHuPanZhenMercenaryTask_10]["Title"] = tLuaText[LANGUAGE_CONFIG][20636]
rwtTask[nHuPanZhenMercenaryTask_10]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_10]["TaskQuality"] = 5
rwtTask[nHuPanZhenMercenaryTask_10]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_10]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_10]["TaskNpc"] = nNpc_LvGuanLaoBan
rwtTask[nHuPanZhenMercenaryTask_10]["DialogId"] = 10194
rwtTask[nHuPanZhenMercenaryTask_10]["AcceptDialogId"] = 10260
rwtTask[nHuPanZhenMercenaryTask_10]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_10]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_10]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_10]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[nHuPanZhenMercenaryTask_10]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_10]["StartAutoWay"]["FindWayPos"] = "-2.33,0.05,-1.83"

rwtTask[nHuPanZhenMercenaryTask_11] = {}
rwtTask[nHuPanZhenMercenaryTask_11]["Title"] = tLuaText[LANGUAGE_CONFIG][20637]
rwtTask[nHuPanZhenMercenaryTask_11]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_11]["TaskQuality"] = 1
rwtTask[nHuPanZhenMercenaryTask_11]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_11]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_11]["TaskNpc"] = nNpc_TanYuan
rwtTask[nHuPanZhenMercenaryTask_11]["DialogId"] = 10195
rwtTask[nHuPanZhenMercenaryTask_11]["AcceptDialogId"] = 10261
rwtTask[nHuPanZhenMercenaryTask_11]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_11]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_11]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_11]["DynaNpcGroupGen"][1]["GenId"] = 2001122
rwtTask[nHuPanZhenMercenaryTask_11]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_11]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_11]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_11]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_11]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_11]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_11]["StartAutoWay"]["FindWayGroupId"] = 20076
rwtTask[nHuPanZhenMercenaryTask_11]["StartAutoWay"]["FindWayGenId"] = 2001122

rwtTask[nHuPanZhenMercenaryTask_12] = {}
rwtTask[nHuPanZhenMercenaryTask_12]["Title"] = tLuaText[LANGUAGE_CONFIG][20638]
rwtTask[nHuPanZhenMercenaryTask_12]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_12]["TaskQuality"] = 2
rwtTask[nHuPanZhenMercenaryTask_12]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_12]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_12]["TaskNpc"] = nNpc_TanYuan
rwtTask[nHuPanZhenMercenaryTask_12]["DialogId"] = 10195
rwtTask[nHuPanZhenMercenaryTask_12]["AcceptDialogId"] = 10261
rwtTask[nHuPanZhenMercenaryTask_12]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_12]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_12]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_12]["DynaNpcGroupGen"][1]["GenId"] = 2001122
rwtTask[nHuPanZhenMercenaryTask_12]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_12]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_12]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_12]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_12]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_12]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_12]["StartAutoWay"]["FindWayGroupId"] = 20076
rwtTask[nHuPanZhenMercenaryTask_12]["StartAutoWay"]["FindWayGenId"] = 2001122

rwtTask[nHuPanZhenMercenaryTask_13] = {}
rwtTask[nHuPanZhenMercenaryTask_13]["Title"] = tLuaText[LANGUAGE_CONFIG][20639]
rwtTask[nHuPanZhenMercenaryTask_13]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_13]["TaskQuality"] = 3
rwtTask[nHuPanZhenMercenaryTask_13]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_13]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_13]["TaskNpc"] = nNpc_TanYuan
rwtTask[nHuPanZhenMercenaryTask_13]["DialogId"] = 10195
rwtTask[nHuPanZhenMercenaryTask_13]["AcceptDialogId"] = 10261
rwtTask[nHuPanZhenMercenaryTask_13]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_13]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_13]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_13]["DynaNpcGroupGen"][1]["GenId"] = 2001122
rwtTask[nHuPanZhenMercenaryTask_13]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_13]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_13]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_13]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_13]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_13]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_13]["StartAutoWay"]["FindWayGroupId"] = 20076
rwtTask[nHuPanZhenMercenaryTask_13]["StartAutoWay"]["FindWayGenId"] = 2001122

rwtTask[nHuPanZhenMercenaryTask_14] = {}
rwtTask[nHuPanZhenMercenaryTask_14]["Title"] =tLuaText[LANGUAGE_CONFIG][20640]
rwtTask[nHuPanZhenMercenaryTask_14]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_14]["TaskQuality"] = 4
rwtTask[nHuPanZhenMercenaryTask_14]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_14]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_14]["TaskNpc"] = nNpc_TanYuan
rwtTask[nHuPanZhenMercenaryTask_14]["DialogId"] = 10195
rwtTask[nHuPanZhenMercenaryTask_14]["AcceptDialogId"] = 10261
rwtTask[nHuPanZhenMercenaryTask_14]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_14]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_14]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_14]["DynaNpcGroupGen"][1]["GenId"] = 2001122
rwtTask[nHuPanZhenMercenaryTask_14]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_14]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_14]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_14]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_14]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_14]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_14]["StartAutoWay"]["FindWayGroupId"] = 20076
rwtTask[nHuPanZhenMercenaryTask_14]["StartAutoWay"]["FindWayGenId"] = 2001122

rwtTask[nHuPanZhenMercenaryTask_15] = {}
rwtTask[nHuPanZhenMercenaryTask_15]["Title"] = tLuaText[LANGUAGE_CONFIG][20641]
rwtTask[nHuPanZhenMercenaryTask_15]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_15]["TaskQuality"] = 5
rwtTask[nHuPanZhenMercenaryTask_15]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_15]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_15]["TaskNpc"] = nNpc_TanYuan
rwtTask[nHuPanZhenMercenaryTask_15]["DialogId"] = 10195
rwtTask[nHuPanZhenMercenaryTask_15]["AcceptDialogId"] = 10261
rwtTask[nHuPanZhenMercenaryTask_15]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_15]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_15]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_15]["DynaNpcGroupGen"][1]["GenId"] = 2001122
rwtTask[nHuPanZhenMercenaryTask_15]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_15]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_15]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_15]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_15]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_15]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_15]["StartAutoWay"]["FindWayGroupId"] = 20076
rwtTask[nHuPanZhenMercenaryTask_15]["StartAutoWay"]["FindWayGenId"] = 2001122

--rwtTask[nHuPanZhenMercenaryTask_16] = {}
--rwtTask[nHuPanZhenMercenaryTask_16]["Title"] =tLuaText[LANGUAGE_CONFIG][20642]
--rwtTask[nHuPanZhenMercenaryTask_16]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_16]["TaskQuality"] = 1
--rwtTask[nHuPanZhenMercenaryTask_16]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_16]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_16]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_16]["AwardGroupId"] = 1

--rwtTask[nHuPanZhenMercenaryTask_17] = {}
--rwtTask[nHuPanZhenMercenaryTask_17]["Title"] = tLuaText[LANGUAGE_CONFIG][20643]
--rwtTask[nHuPanZhenMercenaryTask_17]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_17]["TaskQuality"] = 2
--rwtTask[nHuPanZhenMercenaryTask_17]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_17]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_17]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_17]["AwardGroupId"] = 1

--rwtTask[nHuPanZhenMercenaryTask_18] = {}
--rwtTask[nHuPanZhenMercenaryTask_18]["Title"] = tLuaText[LANGUAGE_CONFIG][20644]
--rwtTask[nHuPanZhenMercenaryTask_18]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_18]["TaskQuality"] = 3
--rwtTask[nHuPanZhenMercenaryTask_18]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_18]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_18]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_18]["AwardGroupId"] = 1

--rwtTask[nHuPanZhenMercenaryTask_19] = {}
--rwtTask[nHuPanZhenMercenaryTask_19]["Title"] = tLuaText[LANGUAGE_CONFIG][20645]
--rwtTask[nHuPanZhenMercenaryTask_19]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_19]["TaskQuality"] = 4
--rwtTask[nHuPanZhenMercenaryTask_19]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_19]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_19]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_19]["AwardGroupId"] = 1

--rwtTask[nHuPanZhenMercenaryTask_20] = {}
--rwtTask[nHuPanZhenMercenaryTask_20]["Title"] = tLuaText[LANGUAGE_CONFIG][20646]
--rwtTask[nHuPanZhenMercenaryTask_20]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_20]["TaskQuality"] = 5
--rwtTask[nHuPanZhenMercenaryTask_20]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_20]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_20]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_20]["AwardGroupId"] = 1

rwtTask[nHuPanZhenMercenaryTask_21] = {}
rwtTask[nHuPanZhenMercenaryTask_21]["Title"] =tLuaText[LANGUAGE_CONFIG][20647]
rwtTask[nHuPanZhenMercenaryTask_21]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_21]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_21]["TaskQuality"] = 1
rwtTask[nHuPanZhenMercenaryTask_21]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_21]["DialogId"] = 10196
rwtTask[nHuPanZhenMercenaryTask_21]["TaskNpc"] = nNpc_HaiLi
rwtTask[nHuPanZhenMercenaryTask_21]["AwardGroupId"] = 4
rwtTask[nHuPanZhenMercenaryTask_21]["AcceptDialogId"] = 10262
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"] = {}
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"][1] = {}
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"][1]["GenId"] = 2001664
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"][1]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"][2] = {}
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"][2]["GenId"] = 2001665
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"][2]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_21]["DynaNpcGroupGen"][2]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_21]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_21]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_21]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_21]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_21]["StartAutoWay"]["FindWayGroupId"] = 20047
rwtTask[nHuPanZhenMercenaryTask_21]["StartAutoWay"]["FindWayGenId"] = 2001104

rwtTask[nHuPanZhenMercenaryTask_22] = {}
rwtTask[nHuPanZhenMercenaryTask_22]["Title"] = tLuaText[LANGUAGE_CONFIG][20648]
rwtTask[nHuPanZhenMercenaryTask_22]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_22]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_22]["TaskQuality"] = 2
rwtTask[nHuPanZhenMercenaryTask_22]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_22]["DialogId"] = 10196
rwtTask[nHuPanZhenMercenaryTask_22]["TaskNpc"] = nNpc_HaiLi
rwtTask[nHuPanZhenMercenaryTask_22]["AwardGroupId"] = 4
rwtTask[nHuPanZhenMercenaryTask_22]["AcceptDialogId"] = 10262
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"] = {}
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"][1] = {}
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"][1]["GenId"] = 2001664
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"][1]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"][2] = {}
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"][2]["GenId"] = 2001665
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"][2]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_22]["DynaNpcGroupGen"][2]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_22]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_22]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_22]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_22]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_22]["StartAutoWay"]["FindWayGroupId"] = 20047
rwtTask[nHuPanZhenMercenaryTask_22]["StartAutoWay"]["FindWayGenId"] = 2001104

rwtTask[nHuPanZhenMercenaryTask_23] = {}
rwtTask[nHuPanZhenMercenaryTask_23]["Title"] = tLuaText[LANGUAGE_CONFIG][20649]
rwtTask[nHuPanZhenMercenaryTask_23]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_23]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_23]["TaskQuality"] = 3
rwtTask[nHuPanZhenMercenaryTask_23]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_23]["DialogId"] = 10196
rwtTask[nHuPanZhenMercenaryTask_23]["TaskNpc"] = nNpc_HaiLi
rwtTask[nHuPanZhenMercenaryTask_23]["AwardGroupId"] = 4
rwtTask[nHuPanZhenMercenaryTask_23]["AcceptDialogId"] = 10262
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"] = {}
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"][1] = {}
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"][1]["GenId"] = 2001664
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"][1]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"][2] = {}
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"][2]["GenId"] = 2001665
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"][2]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_23]["DynaNpcGroupGen"][2]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_23]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_23]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_23]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_23]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_23]["StartAutoWay"]["FindWayGroupId"] = 20047
rwtTask[nHuPanZhenMercenaryTask_23]["StartAutoWay"]["FindWayGenId"] = 2001104

rwtTask[nHuPanZhenMercenaryTask_24] = {}
rwtTask[nHuPanZhenMercenaryTask_24]["Title"] = tLuaText[LANGUAGE_CONFIG][20650]
rwtTask[nHuPanZhenMercenaryTask_24]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_24]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_24]["TaskQuality"] = 4
rwtTask[nHuPanZhenMercenaryTask_24]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_24]["DialogId"] = 10196
rwtTask[nHuPanZhenMercenaryTask_24]["TaskNpc"] = nNpc_HaiLi
rwtTask[nHuPanZhenMercenaryTask_24]["AwardGroupId"] = 4
rwtTask[nHuPanZhenMercenaryTask_24]["AcceptDialogId"] = 10262
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"] = {}
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"][1] = {}
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"][1]["GenId"] = 2001664
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"][1]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"][2] = {}
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"][2]["GenId"] = 2001665
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"][2]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_24]["DynaNpcGroupGen"][2]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_24]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_24]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_24]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_24]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_24]["StartAutoWay"]["FindWayGroupId"] = 20047
rwtTask[nHuPanZhenMercenaryTask_24]["StartAutoWay"]["FindWayGenId"] = 2001104

rwtTask[nHuPanZhenMercenaryTask_25] = {}
rwtTask[nHuPanZhenMercenaryTask_25]["Title"] = tLuaText[LANGUAGE_CONFIG][20651]
rwtTask[nHuPanZhenMercenaryTask_25]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_25]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[nHuPanZhenMercenaryTask_25]["TaskQuality"] = 5
rwtTask[nHuPanZhenMercenaryTask_25]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_25]["DialogId"] = 10196
rwtTask[nHuPanZhenMercenaryTask_25]["TaskNpc"] = nNpc_HaiLi
rwtTask[nHuPanZhenMercenaryTask_25]["AwardGroupId"] = 4
rwtTask[nHuPanZhenMercenaryTask_25]["AcceptDialogId"] = 10262
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"] = {}
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"][1] = {}
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"][1]["GenId"] = 2001664
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"][1]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"][2] = {}
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"][2]["GenId"] = 2001665
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"][2]["MapId"] = 2001
--rwtTask[nHuPanZhenMercenaryTask_25]["DynaNpcGroupGen"][2]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_25]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_25]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_25]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[nHuPanZhenMercenaryTask_25]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_25]["StartAutoWay"]["FindWayGroupId"] = 20047
rwtTask[nHuPanZhenMercenaryTask_25]["StartAutoWay"]["FindWayGenId"] = 2001104

rwtTask[nHuPanZhenMercenaryTask_26] = {}
rwtTask[nHuPanZhenMercenaryTask_26]["Title"] = tLuaText[LANGUAGE_CONFIG][20652]
rwtTask[nHuPanZhenMercenaryTask_26]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_26]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_26]["TaskQuality"] = 1
rwtTask[nHuPanZhenMercenaryTask_26]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_26]["KillMonsterGroup1"] = 900205
rwtTask[nHuPanZhenMercenaryTask_26]["KillMonsterGroupCount1"]= 1
rwtTask[nHuPanZhenMercenaryTask_26]["AwardGroupId"] = 5
rwtTask[nHuPanZhenMercenaryTask_26]["AcceptDialogId"] = 10263
rwtTask[nHuPanZhenMercenaryTask_26]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_26]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_26]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_26]["DynaNpcGroupGen"][1]["GenId"] = 2001755
rwtTask[nHuPanZhenMercenaryTask_26]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_26]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_26]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_26]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_26]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_26]["StartAutoWay"]["FindWayGroupId"] = 900205
rwtTask[nHuPanZhenMercenaryTask_26]["StartAutoWay"]["FindWayGenId"] =  2001755

rwtTask[nHuPanZhenMercenaryTask_27] = {}
rwtTask[nHuPanZhenMercenaryTask_27]["Title"] = tLuaText[LANGUAGE_CONFIG][20653]
rwtTask[nHuPanZhenMercenaryTask_27]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_27]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_27]["TaskQuality"] = 2
rwtTask[nHuPanZhenMercenaryTask_27]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_27]["KillMonsterGroup1"] = 900205
rwtTask[nHuPanZhenMercenaryTask_27]["KillMonsterGroupCount1"]= 1
rwtTask[nHuPanZhenMercenaryTask_27]["AwardGroupId"] = 5
rwtTask[nHuPanZhenMercenaryTask_27]["AcceptDialogId"] = 10263
rwtTask[nHuPanZhenMercenaryTask_27]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_27]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_27]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_27]["DynaNpcGroupGen"][1]["GenId"] = 2001755
rwtTask[nHuPanZhenMercenaryTask_27]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_27]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_27]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_27]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_27]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_27]["StartAutoWay"]["FindWayGroupId"] = 900205
rwtTask[nHuPanZhenMercenaryTask_27]["StartAutoWay"]["FindWayGenId"] =  2001755

rwtTask[nHuPanZhenMercenaryTask_28] = {}
rwtTask[nHuPanZhenMercenaryTask_28]["Title"] = tLuaText[LANGUAGE_CONFIG][20654]
rwtTask[nHuPanZhenMercenaryTask_28]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_28]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_28]["TaskQuality"] = 3
rwtTask[nHuPanZhenMercenaryTask_28]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_28]["KillMonsterGroup1"] = 900205
rwtTask[nHuPanZhenMercenaryTask_28]["KillMonsterGroupCount1"]= 1
rwtTask[nHuPanZhenMercenaryTask_28]["AwardGroupId"] = 5
rwtTask[nHuPanZhenMercenaryTask_28]["AcceptDialogId"] = 10263
rwtTask[nHuPanZhenMercenaryTask_28]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_28]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_28]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_28]["DynaNpcGroupGen"][1]["GenId"] = 2001755
rwtTask[nHuPanZhenMercenaryTask_28]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_28]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_28]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_28]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_28]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_28]["StartAutoWay"]["FindWayGroupId"] = 900205
rwtTask[nHuPanZhenMercenaryTask_28]["StartAutoWay"]["FindWayGenId"] =  2001755

rwtTask[nHuPanZhenMercenaryTask_29] = {}
rwtTask[nHuPanZhenMercenaryTask_29]["Title"] = tLuaText[LANGUAGE_CONFIG][20655]
rwtTask[nHuPanZhenMercenaryTask_29]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_29]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_29]["TaskQuality"] = 4
rwtTask[nHuPanZhenMercenaryTask_29]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_29]["KillMonsterGroup1"] = 900205
rwtTask[nHuPanZhenMercenaryTask_29]["KillMonsterGroupCount1"]= 1
rwtTask[nHuPanZhenMercenaryTask_29]["AwardGroupId"] = 5
rwtTask[nHuPanZhenMercenaryTask_29]["AcceptDialogId"] = 10263
rwtTask[nHuPanZhenMercenaryTask_29]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_29]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_29]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_29]["DynaNpcGroupGen"][1]["GenId"] = 2001755
rwtTask[nHuPanZhenMercenaryTask_29]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_29]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_29]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_29]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_29]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_29]["StartAutoWay"]["FindWayGroupId"] = 900205
rwtTask[nHuPanZhenMercenaryTask_29]["StartAutoWay"]["FindWayGenId"] =  2001755

rwtTask[nHuPanZhenMercenaryTask_30] = {}
rwtTask[nHuPanZhenMercenaryTask_30]["Title"] = tLuaText[LANGUAGE_CONFIG][20656]
rwtTask[nHuPanZhenMercenaryTask_30]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_30]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_30]["TaskQuality"] = 5
rwtTask[nHuPanZhenMercenaryTask_30]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_30]["KillMonsterGroup1"] = 900205
rwtTask[nHuPanZhenMercenaryTask_30]["KillMonsterGroupCount1"]= 1
rwtTask[nHuPanZhenMercenaryTask_30]["AwardGroupId"] = 5
rwtTask[nHuPanZhenMercenaryTask_30]["AcceptDialogId"] = 10263
rwtTask[nHuPanZhenMercenaryTask_30]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_30]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_30]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_30]["DynaNpcGroupGen"][1]["GenId"] = 2001755
rwtTask[nHuPanZhenMercenaryTask_30]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_30]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_30]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_30]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_30]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_30]["StartAutoWay"]["FindWayGroupId"] = 900205
rwtTask[nHuPanZhenMercenaryTask_30]["StartAutoWay"]["FindWayGenId"] =  2001755


rwtTask[nHuPanZhenMercenaryTask_31] = {}
rwtTask[nHuPanZhenMercenaryTask_31]["Title"] = tLuaText[LANGUAGE_CONFIG][20657]
rwtTask[nHuPanZhenMercenaryTask_31]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_31]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[nHuPanZhenMercenaryTask_31]["TaskQuality"] = 1
rwtTask[nHuPanZhenMercenaryTask_31]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_31]["ReqCollectId1"] = nCollect_QingHuBei
rwtTask[nHuPanZhenMercenaryTask_31]["ReqCollectCount1"] = 1
rwtTask[nHuPanZhenMercenaryTask_31]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_31]["AcceptDialogId"] = 10264
rwtTask[nHuPanZhenMercenaryTask_31]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_31]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_31]["DynaNpcGroupGen"][1]["GenId"] = 2001126
rwtTask[nHuPanZhenMercenaryTask_31]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_31]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_31]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_31]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_31]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_31]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_31]["StartAutoWay"]["FindWayGroupId"] = 60047
rwtTask[nHuPanZhenMercenaryTask_31]["StartAutoWay"]["FindWayGenId"] =  2001126

rwtTask[nHuPanZhenMercenaryTask_32] = {}
rwtTask[nHuPanZhenMercenaryTask_32]["Title"] = tLuaText[LANGUAGE_CONFIG][20658]
rwtTask[nHuPanZhenMercenaryTask_32]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_32]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[nHuPanZhenMercenaryTask_32]["TaskQuality"] = 2
rwtTask[nHuPanZhenMercenaryTask_32]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_32]["ReqCollectId1"] = nCollect_QingHuBei
rwtTask[nHuPanZhenMercenaryTask_32]["ReqCollectCount1"] = 1
rwtTask[nHuPanZhenMercenaryTask_32]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_32]["AcceptDialogId"] = 10264
rwtTask[nHuPanZhenMercenaryTask_32]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_32]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_32]["DynaNpcGroupGen"][1]["GenId"] = 2001126
rwtTask[nHuPanZhenMercenaryTask_32]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_32]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_32]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_32]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_32]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_32]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_32]["StartAutoWay"]["FindWayGroupId"] = 60047
rwtTask[nHuPanZhenMercenaryTask_32]["StartAutoWay"]["FindWayGenId"] =  2001126

rwtTask[nHuPanZhenMercenaryTask_33] = {}
rwtTask[nHuPanZhenMercenaryTask_33]["Title"] = tLuaText[LANGUAGE_CONFIG][20659]
rwtTask[nHuPanZhenMercenaryTask_33]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_33]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[nHuPanZhenMercenaryTask_33]["TaskQuality"] = 3
rwtTask[nHuPanZhenMercenaryTask_33]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_33]["ReqCollectId1"] = nCollect_QingHuBei
rwtTask[nHuPanZhenMercenaryTask_33]["ReqCollectCount1"] = 1
rwtTask[nHuPanZhenMercenaryTask_33]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_33]["AcceptDialogId"] = 10264
rwtTask[nHuPanZhenMercenaryTask_33]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_33]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_33]["DynaNpcGroupGen"][1]["GenId"] = 2001126
rwtTask[nHuPanZhenMercenaryTask_33]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_33]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_33]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_33]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_33]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_33]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_33]["StartAutoWay"]["FindWayGroupId"] = 60047
rwtTask[nHuPanZhenMercenaryTask_33]["StartAutoWay"]["FindWayGenId"] =  2001126

rwtTask[nHuPanZhenMercenaryTask_34] = {}
rwtTask[nHuPanZhenMercenaryTask_34]["Title"] = tLuaText[LANGUAGE_CONFIG][20660]
rwtTask[nHuPanZhenMercenaryTask_34]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_34]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[nHuPanZhenMercenaryTask_34]["TaskQuality"] = 4
rwtTask[nHuPanZhenMercenaryTask_34]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_34]["ReqCollectId1"] = nCollect_QingHuBei
rwtTask[nHuPanZhenMercenaryTask_34]["ReqCollectCount1"] = 1
rwtTask[nHuPanZhenMercenaryTask_34]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_34]["AcceptDialogId"] = 10264
rwtTask[nHuPanZhenMercenaryTask_34]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_34]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_34]["DynaNpcGroupGen"][1]["GenId"] = 2001126
rwtTask[nHuPanZhenMercenaryTask_34]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_34]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_34]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_34]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_34]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_34]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_34]["StartAutoWay"]["FindWayGroupId"] = 60047
rwtTask[nHuPanZhenMercenaryTask_34]["StartAutoWay"]["FindWayGenId"] =  2001126

rwtTask[nHuPanZhenMercenaryTask_35] = {}
rwtTask[nHuPanZhenMercenaryTask_35]["Title"] = tLuaText[LANGUAGE_CONFIG][20661]
rwtTask[nHuPanZhenMercenaryTask_35]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_35]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[nHuPanZhenMercenaryTask_35]["TaskQuality"] = 5
rwtTask[nHuPanZhenMercenaryTask_35]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_35]["ReqCollectId1"] = nCollect_QingHuBei
rwtTask[nHuPanZhenMercenaryTask_35]["ReqCollectCount1"] = 1
rwtTask[nHuPanZhenMercenaryTask_35]["AwardGroupId"] = 1
rwtTask[nHuPanZhenMercenaryTask_35]["AcceptDialogId"] = 10264
rwtTask[nHuPanZhenMercenaryTask_35]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_35]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_35]["DynaNpcGroupGen"][1]["GenId"] = 2001126
rwtTask[nHuPanZhenMercenaryTask_35]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_35]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_35]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_35]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_35]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_35]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_35]["StartAutoWay"]["FindWayGroupId"] = 60047
rwtTask[nHuPanZhenMercenaryTask_35]["StartAutoWay"]["FindWayGenId"] =  2001126

rwtTask[nHuPanZhenMercenaryTask_36] = {}
rwtTask[nHuPanZhenMercenaryTask_36]["Title"] = tLuaText[LANGUAGE_CONFIG][20662]
rwtTask[nHuPanZhenMercenaryTask_36]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_36]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_36]["TaskQuality"] = 1
rwtTask[nHuPanZhenMercenaryTask_36]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_36]["KillMonsterGroup1"] = nMonsterGroup_PoHuaiZhe
rwtTask[nHuPanZhenMercenaryTask_36]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_36]["AcceptDialogId"] = 10265
rwtTask[nHuPanZhenMercenaryTask_36]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_36]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_36]["DynaNpcGroupGen"][1]["GenId"] = 2001130
rwtTask[nHuPanZhenMercenaryTask_36]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_36]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_36]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_36]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_36]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_36]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_36]["StartAutoWay"]["FindWayGroupId"] = 900147
rwtTask[nHuPanZhenMercenaryTask_36]["StartAutoWay"]["FindWayGenId"] =  2001130

--rwtTask[nHuPanZhenMercenaryTask_36]["DynaNpcGroupRandomGen"] = 2001130
--rwtTask[nHuPanZhenMercenaryTask_36]["DynaNpcGroupRandomGenPos"] = {2001130,2001131,2001132,2001133}

rwtTask[nHuPanZhenMercenaryTask_37] = {}
rwtTask[nHuPanZhenMercenaryTask_37]["Title"] = tLuaText[LANGUAGE_CONFIG][20663]
rwtTask[nHuPanZhenMercenaryTask_37]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_37]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_37]["TaskQuality"] = 2
rwtTask[nHuPanZhenMercenaryTask_37]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_37]["KillMonsterGroup1"] = nMonsterGroup_PoHuaiZhe
rwtTask[nHuPanZhenMercenaryTask_37]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_37]["AcceptDialogId"] = 10265
rwtTask[nHuPanZhenMercenaryTask_37]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_37]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_37]["DynaNpcGroupGen"][1]["GenId"] = 2001130
rwtTask[nHuPanZhenMercenaryTask_37]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_37]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_37]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_37]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_37]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_37]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_37]["StartAutoWay"]["FindWayGroupId"] = 900147
rwtTask[nHuPanZhenMercenaryTask_37]["StartAutoWay"]["FindWayGenId"] =  2001130
--rwtTask[nHuPanZhenMercenaryTask_37]["DynaNpcGroupRandomGen"] = 2001130
--rwtTask[nHuPanZhenMercenaryTask_37]["DynaNpcGroupRandomGenPos"] = {2001130,2001131,2001132,2001133}

rwtTask[nHuPanZhenMercenaryTask_38] = {}
rwtTask[nHuPanZhenMercenaryTask_38]["Title"] = tLuaText[LANGUAGE_CONFIG][20664]
rwtTask[nHuPanZhenMercenaryTask_38]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_38]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_38]["TaskQuality"] = 3
rwtTask[nHuPanZhenMercenaryTask_38]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_38]["KillMonsterGroup1"] = nMonsterGroup_PoHuaiZhe
rwtTask[nHuPanZhenMercenaryTask_38]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_38]["AcceptDialogId"] = 10265
rwtTask[nHuPanZhenMercenaryTask_38]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_38]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_38]["DynaNpcGroupGen"][1]["GenId"] = 2001130
rwtTask[nHuPanZhenMercenaryTask_38]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_38]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_38]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_38]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_38]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_38]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_38]["StartAutoWay"]["FindWayGroupId"] = 900147
rwtTask[nHuPanZhenMercenaryTask_38]["StartAutoWay"]["FindWayGenId"] =  2001130
--rwtTask[nHuPanZhenMercenaryTask_38]["DynaNpcGroupRandomGen"] = 2001130
--rwtTask[nHuPanZhenMercenaryTask_38]["DynaNpcGroupRandomGenPos"] = {2001130,2001131,2001132,2001133}

rwtTask[nHuPanZhenMercenaryTask_39] = {}
rwtTask[nHuPanZhenMercenaryTask_39]["Title"] = tLuaText[LANGUAGE_CONFIG][20665]
rwtTask[nHuPanZhenMercenaryTask_39]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_39]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_39]["TaskQuality"] = 4
rwtTask[nHuPanZhenMercenaryTask_39]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_39]["KillMonsterGroup1"] = nMonsterGroup_PoHuaiZhe
rwtTask[nHuPanZhenMercenaryTask_39]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_39]["AcceptDialogId"] = 10265
rwtTask[nHuPanZhenMercenaryTask_39]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_39]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_39]["DynaNpcGroupGen"][1]["GenId"] = 2001130
rwtTask[nHuPanZhenMercenaryTask_39]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_39]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_39]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_39]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_39]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_39]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_39]["StartAutoWay"]["FindWayGroupId"] = 900147
rwtTask[nHuPanZhenMercenaryTask_39]["StartAutoWay"]["FindWayGenId"] =  2001130
--rwtTask[nHuPanZhenMercenaryTask_39]["DynaNpcGroupRandomGen"] = 2001130
--rwtTask[nHuPanZhenMercenaryTask_39]["DynaNpcGroupRandomGenPos"] = {2001130,2001131,2001132,2001133}

rwtTask[nHuPanZhenMercenaryTask_40] = {}
rwtTask[nHuPanZhenMercenaryTask_40]["Title"] = tLuaText[LANGUAGE_CONFIG][20666]
rwtTask[nHuPanZhenMercenaryTask_40]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_40]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_40]["TaskQuality"] = 5
rwtTask[nHuPanZhenMercenaryTask_40]["MercenaryTownId"] = 200101
rwtTask[nHuPanZhenMercenaryTask_40]["KillMonsterGroup1"] = nMonsterGroup_PoHuaiZhe
rwtTask[nHuPanZhenMercenaryTask_40]["AwardGroupId"] = 2
rwtTask[nHuPanZhenMercenaryTask_40]["AcceptDialogId"] = 10265
rwtTask[nHuPanZhenMercenaryTask_40]["DynaNpcGroupGen"] = {}
rwtTask[nHuPanZhenMercenaryTask_40]["DynaNpcGroupGen"][1] = {}
rwtTask[nHuPanZhenMercenaryTask_40]["DynaNpcGroupGen"][1]["GenId"] = 2001130
rwtTask[nHuPanZhenMercenaryTask_40]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_40]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[nHuPanZhenMercenaryTask_40]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_40]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_40]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[nHuPanZhenMercenaryTask_40]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_40]["StartAutoWay"]["FindWayGroupId"] = 900147
rwtTask[nHuPanZhenMercenaryTask_40]["StartAutoWay"]["FindWayGenId"] =  2001130
--rwtTask[nHuPanZhenMercenaryTask_40]["DynaNpcGroupRandomGen"] = 2001130
--rwtTask[nHuPanZhenMercenaryTask_40]["DynaNpcGroupRandomGenPos"] = {2001130,2001131,2001132,2001133}

rwtTask[nHuPanZhenMercenaryTask_41] = {}
rwtTask[nHuPanZhenMercenaryTask_41]["Title"] = tLuaText[LANGUAGE_CONFIG][20667]
rwtTask[nHuPanZhenMercenaryTask_41]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_41]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_41]["TaskQuality"] = 1
rwtTask[nHuPanZhenMercenaryTask_41]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_41]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK
rwtTask[nHuPanZhenMercenaryTask_41]["TaskNpc"] = nNpc_XiEr
rwtTask[nHuPanZhenMercenaryTask_41]["DialogId"] = 10198
rwtTask[nHuPanZhenMercenaryTask_41]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_41]["AcceptDialogId"] = 10266
rwtTask[nHuPanZhenMercenaryTask_41]["MonsterGroupGenId"] = 2001136
rwtTask[nHuPanZhenMercenaryTask_41]["KillMonsterGroup1" ] = 900148
rwtTask[nHuPanZhenMercenaryTask_41]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_41]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_41]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_41]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_41]["StartAutoWay"]["FindWayGroupId"] = 20079
rwtTask[nHuPanZhenMercenaryTask_41]["StartAutoWay"]["FindWayGenId"] =  2001125

rwtTask[nHuPanZhenMercenaryTask_42] = {}
rwtTask[nHuPanZhenMercenaryTask_42]["Title"] = tLuaText[LANGUAGE_CONFIG][20668]
rwtTask[nHuPanZhenMercenaryTask_42]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_42]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_42]["TaskQuality"] = 2
rwtTask[nHuPanZhenMercenaryTask_42]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_42]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK
rwtTask[nHuPanZhenMercenaryTask_42]["TaskNpc"] = nNpc_XiEr
rwtTask[nHuPanZhenMercenaryTask_42]["DialogId"] = 10198
rwtTask[nHuPanZhenMercenaryTask_42]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_42]["AcceptDialogId"] = 10266
rwtTask[nHuPanZhenMercenaryTask_42]["MonsterGroupGenId"] = 2001136
rwtTask[nHuPanZhenMercenaryTask_42]["KillMonsterGroup1" ] = 900148
rwtTask[nHuPanZhenMercenaryTask_42]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_42]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_42]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_42]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_42]["StartAutoWay"]["FindWayGroupId"] = 20079
rwtTask[nHuPanZhenMercenaryTask_42]["StartAutoWay"]["FindWayGenId"] =  2001125


rwtTask[nHuPanZhenMercenaryTask_43] = {}
rwtTask[nHuPanZhenMercenaryTask_43]["Title"] = tLuaText[LANGUAGE_CONFIG][20669]
rwtTask[nHuPanZhenMercenaryTask_43]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_43]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_43]["TaskQuality"] = 3
rwtTask[nHuPanZhenMercenaryTask_43]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_43]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK
rwtTask[nHuPanZhenMercenaryTask_43]["TaskNpc"] = nNpc_XiEr
rwtTask[nHuPanZhenMercenaryTask_43]["DialogId"] = 10198
rwtTask[nHuPanZhenMercenaryTask_43]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_43]["AcceptDialogId"] = 10266
rwtTask[nHuPanZhenMercenaryTask_43]["MonsterGroupGenId"] = 2001136
rwtTask[nHuPanZhenMercenaryTask_43]["KillMonsterGroup1" ] = 900148
rwtTask[nHuPanZhenMercenaryTask_43]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_43]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_43]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_43]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_43]["StartAutoWay"]["FindWayGroupId"] = 20079
rwtTask[nHuPanZhenMercenaryTask_43]["StartAutoWay"]["FindWayGenId"] =  2001125

rwtTask[nHuPanZhenMercenaryTask_44] = {}
rwtTask[nHuPanZhenMercenaryTask_44]["Title"] = tLuaText[LANGUAGE_CONFIG][20670]
rwtTask[nHuPanZhenMercenaryTask_44]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_44]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_44]["TaskQuality"] = 4
rwtTask[nHuPanZhenMercenaryTask_44]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_44]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK
rwtTask[nHuPanZhenMercenaryTask_44]["TaskNpc"] = nNpc_XiEr
rwtTask[nHuPanZhenMercenaryTask_44]["DialogId"] = 10198
rwtTask[nHuPanZhenMercenaryTask_44]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_44]["AcceptDialogId"] = 10266
rwtTask[nHuPanZhenMercenaryTask_44]["MonsterGroupGenId"] = 2001136
rwtTask[nHuPanZhenMercenaryTask_44]["KillMonsterGroup1" ] = 900148
rwtTask[nHuPanZhenMercenaryTask_44]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_44]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_44]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_44]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_44]["StartAutoWay"]["FindWayGroupId"] = 20079
rwtTask[nHuPanZhenMercenaryTask_44]["StartAutoWay"]["FindWayGenId"] =  2001125

rwtTask[nHuPanZhenMercenaryTask_45] = {}
rwtTask[nHuPanZhenMercenaryTask_45]["Title"] = tLuaText[LANGUAGE_CONFIG][20671]
rwtTask[nHuPanZhenMercenaryTask_45]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[nHuPanZhenMercenaryTask_45]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[nHuPanZhenMercenaryTask_45]["TaskQuality"] = 5
rwtTask[nHuPanZhenMercenaryTask_45]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_45]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK
rwtTask[nHuPanZhenMercenaryTask_45]["TaskNpc"] = nNpc_XiEr
rwtTask[nHuPanZhenMercenaryTask_45]["DialogId"] = 10198
rwtTask[nHuPanZhenMercenaryTask_45]["AwardGroupId"] = 3
rwtTask[nHuPanZhenMercenaryTask_45]["AcceptDialogId"] = 10266
rwtTask[nHuPanZhenMercenaryTask_45]["MonsterGroupGenId"] = 2001136
rwtTask[nHuPanZhenMercenaryTask_45]["KillMonsterGroup1" ] = 900148
rwtTask[nHuPanZhenMercenaryTask_45]["IsClickComplete"] = 0
rwtTask[nHuPanZhenMercenaryTask_45]["StartAutoWay"] = {}
rwtTask[nHuPanZhenMercenaryTask_45]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[nHuPanZhenMercenaryTask_45]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[nHuPanZhenMercenaryTask_45]["StartAutoWay"]["FindWayGroupId"] = 20079
rwtTask[nHuPanZhenMercenaryTask_45]["StartAutoWay"]["FindWayGenId"] =  2001125

--rwtTask[nHuPanZhenMercenaryTask_46] = {}
--rwtTask[nHuPanZhenMercenaryTask_46]["Title"] = tLuaText[LANGUAGE_CONFIG][20672]
--rwtTask[nHuPanZhenMercenaryTask_46]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_46]["TaskQuality"] = 1
--rwtTask[nHuPanZhenMercenaryTask_46]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_46]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_46]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_46]["AwardGroupId"] = 4
--rwtTask[nHuPanZhenMercenaryTask_46]["AcceptDialogId"] = 10267

--rwtTask[nHuPanZhenMercenaryTask_47] = {}
--rwtTask[nHuPanZhenMercenaryTask_47]["Title"] = tLuaText[LANGUAGE_CONFIG][20673]
--rwtTask[nHuPanZhenMercenaryTask_47]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_47]["TaskQuality"] = 2
--rwtTask[nHuPanZhenMercenaryTask_47]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_47]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_47]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_47]["AwardGroupId"] = 4
--rwtTask[nHuPanZhenMercenaryTask_47]["AcceptDialogId"] = 10267

--rwtTask[nHuPanZhenMercenaryTask_48] = {}
--rwtTask[nHuPanZhenMercenaryTask_48]["Title"] = tLuaText[LANGUAGE_CONFIG][20674]
--rwtTask[nHuPanZhenMercenaryTask_48]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_48]["TaskQuality"] = 3
--rwtTask[nHuPanZhenMercenaryTask_48]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_48]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_48]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_48]["AwardGroupId"] = 4
--rwtTask[nHuPanZhenMercenaryTask_48]["AcceptDialogId"] = 10267

--rwtTask[nHuPanZhenMercenaryTask_49] = {}
--rwtTask[nHuPanZhenMercenaryTask_49]["Title"] = tLuaText[LANGUAGE_CONFIG][20675]
--rwtTask[nHuPanZhenMercenaryTask_49]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_49]["TaskQuality"] = 4
--rwtTask[nHuPanZhenMercenaryTask_49]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_49]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_49]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_49]["AwardGroupId"] = 4
--rwtTask[nHuPanZhenMercenaryTask_49]["AcceptDialogId"] = 10267

--rwtTask[nHuPanZhenMercenaryTask_50] = {}
--rwtTask[nHuPanZhenMercenaryTask_50]["Title"] = tLuaText[LANGUAGE_CONFIG][20676]
--rwtTask[nHuPanZhenMercenaryTask_50]["TaskType"] = CONST_TASK_TYPE.MERCENARY
--rwtTask[nHuPanZhenMercenaryTask_50]["TaskQuality"] = 5
--rwtTask[nHuPanZhenMercenaryTask_50]["MercenaryTownId"] = 200101
--rwtTask[nHuPanZhenMercenaryTask_50]["DialogId"] = 1
--rwtTask[nHuPanZhenMercenaryTask_50]["ReqTrap1"] = 1
--rwtTask[nHuPanZhenMercenaryTask_50]["AwardGroupId"] = 4
--rwtTask[nHuPanZhenMercenaryTask_50]["AcceptDialogId"] = 10267

---------------------------------击退兽潮--------------------------------------------------
rwtTask[tHuPanZhenMercenaryTask.NewAdd1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["Title"] = tLuaText[LANGUAGE_CONFIG][21157]--"击退兽潮"
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["TaskQuality"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["AcceptDialogId"] = nAcceptDialog_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["MonsterGroupGenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["AwardGroupId"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd2] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["Title"] = tLuaText[LANGUAGE_CONFIG][21158]--"击退兽潮"
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["TaskQuality"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["AcceptDialogId"] = nAcceptDialog_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["MonsterGroupGenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["AwardGroupId"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd3] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["Title"] = tLuaText[LANGUAGE_CONFIG][21159]--"击退兽潮"
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["TaskQuality"] = 3
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["AcceptDialogId"] = nAcceptDialog_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["MonsterGroupGenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["AwardGroupId"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd4] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["Title"] = tLuaText[LANGUAGE_CONFIG][21160]--"击退兽潮"
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["TaskQuality"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["AcceptDialogId"] = nAcceptDialog_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["MonsterGroupGenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["AwardGroupId"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd5] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["Title"] = tLuaText[LANGUAGE_CONFIG][21161]--"击退兽潮"
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["TaskQuality"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["AcceptDialogId"] = nAcceptDialog_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["MonsterGroupGenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["AwardGroupId"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd1
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd1_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete


-------------------------------碎魂狼王的复仇-----------------------------------------
rwtTask[tHuPanZhenMercenaryTask.NewAdd6] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["Title"] = tLuaText[LANGUAGE_CONFIG][21162]--"碎魂狼王的复仇"
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["TaskQuality"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["AcceptDialogId"] = nAcceptDialog_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["MonsterGroupGenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["AwardGroupId"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd6]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd7] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["Title"] = tLuaText[LANGUAGE_CONFIG][21163]--"碎魂狼王的复仇"
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["TaskQuality"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["AcceptDialogId"] = nAcceptDialog_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["MonsterGroupGenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["AwardGroupId"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd7]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd8] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["Title"] = tLuaText[LANGUAGE_CONFIG][21164]--"碎魂狼王的复仇"
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["TaskQuality"] = 3
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["AcceptDialogId"] = nAcceptDialog_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["MonsterGroupGenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["AwardGroupId"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd8]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd9] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["Title"] = tLuaText[LANGUAGE_CONFIG][21165]--"碎魂狼王的复仇"
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["TaskQuality"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["AcceptDialogId"] = nAcceptDialog_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["MonsterGroupGenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["AwardGroupId"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd9]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd10] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["Title"] = tLuaText[LANGUAGE_CONFIG][21166]--"碎魂狼王的复仇"
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["TaskQuality"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["AcceptDialogId"] = nAcceptDialog_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["MonsterGroupGenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd2
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["AwardGroupId"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd2_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd10]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete




---------------------------------神秘怪物的来历------------------------------
rwtTask[tHuPanZhenMercenaryTask.NewAdd11] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["Title"] = tLuaText[LANGUAGE_CONFIG][21167]--"神秘怪物的来历"
--rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["PuzzleTitle"] = tLuaText[LANGUAGE_CONFIG][40015]
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.PUZZLE
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["TaskQuality"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["AcceptDialogId"] = nAcceptDialog_NewAdd3
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["ReqPuzzleId"] = 101
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["ReqPuzzleObj"] = 101002
--rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["ReqPuzzleEnterDialog"] = 12019
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["IsClickComplete"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["AwardGroupId"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["StartAutoWay"]["FindWayTypeId"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd11]["StartAutoWay"]["FindWayPos"] = sPos_ChuWuShi


rwtTask[tHuPanZhenMercenaryTask.NewAdd12] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["Title"] = tLuaText[LANGUAGE_CONFIG][21168]--"神秘怪物的来历"
--rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["PuzzleTitle"] = tLuaText[LANGUAGE_CONFIG][40015]
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.PUZZLE
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["TaskQuality"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["AcceptDialogId"] = nAcceptDialog_NewAdd3
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["ReqPuzzleId"] = 101
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["ReqPuzzleObj"] = 101002
--rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["ReqPuzzleEnterDialog"] = 12019
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["IsClickComplete"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["AwardGroupId"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["StartAutoWay"]["FindWayTypeId"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd12]["StartAutoWay"]["FindWayPos"] = sPos_ChuWuShi


rwtTask[tHuPanZhenMercenaryTask.NewAdd13] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["Title"] = tLuaText[LANGUAGE_CONFIG][21169]--"神秘怪物的来历"
--rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["PuzzleTitle"] = tLuaText[LANGUAGE_CONFIG][40015]
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.PUZZLE
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["TaskQuality"] = 3
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["AcceptDialogId"] = nAcceptDialog_NewAdd3
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["ReqPuzzleId"] = 101
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["ReqPuzzleObj"] = 101002
--rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["ReqPuzzleEnterDialog"] = 12019
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["IsClickComplete"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["AwardGroupId"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["StartAutoWay"]["FindWayTypeId"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd13]["StartAutoWay"]["FindWayPos"] = sPos_ChuWuShi


rwtTask[tHuPanZhenMercenaryTask.NewAdd14] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["Title"] = tLuaText[LANGUAGE_CONFIG][21170]--"神秘怪物的来历"
--rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["PuzzleTitle"] = tLuaText[LANGUAGE_CONFIG][40015]
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.PUZZLE
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["TaskQuality"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["AcceptDialogId"] = nAcceptDialog_NewAdd3
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["ReqPuzzleId"] = 101
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["ReqPuzzleObj"] = 101002
--rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["ReqPuzzleEnterDialog"] = 12019
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["IsClickComplete"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["AwardGroupId"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["StartAutoWay"]["FindWayTypeId"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd14]["StartAutoWay"]["FindWayPos"] = sPos_ChuWuShi


rwtTask[tHuPanZhenMercenaryTask.NewAdd15] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["Title"] = tLuaText[LANGUAGE_CONFIG][21171]--"神秘怪物的来历"
--rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["PuzzleTitle"] = tLuaText[LANGUAGE_CONFIG][40015]
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.PUZZLE
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["TaskQuality"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["AcceptDialogId"] = nAcceptDialog_NewAdd3
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["ReqPuzzleId"] = 101
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["ReqPuzzleObj"] = 101002
--rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["ReqPuzzleEnterDialog"] = 12019
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["IsClickComplete"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["AwardGroupId"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["StartAutoWay"]["FindWayTypeId"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd15]["StartAutoWay"]["FindWayPos"] = sPos_ChuWuShi



-----------------------联盟通缉令------------------------------
rwtTask[tHuPanZhenMercenaryTask.NewAdd16] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["Title"] = tLuaText[LANGUAGE_CONFIG][21172]--"联盟通缉令"
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["TaskQuality"] = 1
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["AcceptDialogId"] = nAcceptDialog_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["MonsterGroupGenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["AwardGroupId"] = 6
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd16]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd17] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["Title"] = tLuaText[LANGUAGE_CONFIG][21173]--"联盟通缉令"
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["TaskQuality"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["AcceptDialogId"] = nAcceptDialog_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["MonsterGroupGenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["AwardGroupId"] = 6
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd17]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd18] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["Title"] = tLuaText[LANGUAGE_CONFIG][21174]--"联盟通缉令"
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["TaskQuality"] = 3
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["AcceptDialogId"] = nAcceptDialog_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["MonsterGroupGenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["AwardGroupId"] = 6
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd18]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd19] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["Title"] = tLuaText[LANGUAGE_CONFIG][21175]--"联盟通缉令"
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["TaskQuality"] = 4
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["AcceptDialogId"] = nAcceptDialog_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["MonsterGroupGenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["AwardGroupId"] = 6
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd19]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete

rwtTask[tHuPanZhenMercenaryTask.NewAdd20] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["Title"] = tLuaText[LANGUAGE_CONFIG][21176]--"联盟通缉令"
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["MercenaryTownId"] = 200101
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["TaskQuality"] = 5
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["AcceptDialogId"] = nAcceptDialog_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["MonsterGroupGenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["KillMonsterGroup1" ] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["IsClickComplete"] = 0
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["StartAutoWay"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["StartAutoWay"]["FindWayMapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_NewAdd4
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["AwardGroupId"] = 6
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["DynaNpcGroupGen"] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["DynaNpcGroupGen"][1] = {}
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_NewAdd4_GenId
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tHuPanZhenMercenaryTask.NewAdd20]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
