
--地图ID
local nMapId = 2004

--镇子ID
local nTownId = 200502

--任务ID
local tTianKong = {}
tTianKong.task1 =  20722	--纳雅密函
tTianKong.task2 =  20723	--纳雅密函
tTianKong.task3 =  20724	--纳雅密函
tTianKong.task4 =  20725	--纳雅密函
tTianKong.task5 =  20726	--纳雅密函
tTianKong.task6 =  20727	--尤菲的梦想
tTianKong.task7 =  20728	--尤菲的梦想
tTianKong.task8 =  20729	--尤菲的梦想
tTianKong.task9 =  20730	--尤菲的梦想
tTianKong.task10 = 20731	--尤菲的梦想
tTianKong.task11 = 20732	--天神的传说
tTianKong.task12 = 20733	--天神的传说
tTianKong.task13 = 20734	--天神的传说
tTianKong.task14 = 20735	--天神的传说
tTianKong.task15 = 20736	--天神的传说
tTianKong.task16 = 20737	--新物种研究
tTianKong.task17 = 20738	--新物种研究
tTianKong.task18 = 20739	--新物种研究
tTianKong.task19 = 20740	--新物种研究
tTianKong.task20 = 20741	--新物种研究
tTianKong.task21 = 20742	--采集圣水
tTianKong.task22 = 20743	--采集圣水
tTianKong.task23 = 20744	--采集圣水
tTianKong.task24 = 20745	--采集圣水
tTianKong.task25 = 20746	--采集圣水
tTianKong.task26 = 20747	--定期养护
tTianKong.task27 = 20748	--定期养护
tTianKong.task28 = 20749	--定期养护
tTianKong.task29 = 20750	--定期养护
tTianKong.task30 = 20751	--定期养护
tTianKong.task31 = 20752	--纳雅科技箱
tTianKong.task32 = 20753	--纳雅科技箱
tTianKong.task33 = 20754	--纳雅科技箱
tTianKong.task34 = 20755	--纳雅科技箱
tTianKong.task35 = 20756	--纳雅科技箱
tTianKong.task36 = 20757	--危险实验体
tTianKong.task37 = 20758	--危险实验体
tTianKong.task38 = 20759	--危险实验体
tTianKong.task39 = 20760	--危险实验体
tTianKong.task40 = 20761	--危险实验体
tTianKong.task41 = 20762	--天空城潜伏者
tTianKong.task42 = 20763	--天空城潜伏者
tTianKong.task43 = 20764	--天空城潜伏者
tTianKong.task44 = 20765	--天空城潜伏者
tTianKong.task45 = 20766	--天空城潜伏者
tTianKong.task46 = 20767	--实力的考验
tTianKong.task47 = 20768	--实力的考验
tTianKong.task48 = 20769	--实力的考验
tTianKong.task49 = 20770	--实力的考验
tTianKong.task50 = 20771	--实力的考验


--对话ID
local tDialog = {}
tDialog.nTask1_1  =	11999	--纳雅密函
tDialog.nTask1_2  =	12000	--纳雅密函
tDialog.nTask2_1  =	12001	--尤菲的梦想
tDialog.nTask2_2  =	12002	--尤菲的梦想
tDialog.nTask3_1  =	12003	--天神的传说
tDialog.nTask3_2  =	12004	--天神的传说
tDialog.nTask4_1  =	12005	--新物种研究
tDialog.nTask4_2  =	12006	--新物种研究
tDialog.nTask5_1  =	12007	--采集圣水
tDialog.nTask5_2  =	12008	--采集圣水
tDialog.nTask6_1  =	12009	--定期养护
tDialog.nTask6_2  =	12010	--定期养护
tDialog.nTask7_1  =	12011	--纳雅科技箱
tDialog.nTask7_2  =	12012	--纳雅科技箱
tDialog.nTask8_1  =	12013	--危险实验体
tDialog.nTask8_2  =	12014	--危险实验体
tDialog.nTask9_1  =	12015	--天空城潜伏者
tDialog.nTask9_2  =	12016	--天空城潜伏者
tDialog.nTask10_1 =	12017	--实力的考验
tDialog.nTask10_2 =	12018	--实力的考验



--陷阱ID
local tTrap = {}

--采集物ID
local tCollect= {}

tCollect.nCollect_Shengshui = 60317
tCollect.nCollect_GenId_Shengshui = 20040055
rwtNpcGroup[tCollect.nCollect_Shengshui] = rwtNpcGroup[tCollect.nCollect_Shengshui] or {} 
rwtNpcGroup[tCollect.nCollect_Shengshui]["Type"] = CONST_NPCGROUP_TYPE.Collect

tCollect.nCollect_Robot = 60318
tCollect.nCollect_GenId_Robot = 20040056
rwtNpcGroup[tCollect.nCollect_Robot] = rwtNpcGroup[tCollect.nCollect_Robot] or {} 
rwtNpcGroup[tCollect.nCollect_Robot]["Type"] = CONST_NPCGROUP_TYPE.Collect

tCollect.nCollect_Box = 60319
tCollect.nCollect_GenId_Box = 20040057
rwtNpcGroup[tCollect.nCollect_Box] = rwtNpcGroup[tCollect.nCollect_Box] or {} 
rwtNpcGroup[tCollect.nCollect_Box]["Type"] = CONST_NPCGROUP_TYPE.Collect

--宝箱ID
local tTreasureBox= {}

--怪物ID
local tMonster = {}

tMonster.nMonster_ShiYanTi = 9000399
tMonster.nMonsterGroup_ShiYanTi = 900434
tMonster.nMonsterGroup_GenId_ShiYanTi = 20040058

tMonster.nMonster_QianFuZhe = 9000400
tMonster.nMonsterGroup_QianFuZhe = 900435
tMonster.nMonsterGroup_GenId_QianFuZhe = 20040059

tMonster.nMonster_WeiDuiZhang = 9000401
tMonster.nMonsterGroup_WeiDuiZhang = 900436
tMonster.nMonsterGroup_GenId_WeiDuiZhang = 20040060

--NPCID
local tSingleNpc = {}

tSingleNpc.nNpc_TaLeiYa = 3398
tSingleNpc.nNpcGroup_TaLeiYa = 20420
tSingleNpc.nNpcGroup_GenId_TaLeiYa = 20040002


tSingleNpc.nNpc_YouFei = 3401
tSingleNpc.nNpcGroup_YouFei = 20423
tSingleNpc.nNpcGroup_GenId_YouFei = 20040005


tSingleNpc.nNpc_TianShenSHouWei = 3457
tSingleNpc.nNpcGroup_TianShenSHouWei = 70015
tSingleNpc.nNpcGroup_GenId_TianShenSHouWei = 20050135


tSingleNpc.nNpc_MaLuXi = 3399
tSingleNpc.nNpcGroup_MaLuXi = 20421
tSingleNpc.nNpcGroup_GenId_MaLuXi = 20040003


-------------------------------------纳雅密函----------------------------------------------

rwtTask[tTianKong.task1] = {}
rwtTask[tTianKong.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21493]
rwtTask[tTianKong.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task1]["TaskQuality"] = 1
rwtTask[tTianKong.task1]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task1]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task1]["AwardGroupId"] = 1
rwtTask[tTianKong.task1]["TaskNpc"] = tSingleNpc.nNpc_TaLeiYa
rwtTask[tTianKong.task1]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tTianKong.task1]["DialogId"] = tDialog.nTask1_2
rwtTask[tTianKong.task1]["StartAutoWay"] = {}
rwtTask[tTianKong.task1]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task1]["StartAutoWay"]["FindWayMapId"] = 2006
rwtTask[tTianKong.task1]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TaLeiYa
rwtTask[tTianKong.task1]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TaLeiYa


rwtTask[tTianKong.task2] = {}
rwtTask[tTianKong.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21493]
rwtTask[tTianKong.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task2]["TaskQuality"] = 2
rwtTask[tTianKong.task2]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task2]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task2]["AwardGroupId"] = 1
rwtTask[tTianKong.task2]["TaskNpc"] = tSingleNpc.nNpc_TaLeiYa
rwtTask[tTianKong.task2]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tTianKong.task2]["DialogId"] = tDialog.nTask1_2
rwtTask[tTianKong.task2]["StartAutoWay"] = {}
rwtTask[tTianKong.task2]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task2]["StartAutoWay"]["FindWayMapId"] = 2006
rwtTask[tTianKong.task2]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TaLeiYa
rwtTask[tTianKong.task2]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TaLeiYa


rwtTask[tTianKong.task3] = {}
rwtTask[tTianKong.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21493]
rwtTask[tTianKong.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task3]["TaskQuality"] = 3
rwtTask[tTianKong.task3]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task3]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task3]["AwardGroupId"] = 1
rwtTask[tTianKong.task3]["TaskNpc"] = tSingleNpc.nNpc_TaLeiYa
rwtTask[tTianKong.task3]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tTianKong.task3]["DialogId"] = tDialog.nTask1_2
rwtTask[tTianKong.task3]["StartAutoWay"] = {}
rwtTask[tTianKong.task3]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task3]["StartAutoWay"]["FindWayMapId"] = 2006
rwtTask[tTianKong.task3]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TaLeiYa
rwtTask[tTianKong.task3]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TaLeiYa


rwtTask[tTianKong.task4] = {}
rwtTask[tTianKong.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21493]
rwtTask[tTianKong.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task4]["TaskQuality"] = 4
rwtTask[tTianKong.task4]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task4]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task4]["AwardGroupId"] = 1
rwtTask[tTianKong.task4]["TaskNpc"] = tSingleNpc.nNpc_TaLeiYa
rwtTask[tTianKong.task4]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tTianKong.task4]["DialogId"] = tDialog.nTask1_2
rwtTask[tTianKong.task4]["StartAutoWay"] = {}
rwtTask[tTianKong.task4]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task4]["StartAutoWay"]["FindWayMapId"] = 2006
rwtTask[tTianKong.task4]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TaLeiYa
rwtTask[tTianKong.task4]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TaLeiYa


rwtTask[tTianKong.task5] = {}
rwtTask[tTianKong.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21493]
rwtTask[tTianKong.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task5]["TaskQuality"] = 5
rwtTask[tTianKong.task5]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task5]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task5]["AwardGroupId"] = 1
rwtTask[tTianKong.task5]["TaskNpc"] = tSingleNpc.nNpc_TaLeiYa
rwtTask[tTianKong.task5]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tTianKong.task5]["DialogId"] = tDialog.nTask1_2
rwtTask[tTianKong.task5]["StartAutoWay"] = {}
rwtTask[tTianKong.task5]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task5]["StartAutoWay"]["FindWayMapId"] = 2006
rwtTask[tTianKong.task5]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TaLeiYa
rwtTask[tTianKong.task5]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TaLeiYa

----------------------------------尤菲的梦想-----------------------------------------------------

rwtTask[tTianKong.task6] = {}
rwtTask[tTianKong.task6]["Title"] = tLuaText[LANGUAGE_CONFIG][21494]
rwtTask[tTianKong.task6]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task6]["TaskQuality"] = 1
rwtTask[tTianKong.task6]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task6]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task6]["AwardGroupId"] = 2
rwtTask[tTianKong.task6]["TaskNpc"] = tSingleNpc.nNpc_YouFei
rwtTask[tTianKong.task6]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tTianKong.task6]["DialogId"] = tDialog.nTask2_2
rwtTask[tTianKong.task6]["StartAutoWay"] = {}
rwtTask[tTianKong.task6]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task6]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task6]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_YouFei
rwtTask[tTianKong.task6]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_YouFei

rwtTask[tTianKong.task7] = {}
rwtTask[tTianKong.task7]["Title"] = tLuaText[LANGUAGE_CONFIG][21494]
rwtTask[tTianKong.task7]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task7]["TaskQuality"] = 2
rwtTask[tTianKong.task7]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task7]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task7]["AwardGroupId"] = 2
rwtTask[tTianKong.task7]["TaskNpc"] = tSingleNpc.nNpc_YouFei
rwtTask[tTianKong.task7]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tTianKong.task7]["DialogId"] = tDialog.nTask2_2
rwtTask[tTianKong.task7]["StartAutoWay"] = {}
rwtTask[tTianKong.task7]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task7]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task7]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_YouFei
rwtTask[tTianKong.task7]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_YouFei

rwtTask[tTianKong.task8] = {}
rwtTask[tTianKong.task8]["Title"] = tLuaText[LANGUAGE_CONFIG][21494]
rwtTask[tTianKong.task8]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task8]["TaskQuality"] = 3
rwtTask[tTianKong.task8]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task8]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task8]["AwardGroupId"] = 2
rwtTask[tTianKong.task8]["TaskNpc"] = tSingleNpc.nNpc_YouFei
rwtTask[tTianKong.task8]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tTianKong.task8]["DialogId"] = tDialog.nTask2_2
rwtTask[tTianKong.task8]["StartAutoWay"] = {}
rwtTask[tTianKong.task8]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task8]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task8]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_YouFei
rwtTask[tTianKong.task8]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_YouFei

rwtTask[tTianKong.task9] = {}
rwtTask[tTianKong.task9]["Title"] = tLuaText[LANGUAGE_CONFIG][21494]
rwtTask[tTianKong.task9]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task9]["TaskQuality"] = 4
rwtTask[tTianKong.task9]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task9]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task9]["AwardGroupId"] = 2
rwtTask[tTianKong.task9]["TaskNpc"] = tSingleNpc.nNpc_YouFei
rwtTask[tTianKong.task9]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tTianKong.task9]["DialogId"] = tDialog.nTask2_2
rwtTask[tTianKong.task9]["StartAutoWay"] = {}
rwtTask[tTianKong.task9]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task9]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task9]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_YouFei
rwtTask[tTianKong.task9]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_YouFei

rwtTask[tTianKong.task10] = {}
rwtTask[tTianKong.task10]["Title"] = tLuaText[LANGUAGE_CONFIG][21494]
rwtTask[tTianKong.task10]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task10]["TaskQuality"] = 5
rwtTask[tTianKong.task10]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task10]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task10]["AwardGroupId"] = 2
rwtTask[tTianKong.task10]["TaskNpc"] = tSingleNpc.nNpc_YouFei
rwtTask[tTianKong.task10]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tTianKong.task10]["DialogId"] = tDialog.nTask2_2
rwtTask[tTianKong.task10]["StartAutoWay"] = {}
rwtTask[tTianKong.task10]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task10]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task10]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_YouFei
rwtTask[tTianKong.task10]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_YouFei

--------------------------------天神的传说--------------------------------------------------
rwtTask[tTianKong.task11] = {}
rwtTask[tTianKong.task11]["Title"] = tLuaText[LANGUAGE_CONFIG][21495]
rwtTask[tTianKong.task11]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task11]["TaskQuality"] = 1
rwtTask[tTianKong.task11]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task11]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task11]["AwardGroupId"] = 3
rwtTask[tTianKong.task11]["TaskNpc"] = tSingleNpc.nNpc_TianShenSHouWei
rwtTask[tTianKong.task11]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tTianKong.task11]["DialogId"] = tDialog.nTask3_2
rwtTask[tTianKong.task11]["StartAutoWay"] = {}
rwtTask[tTianKong.task11]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task11]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task11]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TianShenSHouWei
rwtTask[tTianKong.task11]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TianShenSHouWei


rwtTask[tTianKong.task12] = {}
rwtTask[tTianKong.task12]["Title"] = tLuaText[LANGUAGE_CONFIG][21495]
rwtTask[tTianKong.task12]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task12]["TaskQuality"] = 2
rwtTask[tTianKong.task12]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task12]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task12]["AwardGroupId"] = 3
rwtTask[tTianKong.task12]["TaskNpc"] = tSingleNpc.nNpc_TianShenSHouWei
rwtTask[tTianKong.task12]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tTianKong.task12]["DialogId"] = tDialog.nTask3_2
rwtTask[tTianKong.task12]["StartAutoWay"] = {}
rwtTask[tTianKong.task12]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task12]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task12]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TianShenSHouWei
rwtTask[tTianKong.task12]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TianShenSHouWei

rwtTask[tTianKong.task13] = {}
rwtTask[tTianKong.task13]["Title"] = tLuaText[LANGUAGE_CONFIG][21495]
rwtTask[tTianKong.task13]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task13]["TaskQuality"] = 3
rwtTask[tTianKong.task13]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task13]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task13]["AwardGroupId"] = 3
rwtTask[tTianKong.task13]["TaskNpc"] = tSingleNpc.nNpc_TianShenSHouWei
rwtTask[tTianKong.task13]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tTianKong.task13]["DialogId"] = tDialog.nTask3_2
rwtTask[tTianKong.task13]["StartAutoWay"] = {}
rwtTask[tTianKong.task13]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task13]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task13]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TianShenSHouWei
rwtTask[tTianKong.task13]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TianShenSHouWei

rwtTask[tTianKong.task14] = {}
rwtTask[tTianKong.task14]["Title"] = tLuaText[LANGUAGE_CONFIG][21495]
rwtTask[tTianKong.task14]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task14]["TaskQuality"] = 4
rwtTask[tTianKong.task14]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task14]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task14]["AwardGroupId"] = 3
rwtTask[tTianKong.task14]["TaskNpc"] = tSingleNpc.nNpc_TianShenSHouWei
rwtTask[tTianKong.task14]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tTianKong.task14]["DialogId"] = tDialog.nTask3_2
rwtTask[tTianKong.task14]["StartAutoWay"] = {}
rwtTask[tTianKong.task14]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task14]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task14]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TianShenSHouWei
rwtTask[tTianKong.task14]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TianShenSHouWei

rwtTask[tTianKong.task15] = {}
rwtTask[tTianKong.task15]["Title"] = tLuaText[LANGUAGE_CONFIG][21495]
rwtTask[tTianKong.task15]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task15]["TaskQuality"] = 5
rwtTask[tTianKong.task15]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task15]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task15]["AwardGroupId"] = 3
rwtTask[tTianKong.task15]["TaskNpc"] = tSingleNpc.nNpc_TianShenSHouWei
rwtTask[tTianKong.task15]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tTianKong.task15]["DialogId"] = tDialog.nTask3_2
rwtTask[tTianKong.task15]["StartAutoWay"] = {}
rwtTask[tTianKong.task15]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task15]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task15]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_TianShenSHouWei
rwtTask[tTianKong.task15]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_TianShenSHouWei

--------------------------------------新物种研究---------------------------------------------------

rwtTask[tTianKong.task16] = {}
rwtTask[tTianKong.task16]["Title"] = tLuaText[LANGUAGE_CONFIG][21496]
rwtTask[tTianKong.task16]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task16]["TaskQuality"] = 1
rwtTask[tTianKong.task16]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task16]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task16]["AwardGroupId"] = 4
rwtTask[tTianKong.task16]["TaskNpc"] = tSingleNpc.nNpc_MaLuXi
rwtTask[tTianKong.task16]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tTianKong.task16]["DialogId"] = tDialog.nTask4_2
rwtTask[tTianKong.task16]["StartAutoWay"] = {}
rwtTask[tTianKong.task16]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task16]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task16]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_MaLuXi
rwtTask[tTianKong.task16]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_MaLuXi

rwtTask[tTianKong.task17] = {}
rwtTask[tTianKong.task17]["Title"] = tLuaText[LANGUAGE_CONFIG][21496]
rwtTask[tTianKong.task17]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task17]["TaskQuality"] = 2
rwtTask[tTianKong.task17]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task17]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task17]["AwardGroupId"] = 4
rwtTask[tTianKong.task17]["TaskNpc"] = tSingleNpc.nNpc_MaLuXi
rwtTask[tTianKong.task17]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tTianKong.task17]["DialogId"] = tDialog.nTask4_2
rwtTask[tTianKong.task17]["StartAutoWay"] = {}
rwtTask[tTianKong.task17]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task17]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task17]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_MaLuXi
rwtTask[tTianKong.task17]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_MaLuXi

rwtTask[tTianKong.task18] = {}
rwtTask[tTianKong.task18]["Title"] = tLuaText[LANGUAGE_CONFIG][21496]
rwtTask[tTianKong.task18]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task18]["TaskQuality"] = 3
rwtTask[tTianKong.task18]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task18]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task18]["AwardGroupId"] = 4
rwtTask[tTianKong.task18]["TaskNpc"] = tSingleNpc.nNpc_MaLuXi
rwtTask[tTianKong.task18]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tTianKong.task18]["DialogId"] = tDialog.nTask4_2
rwtTask[tTianKong.task18]["StartAutoWay"] = {}
rwtTask[tTianKong.task18]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task18]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task18]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_MaLuXi
rwtTask[tTianKong.task18]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_MaLuXi

rwtTask[tTianKong.task19] = {}
rwtTask[tTianKong.task19]["Title"] = tLuaText[LANGUAGE_CONFIG][21496]
rwtTask[tTianKong.task19]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task19]["TaskQuality"] = 4
rwtTask[tTianKong.task19]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task19]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task19]["AwardGroupId"] = 4
rwtTask[tTianKong.task19]["TaskNpc"] = tSingleNpc.nNpc_MaLuXi
rwtTask[tTianKong.task19]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tTianKong.task19]["DialogId"] = tDialog.nTask4_2
rwtTask[tTianKong.task19]["StartAutoWay"] = {}
rwtTask[tTianKong.task19]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task19]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task19]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_MaLuXi
rwtTask[tTianKong.task19]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_MaLuXi

rwtTask[tTianKong.task20] = {}
rwtTask[tTianKong.task20]["Title"] = tLuaText[LANGUAGE_CONFIG][21496]
rwtTask[tTianKong.task20]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task20]["TaskQuality"] = 5
rwtTask[tTianKong.task20]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task20]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tTianKong.task20]["AwardGroupId"] = 4
rwtTask[tTianKong.task20]["TaskNpc"] = tSingleNpc.nNpc_MaLuXi
rwtTask[tTianKong.task20]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tTianKong.task20]["DialogId"] = tDialog.nTask4_2
rwtTask[tTianKong.task20]["StartAutoWay"] = {}
rwtTask[tTianKong.task20]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task20]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task20]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_MaLuXi
rwtTask[tTianKong.task20]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_MaLuXi

------------------------------------采集圣水---------------------------------------------------

rwtTask[tTianKong.task21] = {}
rwtTask[tTianKong.task21]["Title"] = tLuaText[LANGUAGE_CONFIG][21497]
rwtTask[tTianKong.task21]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task21]["TaskQuality"] = 1
rwtTask[tTianKong.task21]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task21]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task21]["AwardGroupId"] = 5
rwtTask[tTianKong.task21]["ReqCollectId1"] =   tCollect.nCollect_Shengshui
rwtTask[tTianKong.task21]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task21]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task21]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tTianKong.task21]["DialogId"] = tDialog.nTask5_2
rwtTask[tTianKong.task21]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task21]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task21]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Shengshui
rwtTask[tTianKong.task21]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task21]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task21]["StartAutoWay"] = {}
rwtTask[tTianKong.task21]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task21]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task21]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Shengshui
rwtTask[tTianKong.task21]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Shengshui

rwtTask[tTianKong.task22] = {}
rwtTask[tTianKong.task22]["Title"] = tLuaText[LANGUAGE_CONFIG][21497]
rwtTask[tTianKong.task22]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task22]["TaskQuality"] = 2
rwtTask[tTianKong.task22]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task22]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task22]["AwardGroupId"] = 5
rwtTask[tTianKong.task22]["ReqCollectId1"] =   tCollect.nCollect_Shengshui
rwtTask[tTianKong.task22]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task22]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task22]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tTianKong.task22]["DialogId"] = tDialog.nTask5_2
rwtTask[tTianKong.task22]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task22]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task22]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Shengshui
rwtTask[tTianKong.task22]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task22]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task22]["StartAutoWay"] = {}
rwtTask[tTianKong.task22]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task22]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task22]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Shengshui
rwtTask[tTianKong.task22]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Shengshui

rwtTask[tTianKong.task23] = {}
rwtTask[tTianKong.task23]["Title"] = tLuaText[LANGUAGE_CONFIG][21497]
rwtTask[tTianKong.task23]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task23]["TaskQuality"] = 3
rwtTask[tTianKong.task23]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task23]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task23]["AwardGroupId"] = 5
rwtTask[tTianKong.task23]["ReqCollectId1"] =   tCollect.nCollect_Shengshui
rwtTask[tTianKong.task23]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task23]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task23]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tTianKong.task23]["DialogId"] = tDialog.nTask5_2
rwtTask[tTianKong.task23]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task23]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task23]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Shengshui
rwtTask[tTianKong.task23]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task23]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task23]["StartAutoWay"] = {}
rwtTask[tTianKong.task23]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task23]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task23]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Shengshui
rwtTask[tTianKong.task23]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Shengshui

rwtTask[tTianKong.task24] = {}
rwtTask[tTianKong.task24]["Title"] = tLuaText[LANGUAGE_CONFIG][21497]
rwtTask[tTianKong.task24]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task24]["TaskQuality"] = 4
rwtTask[tTianKong.task24]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task24]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task24]["AwardGroupId"] = 5
rwtTask[tTianKong.task24]["ReqCollectId1"] =   tCollect.nCollect_Shengshui
rwtTask[tTianKong.task24]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task24]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task24]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tTianKong.task24]["DialogId"] = tDialog.nTask5_2
rwtTask[tTianKong.task24]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task24]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task24]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Shengshui
rwtTask[tTianKong.task24]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task24]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task24]["StartAutoWay"] = {}
rwtTask[tTianKong.task24]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task24]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task24]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Shengshui
rwtTask[tTianKong.task24]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Shengshui

rwtTask[tTianKong.task25] = {}
rwtTask[tTianKong.task25]["Title"] = tLuaText[LANGUAGE_CONFIG][21497]
rwtTask[tTianKong.task25]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task25]["TaskQuality"] = 5
rwtTask[tTianKong.task25]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task25]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task25]["AwardGroupId"] = 5
rwtTask[tTianKong.task25]["ReqCollectId1"] =   tCollect.nCollect_Shengshui
rwtTask[tTianKong.task25]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task25]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task25]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tTianKong.task25]["DialogId"] = tDialog.nTask5_2
rwtTask[tTianKong.task25]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task25]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task25]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Shengshui
rwtTask[tTianKong.task25]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task25]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task25]["StartAutoWay"] = {}
rwtTask[tTianKong.task25]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task25]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task25]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Shengshui
rwtTask[tTianKong.task25]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Shengshui


-------------------------------定期养护=--------------------------------------------------
rwtTask[tTianKong.task26] = {}
rwtTask[tTianKong.task26]["Title"] = tLuaText[LANGUAGE_CONFIG][21498]
rwtTask[tTianKong.task26]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task26]["TaskQuality"] = 1
rwtTask[tTianKong.task26]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task26]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task26]["AwardGroupId"] = 1
rwtTask[tTianKong.task26]["ReqCollectId1"] =   tCollect.nCollect_Robot
rwtTask[tTianKong.task26]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task26]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task26]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tTianKong.task26]["DialogId"] = tDialog.nTask6_2
rwtTask[tTianKong.task26]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task26]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task26]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Robot
rwtTask[tTianKong.task26]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task26]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task26]["StartAutoWay"] = {}
rwtTask[tTianKong.task26]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task26]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task26]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Robot
rwtTask[tTianKong.task26]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Robot


rwtTask[tTianKong.task27] = {}
rwtTask[tTianKong.task27]["Title"] = tLuaText[LANGUAGE_CONFIG][21498]
rwtTask[tTianKong.task27]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task27]["TaskQuality"] = 2
rwtTask[tTianKong.task27]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task27]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task27]["AwardGroupId"] = 1
rwtTask[tTianKong.task27]["ReqCollectId1"] =   tCollect.nCollect_Robot
rwtTask[tTianKong.task27]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task27]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task27]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tTianKong.task27]["DialogId"] = tDialog.nTask6_2
rwtTask[tTianKong.task27]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task27]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task27]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Robot
rwtTask[tTianKong.task27]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task27]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task27]["StartAutoWay"] = {}
rwtTask[tTianKong.task27]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task27]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task27]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Robot
rwtTask[tTianKong.task27]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Robot

rwtTask[tTianKong.task28] = {}
rwtTask[tTianKong.task28]["Title"] = tLuaText[LANGUAGE_CONFIG][21498]
rwtTask[tTianKong.task28]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task28]["TaskQuality"] = 3
rwtTask[tTianKong.task28]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task28]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task28]["AwardGroupId"] = 1
rwtTask[tTianKong.task28]["ReqCollectId1"] =   tCollect.nCollect_Robot
rwtTask[tTianKong.task28]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task28]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task28]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tTianKong.task28]["DialogId"] = tDialog.nTask6_2
rwtTask[tTianKong.task28]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task28]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task28]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Robot
rwtTask[tTianKong.task28]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task28]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task28]["StartAutoWay"] = {}
rwtTask[tTianKong.task28]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task28]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task28]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Robot
rwtTask[tTianKong.task28]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Robot

rwtTask[tTianKong.task29] = {}
rwtTask[tTianKong.task29]["Title"] = tLuaText[LANGUAGE_CONFIG][21498]
rwtTask[tTianKong.task29]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task29]["TaskQuality"] = 4
rwtTask[tTianKong.task29]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task29]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task29]["AwardGroupId"] = 1
rwtTask[tTianKong.task29]["ReqCollectId1"] =   tCollect.nCollect_Robot
rwtTask[tTianKong.task29]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task29]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task29]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tTianKong.task29]["DialogId"] = tDialog.nTask6_2
rwtTask[tTianKong.task29]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task29]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task29]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Robot
rwtTask[tTianKong.task29]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task29]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task29]["StartAutoWay"] = {}
rwtTask[tTianKong.task29]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task29]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task29]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Robot
rwtTask[tTianKong.task29]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Robot

rwtTask[tTianKong.task30] = {}
rwtTask[tTianKong.task30]["Title"] = tLuaText[LANGUAGE_CONFIG][21498]
rwtTask[tTianKong.task30]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task30]["TaskQuality"] = 5
rwtTask[tTianKong.task30]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task30]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task30]["AwardGroupId"] = 1
rwtTask[tTianKong.task30]["ReqCollectId1"] =   tCollect.nCollect_Robot
rwtTask[tTianKong.task30]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task30]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task30]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tTianKong.task30]["DialogId"] = tDialog.nTask6_2
rwtTask[tTianKong.task30]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task30]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task30]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Robot
rwtTask[tTianKong.task30]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task30]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task30]["StartAutoWay"] = {}
rwtTask[tTianKong.task30]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task30]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task30]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Robot
rwtTask[tTianKong.task30]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Robot

-----------------------------------纳雅科技箱--------------------------------------------
rwtTask[tTianKong.task31] = {}
rwtTask[tTianKong.task31]["Title"] = tLuaText[LANGUAGE_CONFIG][21499]
rwtTask[tTianKong.task31]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task31]["TaskQuality"] = 1
rwtTask[tTianKong.task31]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task31]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task31]["AwardGroupId"] = 2
rwtTask[tTianKong.task31]["ReqCollectId1"] =   tCollect.nCollect_Box
rwtTask[tTianKong.task31]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task31]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task31]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tTianKong.task31]["DialogId"] = tDialog.nTask7_2
rwtTask[tTianKong.task31]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task31]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task31]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Box
rwtTask[tTianKong.task31]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task31]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task31]["StartAutoWay"] = {}
rwtTask[tTianKong.task31]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task31]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task31]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Box
rwtTask[tTianKong.task31]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Box

rwtTask[tTianKong.task32] = {}
rwtTask[tTianKong.task32]["Title"] = tLuaText[LANGUAGE_CONFIG][21499]
rwtTask[tTianKong.task32]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task32]["TaskQuality"] = 2
rwtTask[tTianKong.task32]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task32]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task32]["AwardGroupId"] = 2
rwtTask[tTianKong.task32]["ReqCollectId1"] =   tCollect.nCollect_Box
rwtTask[tTianKong.task32]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task32]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task32]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tTianKong.task32]["DialogId"] = tDialog.nTask7_2
rwtTask[tTianKong.task32]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task32]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task32]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Box
rwtTask[tTianKong.task32]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task32]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task32]["StartAutoWay"] = {}
rwtTask[tTianKong.task32]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task32]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task32]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Box
rwtTask[tTianKong.task32]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Box

rwtTask[tTianKong.task33] = {}
rwtTask[tTianKong.task33]["Title"] = tLuaText[LANGUAGE_CONFIG][21499]
rwtTask[tTianKong.task33]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task33]["TaskQuality"] = 3
rwtTask[tTianKong.task33]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task33]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task33]["AwardGroupId"] = 2
rwtTask[tTianKong.task33]["ReqCollectId1"] =   tCollect.nCollect_Box
rwtTask[tTianKong.task33]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task33]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task33]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tTianKong.task33]["DialogId"] = tDialog.nTask7_2
rwtTask[tTianKong.task33]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task33]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task33]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Box
rwtTask[tTianKong.task33]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task33]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task33]["StartAutoWay"] = {}
rwtTask[tTianKong.task33]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task33]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task33]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Box
rwtTask[tTianKong.task33]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Box

rwtTask[tTianKong.task34] = {}
rwtTask[tTianKong.task34]["Title"] = tLuaText[LANGUAGE_CONFIG][21499]
rwtTask[tTianKong.task34]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task34]["TaskQuality"] = 4
rwtTask[tTianKong.task34]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task34]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task34]["AwardGroupId"] = 2
rwtTask[tTianKong.task34]["ReqCollectId1"] =   tCollect.nCollect_Box
rwtTask[tTianKong.task34]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task34]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task34]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tTianKong.task34]["DialogId"] = tDialog.nTask7_2
rwtTask[tTianKong.task34]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task34]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task34]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Box
rwtTask[tTianKong.task34]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task34]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task34]["StartAutoWay"] = {}
rwtTask[tTianKong.task34]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task34]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task34]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Box

rwtTask[tTianKong.task35] = {}
rwtTask[tTianKong.task35]["Title"] = tLuaText[LANGUAGE_CONFIG][21499]
rwtTask[tTianKong.task35]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task35]["TaskQuality"] = 5
rwtTask[tTianKong.task35]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task35]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tTianKong.task35]["AwardGroupId"] = 2
rwtTask[tTianKong.task35]["ReqCollectId1"] =   tCollect.nCollect_Box
rwtTask[tTianKong.task35]["ReqCollectOnceNum"] = 1
rwtTask[tTianKong.task35]["ReqCollectCount1"] =  1
rwtTask[tTianKong.task35]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tTianKong.task35]["DialogId"] = tDialog.nTask7_2
rwtTask[tTianKong.task35]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task35]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task35]["DynaNpcGroupGen"][1]["GenId"] = tCollect.nCollect_GenId_Box
rwtTask[tTianKong.task35]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task35]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task35]["StartAutoWay"] = {}
rwtTask[tTianKong.task35]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tTianKong.task35]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task35]["StartAutoWay"]["FindWayGroupId"] = tCollect.nCollect_Box
rwtTask[tTianKong.task35]["StartAutoWay"]["FindWayGenId"] = tCollect.nCollect_GenId_Box

---------------------------------危险实验体------------------------------------
rwtTask[tTianKong.task36] = {}
rwtTask[tTianKong.task36]["Title"] = tLuaText[LANGUAGE_CONFIG][21500]
rwtTask[tTianKong.task36]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task36]["TaskQuality"] = 1
rwtTask[tTianKong.task36]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task36]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task36]["AwardGroupId"] = 3
rwtTask[tTianKong.task36]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task36]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task36]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task36]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task36]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task36]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task36]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task36]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tTianKong.task36]["StartAutoWay"] = {}
rwtTask[tTianKong.task36]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task36]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task36]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task36]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi

rwtTask[tTianKong.task37] = {}
rwtTask[tTianKong.task37]["Title"] = tLuaText[LANGUAGE_CONFIG][21500]
rwtTask[tTianKong.task37]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task37]["TaskQuality"] = 2
rwtTask[tTianKong.task37]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task37]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task37]["AwardGroupId"] = 3
rwtTask[tTianKong.task37]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task37]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task37]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task37]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task37]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task37]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task37]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task37]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tTianKong.task37]["StartAutoWay"] = {}
rwtTask[tTianKong.task37]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task37]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task37]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task37]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi

rwtTask[tTianKong.task38] = {}
rwtTask[tTianKong.task38]["Title"] = tLuaText[LANGUAGE_CONFIG][21500]
rwtTask[tTianKong.task38]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task38]["TaskQuality"] = 3
rwtTask[tTianKong.task38]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task38]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task38]["AwardGroupId"] = 3
rwtTask[tTianKong.task38]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task38]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task38]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task38]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task38]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task38]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task38]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task38]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tTianKong.task38]["StartAutoWay"] = {}
rwtTask[tTianKong.task38]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task38]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task38]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task38]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi

rwtTask[tTianKong.task39] = {}
rwtTask[tTianKong.task39]["Title"] = tLuaText[LANGUAGE_CONFIG][21500]
rwtTask[tTianKong.task39]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task39]["TaskQuality"] = 4
rwtTask[tTianKong.task39]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task39]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task39]["AwardGroupId"] = 3
rwtTask[tTianKong.task39]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task39]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task39]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task39]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task39]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task39]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task39]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task39]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tTianKong.task39]["StartAutoWay"] = {}
rwtTask[tTianKong.task39]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task39]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task39]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task39]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi

rwtTask[tTianKong.task40] = {}
rwtTask[tTianKong.task40]["Title"] = tLuaText[LANGUAGE_CONFIG][21500]
rwtTask[tTianKong.task40]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task40]["TaskQuality"] = 5
rwtTask[tTianKong.task40]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task40]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task40]["AwardGroupId"] = 3
rwtTask[tTianKong.task40]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task40]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task40]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task40]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task40]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi
rwtTask[tTianKong.task40]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task40]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task40]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tTianKong.task40]["StartAutoWay"] = {}
rwtTask[tTianKong.task40]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task40]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task40]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_ShiYanTi
rwtTask[tTianKong.task40]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_ShiYanTi

------------------------------------天空城潜伏者------------------------------------------------
rwtTask[tTianKong.task41] = {}
rwtTask[tTianKong.task41]["Title"] = tLuaText[LANGUAGE_CONFIG][20501]
rwtTask[tTianKong.task41]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task41]["TaskQuality"] = 1
rwtTask[tTianKong.task41]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task41]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task41]["AwardGroupId"] = 4
rwtTask[tTianKong.task41]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task41]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task41]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task41]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task41]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task41]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task41]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task41]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tTianKong.task41]["StartAutoWay"] = {}
rwtTask[tTianKong.task41]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task41]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task41]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task41]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe

rwtTask[tTianKong.task42] = {}
rwtTask[tTianKong.task42]["Title"] = tLuaText[LANGUAGE_CONFIG][20501]
rwtTask[tTianKong.task42]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task42]["TaskQuality"] = 2
rwtTask[tTianKong.task42]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task42]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task42]["AwardGroupId"] = 4
rwtTask[tTianKong.task42]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task42]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task42]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task42]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task42]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task42]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task42]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task42]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tTianKong.task42]["StartAutoWay"] = {}
rwtTask[tTianKong.task42]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task42]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task42]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task42]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe

rwtTask[tTianKong.task43] = {}
rwtTask[tTianKong.task43]["Title"] = tLuaText[LANGUAGE_CONFIG][20501]
rwtTask[tTianKong.task43]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task43]["TaskQuality"] = 3
rwtTask[tTianKong.task43]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task43]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task43]["AwardGroupId"] = 4
rwtTask[tTianKong.task43]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task43]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task43]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task43]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task43]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task43]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task43]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task43]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tTianKong.task43]["StartAutoWay"] = {}
rwtTask[tTianKong.task43]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task43]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task43]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task43]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe

rwtTask[tTianKong.task44] = {}
rwtTask[tTianKong.task44]["Title"] = tLuaText[LANGUAGE_CONFIG][20501]
rwtTask[tTianKong.task44]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task44]["TaskQuality"] = 4
rwtTask[tTianKong.task44]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task44]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task44]["AwardGroupId"] = 4
rwtTask[tTianKong.task44]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task44]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task44]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task44]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task44]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task44]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task44]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task44]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tTianKong.task44]["StartAutoWay"] = {}
rwtTask[tTianKong.task44]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task44]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task44]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task44]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe

rwtTask[tTianKong.task45] = {}
rwtTask[tTianKong.task45]["Title"] = tLuaText[LANGUAGE_CONFIG][20501]
rwtTask[tTianKong.task45]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task45]["TaskQuality"] = 5
rwtTask[tTianKong.task45]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task45]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task45]["AwardGroupId"] = 4
rwtTask[tTianKong.task45]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task45]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task45]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task45]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task45]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe
rwtTask[tTianKong.task45]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task45]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task45]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tTianKong.task45]["StartAutoWay"] = {}
rwtTask[tTianKong.task45]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task45]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task45]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_QianFuZhe
rwtTask[tTianKong.task45]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_QianFuZhe

-----------------------------------实力的考验--------------------------------------------------------
rwtTask[tTianKong.task46] = {}
rwtTask[tTianKong.task46]["Title"] = tLuaText[LANGUAGE_CONFIG][20502]
rwtTask[tTianKong.task46]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task46]["TaskQuality"] = 1
rwtTask[tTianKong.task46]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task46]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task46]["AwardGroupId"] = 5
rwtTask[tTianKong.task46]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task46]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task46]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tTianKong.task46]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task46]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task46]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task46]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task46]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task46]["StartAutoWay"] = {}
rwtTask[tTianKong.task46]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task46]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task46]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task46]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang

rwtTask[tTianKong.task47] = {}
rwtTask[tTianKong.task47]["Title"] = tLuaText[LANGUAGE_CONFIG][20502]
rwtTask[tTianKong.task47]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task47]["TaskQuality"] = 2
rwtTask[tTianKong.task47]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task47]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task47]["AwardGroupId"] = 5
rwtTask[tTianKong.task47]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task47]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task47]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tTianKong.task47]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task47]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task47]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task47]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task47]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task47]["StartAutoWay"] = {}
rwtTask[tTianKong.task47]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task47]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task47]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task47]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang

rwtTask[tTianKong.task48] = {}
rwtTask[tTianKong.task48]["Title"] = tLuaText[LANGUAGE_CONFIG][20502]
rwtTask[tTianKong.task48]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task48]["TaskQuality"] = 3
rwtTask[tTianKong.task48]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task48]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task48]["AwardGroupId"] = 5
rwtTask[tTianKong.task48]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task48]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task48]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tTianKong.task48]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task48]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task48]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task48]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task48]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task48]["StartAutoWay"] = {}
rwtTask[tTianKong.task48]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task48]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task48]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task48]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang

rwtTask[tTianKong.task49] = {}
rwtTask[tTianKong.task49]["Title"] = tLuaText[LANGUAGE_CONFIG][20502]
rwtTask[tTianKong.task49]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task49]["TaskQuality"] = 4
rwtTask[tTianKong.task49]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task49]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task49]["AwardGroupId"] = 5
rwtTask[tTianKong.task49]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task49]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task49]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tTianKong.task49]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task49]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task49]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task49]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task49]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task49]["StartAutoWay"] = {}
rwtTask[tTianKong.task49]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task49]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task49]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task49]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang

rwtTask[tTianKong.task50] = {}
rwtTask[tTianKong.task50]["Title"] = tLuaText[LANGUAGE_CONFIG][20502]
rwtTask[tTianKong.task50]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tTianKong.task50]["TaskQuality"] = 5
rwtTask[tTianKong.task50]["MercenaryTownId"] = nTownId
rwtTask[tTianKong.task50]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tTianKong.task50]["AwardGroupId"] = 5
rwtTask[tTianKong.task50]["KillMonsterGroup1"] =   tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task50]["MonsterGroupGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task50]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tTianKong.task50]["DynaNpcGroupGen"] = {}
rwtTask[tTianKong.task50]["DynaNpcGroupGen"][1] = {}
rwtTask[tTianKong.task50]["DynaNpcGroupGen"][1]["GenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang
rwtTask[tTianKong.task50]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tTianKong.task50]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tTianKong.task50]["StartAutoWay"] = {}
rwtTask[tTianKong.task50]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tTianKong.task50]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tTianKong.task50]["StartAutoWay"]["FindWayGroupId"] = tMonster.nMonsterGroup_WeiDuiZhang
rwtTask[tTianKong.task50]["StartAutoWay"]["FindWayGenId"] = tMonster.nMonsterGroup_GenId_WeiDuiZhang