--region *.lua
--Date 2019-6-10
--此文件由[BabeLua]插件自动生成
--BY: Dona

--endregion

--地图ID
local nMapId = 2005

--镇子ID
local nTownId = 200505

--任务ID
local tKouDaiMercenary = {}
tKouDaiMercenary.task1  = 20922		--机械师的补给
tKouDaiMercenary.task2  = 20923		--机械师的补给
tKouDaiMercenary.task3  = 20924		--机械师的补给
tKouDaiMercenary.task4  = 20925		--机械师的补给
tKouDaiMercenary.task5  = 20926		--机械师的补给
tKouDaiMercenary.task6  = 20927		--废物再利用
tKouDaiMercenary.task7  = 20928		--废物再利用
tKouDaiMercenary.task8  = 20929		--废物再利用
tKouDaiMercenary.task9  = 20930		--废物再利用
tKouDaiMercenary.task10 = 20931		--废物再利用
tKouDaiMercenary.task11 = 20932		--例行检测
tKouDaiMercenary.task12 = 20933		--例行检测
tKouDaiMercenary.task13 = 20934		--例行检测
tKouDaiMercenary.task14 = 20935		--例行检测
tKouDaiMercenary.task15 = 20936		--例行检测
tKouDaiMercenary.task16 = 20937		--探查黄金立方
tKouDaiMercenary.task17 = 20938		--探查黄金立方
tKouDaiMercenary.task18 = 20939		--探查黄金立方
tKouDaiMercenary.task19 = 20940		--探查黄金立方
tKouDaiMercenary.task20 = 20941		--探查黄金立方
tKouDaiMercenary.task21 = 20942		--残骸调查
tKouDaiMercenary.task22 = 20943		--残骸调查
tKouDaiMercenary.task23 = 20944		--残骸调查
tKouDaiMercenary.task24 = 20945		--残骸调查
tKouDaiMercenary.task25 = 20946		--残骸调查
tKouDaiMercenary.task26 = 20947		--珍奇宝矿
tKouDaiMercenary.task27 = 20948		--珍奇宝矿
tKouDaiMercenary.task28 = 20949		--珍奇宝矿
tKouDaiMercenary.task29 = 20950		--珍奇宝矿
tKouDaiMercenary.task30 = 20951		--珍奇宝矿
tKouDaiMercenary.task31 = 20952		--铲除余党
tKouDaiMercenary.task32 = 20953		--铲除余党
tKouDaiMercenary.task33 = 20954		--铲除余党
tKouDaiMercenary.task34 = 20955		--铲除余党
tKouDaiMercenary.task35 = 20956		--铲除余党
tKouDaiMercenary.task36 = 20957		--打黑除恶
tKouDaiMercenary.task37 = 20958		--打黑除恶
tKouDaiMercenary.task38 = 20959		--打黑除恶
tKouDaiMercenary.task39 = 20960		--打黑除恶
tKouDaiMercenary.task40 = 20961		--打黑除恶
tKouDaiMercenary.task41 = 20962		--机械狂乱
tKouDaiMercenary.task42 = 20963		--机械狂乱
tKouDaiMercenary.task43 = 20964		--机械狂乱
tKouDaiMercenary.task44 = 20965		--机械狂乱
tKouDaiMercenary.task45 = 20966		--机械狂乱
tKouDaiMercenary.task46 = 20967		--联盟通缉令
tKouDaiMercenary.task47 = 20968		--联盟通缉令
tKouDaiMercenary.task48 = 20969		--联盟通缉令
tKouDaiMercenary.task49 = 20970		--联盟通缉令
tKouDaiMercenary.task50 = 20971		--联盟通缉令


--对话ID
local tDialog = {}
tDialog.nTask1_1  =	12598	--机械师的补给
tDialog.nTask1_2  =	12599	--机械师的补给
tDialog.nTask2_1  =	12600	--废物再利用
tDialog.nTask2_2  =	12601	--废物再利用
tDialog.nTask3_1  =	12602	--例行检测
tDialog.nTask3_2  =	12603	--例行检测
tDialog.nTask4_1  =	12604	--探查黄金立方
tDialog.nTask4_2  =	12605	--探查黄金立方
tDialog.nTask5_1  =	12606	--残骸调查
tDialog.nTask5_2  =	12607	--残骸调查
tDialog.nTask6_1  =	12608	--收集贵金属
tDialog.nTask6_2  =	12609	--收集贵金属
tDialog.nTask7_1  =	12610	--铲除余党
tDialog.nTask7_2  =	12611	--铲除余党
tDialog.nTask8_1  =	12612	--打黑除恶
--tDialog.nTask8_2  =	12613	--打黑除恶
tDialog.nTask9_1  =	12614	--机械狂乱
tDialog.nTask9_2  =	12615	--机械狂乱
tDialog.nTask10_1 =	12616	--联盟通缉令
--tDialog.nTask10_2 =	12617	--联盟通缉令


--采集物ID
local tCollect= {}

tCollect.Id1 = 60390	--黄金立方外围
tCollect.GenId1 = 20050320
rwtNpcGroup[tCollect.Id1] = rwtNpcGroup[tCollect.Id1] or {} 
rwtNpcGroup[tCollect.Id1]["Type"] = CONST_NPCGROUP_TYPE.Collect

tCollect.Id2 = 60391 --收集航舰残骸
tCollect.GenId2 = 20050321
rwtNpcGroup[tCollect.Id2] = rwtNpcGroup[tCollect.Id2] or {} 
rwtNpcGroup[tCollect.Id2]["Type"] = CONST_NPCGROUP_TYPE.Collect

tCollect.Id3 = 60392 --采集金属矿（0/1）
tCollect.GenId3 = 20050322
rwtNpcGroup[tCollect.Id3] = rwtNpcGroup[tCollect.Id3] or {} 
rwtNpcGroup[tCollect.Id3]["Type"] = CONST_NPCGROUP_TYPE.Collect


--怪物ID
local tMonsterGroup = {}

tMonsterGroup.Id1 = 900562
tMonsterGroup.Id2 = 900563
tMonsterGroup.Id3 = 900564
tMonsterGroup.Id4 = 900565
tMonsterGroup.GenId1 = 20050323
tMonsterGroup.GenId2 = 20050324
tMonsterGroup.GenId3 = 20050325
tMonsterGroup.GenId4 = 20050326


--NPCID
local tSingleNpc = {}

tSingleNpc.nNpc_1 =	3874		--机械师艾斯
tSingleNpc.nNpcGroup_1 = 20883
tSingleNpc.nNpcGroup_GenId_1= 20050327

rwtNpcGroup[tSingleNpc.nNpcGroup_1] = rwtNpcGroup[tSingleNpc.nNpcGroup_1] or {}  
rwtNpcGroup[tSingleNpc.nNpcGroup_1]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[tSingleNpc.nNpcGroup_1]["NpcId"] = tSingleNpc.nNpc_1

rwtNpc[tSingleNpc.nNpc_1] = rwtNpc[tSingleNpc.nNpc_1 ] or {}

--tSingleNpc.nNpc_2 = 3875		--工程师卡尔文
--tSingleNpc.nNpcGroup_2 = 20884
--tSingleNpc.nNpcGroup_GenId_2 = 20050328

tSingleNpc.nNpc_3 = 3638		--浮士德72
tSingleNpc.nNpcGroup_3 = 20593
tSingleNpc.nNpcGroup_GenId_3 = 20050209
--陷阱

local tTrap = {}--工程师卡尔文
tTrap.nNpcGroup_1 = 30650 
tTrap.nNpcGroup_GenId_1 = 20050328 

rwtNpcGroup[tTrap.nNpcGroup_1] = rwtNpcGroup[tTrap.nNpcGroup_1] or {}
rwtNpcGroup[tTrap.nNpcGroup_1]["Type"] = CONST_NPCGROUP_TYPE.Trap
--chinese
local tTaskTitle = {}

tTaskTitle["1_5"]	= 21761
tTaskTitle["6_10"]  = 21762
tTaskTitle["11_15"] = 21763
tTaskTitle["16_20"] = 21764
tTaskTitle["21_25"] = 21765
tTaskTitle["26_30"] = 21766
tTaskTitle["31_35"] = 21767
tTaskTitle["36_40"] = 21768
tTaskTitle["41_45"] = 21769
tTaskTitle["46_50"] = 21770

--------------------------------机械师的补给------------------------------------------------

rwtTask[tKouDaiMercenary.task1] = {}
rwtTask[tKouDaiMercenary.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["1_5"]]
rwtTask[tKouDaiMercenary.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task1]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task1]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task1]["TaskNpc"] = tSingleNpc.nNpc_1 
rwtTask[tKouDaiMercenary.task1]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tKouDaiMercenary.task1]["DialogId"] = tDialog.nTask1_2
rwtTask[tKouDaiMercenary.task1]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task1]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task1]["DynaNpcGroupGen"][1]["GenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task1]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task1]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task1]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task1]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task1]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_1 
rwtTask[tKouDaiMercenary.task1]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task1]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task1]["TaskQuality"] = 1


rwtTask[tKouDaiMercenary.task2] = {}
rwtTask[tKouDaiMercenary.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["1_5"]]
rwtTask[tKouDaiMercenary.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task2]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task2]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task2]["TaskNpc"] = tSingleNpc.nNpc_1 
rwtTask[tKouDaiMercenary.task2]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tKouDaiMercenary.task2]["DialogId"] = tDialog.nTask1_2
rwtTask[tKouDaiMercenary.task2]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task2]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task2]["DynaNpcGroupGen"][1]["GenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task2]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task2]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task2]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task2]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task2]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_1 
rwtTask[tKouDaiMercenary.task2]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task2]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task2]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task3] = {}
rwtTask[tKouDaiMercenary.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["1_5"]]
rwtTask[tKouDaiMercenary.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task3]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task3]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task3]["TaskNpc"] = tSingleNpc.nNpc_1 
rwtTask[tKouDaiMercenary.task3]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tKouDaiMercenary.task3]["DialogId"] = tDialog.nTask1_2
rwtTask[tKouDaiMercenary.task3]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task3]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task3]["DynaNpcGroupGen"][1]["GenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task3]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task3]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task3]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task3]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task3]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_1 
rwtTask[tKouDaiMercenary.task3]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task3]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task3]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task4] = {}
rwtTask[tKouDaiMercenary.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["1_5"]]
rwtTask[tKouDaiMercenary.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task4]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task4]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task4]["TaskNpc"] = tSingleNpc.nNpc_1 
rwtTask[tKouDaiMercenary.task4]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tKouDaiMercenary.task4]["DialogId"] = tDialog.nTask1_2
rwtTask[tKouDaiMercenary.task4]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task4]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task4]["DynaNpcGroupGen"][1]["GenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task4]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task4]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task4]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task4]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task4]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_1 
rwtTask[tKouDaiMercenary.task4]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task4]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task4]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task5] = {}
rwtTask[tKouDaiMercenary.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["1_5"]]
rwtTask[tKouDaiMercenary.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task5]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task5]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task5]["TaskNpc"] = tSingleNpc.nNpc_1 
rwtTask[tKouDaiMercenary.task5]["AcceptDialogId"] = tDialog.nTask1_1
rwtTask[tKouDaiMercenary.task5]["DialogId"] = tDialog.nTask1_2
rwtTask[tKouDaiMercenary.task5]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task5]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task5]["DynaNpcGroupGen"][1]["GenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task5]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task5]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task5]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task5]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task5]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_1 
rwtTask[tKouDaiMercenary.task5]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task5]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task5]["TaskQuality"] = 5

---------------------------------废物再利用----------------------------------------

rwtTask[tKouDaiMercenary.task6] = {}
rwtTask[tKouDaiMercenary.task6]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["6_10"]]
rwtTask[tKouDaiMercenary.task6]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task6]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task6]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_TRAP
rwtTask[tKouDaiMercenary.task6]["ReqTrap1" ]= tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task6]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tKouDaiMercenary.task6]["DialogId"] = tDialog.nTask2_2
rwtTask[tKouDaiMercenary.task6]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task6]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task6]["DynaNpcGroupGen"][1]["GenId"] = tTrap.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task6]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task6]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task6]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task6]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task6]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task6]["StartAutoWay"]["FindWayGroupId"] = tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task6]["StartAutoWay"]["FindWayGenId"] = tTrap.nNpcGroup_GenId_1 
rwtTask[tKouDaiMercenary.task6]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task6]["TaskQuality"] = 1

rwtTask[tKouDaiMercenary.task7] = {}
rwtTask[tKouDaiMercenary.task7]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["6_10"]]
rwtTask[tKouDaiMercenary.task7]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task7]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task7]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_TRAP
rwtTask[tKouDaiMercenary.task7]["ReqTrap1" ]= tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task7]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tKouDaiMercenary.task7]["DialogId"] = tDialog.nTask2_2
rwtTask[tKouDaiMercenary.task7]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task7]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task7]["DynaNpcGroupGen"][1]["GenId"] = tTrap.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task7]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task7]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task7]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task7]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task7]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task7]["StartAutoWay"]["FindWayGroupId"] = tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task7]["StartAutoWay"]["FindWayGenId"] = tTrap.nNpcGroup_GenId_1 
rwtTask[tKouDaiMercenary.task7]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task7]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task8] = {}
rwtTask[tKouDaiMercenary.task8]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["6_10"]]
rwtTask[tKouDaiMercenary.task8]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task8]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task8]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_TRAP
rwtTask[tKouDaiMercenary.task8]["ReqTrap1" ]= tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task8]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tKouDaiMercenary.task8]["DialogId"] = tDialog.nTask2_2
rwtTask[tKouDaiMercenary.task8]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task8]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task8]["DynaNpcGroupGen"][1]["GenId"] = tTrap.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task8]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task8]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task8]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task8]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task8]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task8]["StartAutoWay"]["FindWayGroupId"] = tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task8]["StartAutoWay"]["FindWayGenId"] = tTrap.nNpcGroup_GenId_1 
rwtTask[tKouDaiMercenary.task8]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task8]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task9] = {}
rwtTask[tKouDaiMercenary.task9]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["6_10"]]
rwtTask[tKouDaiMercenary.task9]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task9]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task9]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_TRAP
rwtTask[tKouDaiMercenary.task9]["ReqTrap1" ]= tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task9]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tKouDaiMercenary.task9]["DialogId"] = tDialog.nTask2_2
rwtTask[tKouDaiMercenary.task9]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task9]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task9]["DynaNpcGroupGen"][1]["GenId"] = tTrap.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task9]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task9]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task9]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task9]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task9]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task9]["StartAutoWay"]["FindWayGroupId"] = tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task9]["StartAutoWay"]["FindWayGenId"] = tTrap.nNpcGroup_GenId_1 
rwtTask[tKouDaiMercenary.task9]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task9]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task10] = {}
rwtTask[tKouDaiMercenary.task10]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["6_10"]]
rwtTask[tKouDaiMercenary.task10]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task10]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task10]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_TRAP
rwtTask[tKouDaiMercenary.task10]["ReqTrap1" ]= tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task10]["AcceptDialogId"] = tDialog.nTask2_1
rwtTask[tKouDaiMercenary.task10]["DialogId"] = tDialog.nTask2_2
rwtTask[tKouDaiMercenary.task10]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task10]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task10]["DynaNpcGroupGen"][1]["GenId"] = tTrap.nNpcGroup_GenId_1
rwtTask[tKouDaiMercenary.task10]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task10]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task10]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task10]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task10]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task10]["StartAutoWay"]["FindWayGroupId"] = tTrap.nNpcGroup_1
rwtTask[tKouDaiMercenary.task10]["StartAutoWay"]["FindWayGenId"] = tTrap.nNpcGroup_GenId_1 
rwtTask[tKouDaiMercenary.task10]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task10]["TaskQuality"] = 5
-------------------------------例行检测---------------------------------

rwtTask[tKouDaiMercenary.task11] = {}
rwtTask[tKouDaiMercenary.task11]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["11_15"]]
rwtTask[tKouDaiMercenary.task11]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task11]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task11]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task11]["TaskNpc"] = tSingleNpc.nNpc_3
rwtTask[tKouDaiMercenary.task11]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tKouDaiMercenary.task11]["DialogId"] = tDialog.nTask3_2
rwtTask[tKouDaiMercenary.task11]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task11]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task11]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task11]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_3
rwtTask[tKouDaiMercenary.task11]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_3 
rwtTask[tKouDaiMercenary.task11]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task11]["TaskQuality"] = 1


rwtTask[tKouDaiMercenary.task12] = {}
rwtTask[tKouDaiMercenary.task12]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["11_15"]]
rwtTask[tKouDaiMercenary.task12]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task12]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task12]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task12]["TaskNpc"] = tSingleNpc.nNpc_3
rwtTask[tKouDaiMercenary.task12]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tKouDaiMercenary.task12]["DialogId"] = tDialog.nTask3_2
rwtTask[tKouDaiMercenary.task12]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task12]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task12]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task12]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_3
rwtTask[tKouDaiMercenary.task12]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_3 
rwtTask[tKouDaiMercenary.task12]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task12]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task13] = {}
rwtTask[tKouDaiMercenary.task13]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["11_15"]]
rwtTask[tKouDaiMercenary.task13]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task13]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task13]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task13]["TaskNpc"] = tSingleNpc.nNpc_3
rwtTask[tKouDaiMercenary.task13]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tKouDaiMercenary.task13]["DialogId"] = tDialog.nTask3_2
rwtTask[tKouDaiMercenary.task13]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task13]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task13]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task13]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_3
rwtTask[tKouDaiMercenary.task13]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_3 
rwtTask[tKouDaiMercenary.task13]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task13]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task14] = {}
rwtTask[tKouDaiMercenary.task14]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["11_15"]]
rwtTask[tKouDaiMercenary.task14]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task14]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task14]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task14]["TaskNpc"] = tSingleNpc.nNpc_3
rwtTask[tKouDaiMercenary.task14]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tKouDaiMercenary.task14]["DialogId"] = tDialog.nTask3_2
rwtTask[tKouDaiMercenary.task14]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task14]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task14]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task14]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_3
rwtTask[tKouDaiMercenary.task14]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_3 
rwtTask[tKouDaiMercenary.task14]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task14]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task15] = {}
rwtTask[tKouDaiMercenary.task15]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["11_15"]]
rwtTask[tKouDaiMercenary.task15]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task15]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task15]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tKouDaiMercenary.task15]["TaskNpc"] = tSingleNpc.nNpc_3
rwtTask[tKouDaiMercenary.task15]["AcceptDialogId"] = tDialog.nTask3_1
rwtTask[tKouDaiMercenary.task15]["DialogId"] = tDialog.nTask3_2
rwtTask[tKouDaiMercenary.task15]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task15]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task15]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task15]["StartAutoWay"]["FindWayGroupId"] = tSingleNpc.nNpcGroup_3
rwtTask[tKouDaiMercenary.task15]["StartAutoWay"]["FindWayGenId"] = tSingleNpc.nNpcGroup_GenId_3 
rwtTask[tKouDaiMercenary.task15]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task15]["TaskQuality"] = 5

-------------------------------探查黄金立方----------------------------------------

rwtTask[tKouDaiMercenary.task16] = {}
rwtTask[tKouDaiMercenary.task16]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["16_20"]]
rwtTask[tKouDaiMercenary.task16]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task16]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task16]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task16]["ReqCollectId1"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task16]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task16]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task16]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tKouDaiMercenary.task16]["DialogId"] = tDialog.nTask4_2
rwtTask[tKouDaiMercenary.task16]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task16]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task16]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task16]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task16]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task16]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task16]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task16]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task16]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task16]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task16]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task16]["TaskQuality"] = 1

rwtTask[tKouDaiMercenary.task17] = {}
rwtTask[tKouDaiMercenary.task17]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["16_20"]]
rwtTask[tKouDaiMercenary.task17]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task17]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task17]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task17]["ReqCollectId1"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task17]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task17]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task17]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tKouDaiMercenary.task17]["DialogId"] = tDialog.nTask4_2
rwtTask[tKouDaiMercenary.task17]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task17]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task17]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task17]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task17]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task17]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task17]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task17]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task17]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task17]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task17]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task17]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task18] = {}
rwtTask[tKouDaiMercenary.task18]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["16_20"]]
rwtTask[tKouDaiMercenary.task18]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task18]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task18]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task18]["ReqCollectId1"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task18]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task18]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task18]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tKouDaiMercenary.task18]["DialogId"] = tDialog.nTask4_2
rwtTask[tKouDaiMercenary.task18]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task18]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task18]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task18]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task18]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task18]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task18]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task18]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task18]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task18]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task18]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task18]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task19] = {}
rwtTask[tKouDaiMercenary.task19]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["16_20"]]
rwtTask[tKouDaiMercenary.task19]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task19]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task19]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task19]["ReqCollectId1"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task19]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task19]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task19]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tKouDaiMercenary.task19]["DialogId"] = tDialog.nTask4_2
rwtTask[tKouDaiMercenary.task19]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task19]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task19]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task19]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task19]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task19]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task19]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task19]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task19]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task19]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task19]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task19]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task20] = {}
rwtTask[tKouDaiMercenary.task20]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["16_20"]]
rwtTask[tKouDaiMercenary.task20]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task20]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task20]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task20]["ReqCollectId1"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task20]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task20]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task20]["AcceptDialogId"] = tDialog.nTask4_1
rwtTask[tKouDaiMercenary.task20]["DialogId"] = tDialog.nTask4_2
rwtTask[tKouDaiMercenary.task20]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task20]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task20]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task20]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task20]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task20]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task20]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task20]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task20]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id1 
rwtTask[tKouDaiMercenary.task20]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId1
rwtTask[tKouDaiMercenary.task20]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task20]["TaskQuality"] = 5

--------------------------------------战舰残骸-----------------------------------------
rwtTask[tKouDaiMercenary.task21] = {}
rwtTask[tKouDaiMercenary.task21]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["21_25"]]
rwtTask[tKouDaiMercenary.task21]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task21]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task21]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task21]["ReqCollectId1"] =  tCollect.Id2 
rwtTask[tKouDaiMercenary.task21]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task21]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task21]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tKouDaiMercenary.task21]["DialogId"] = tDialog.nTask5_2
rwtTask[tKouDaiMercenary.task21]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task21]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task21]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task21]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task21]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task21]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task21]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task21]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task21]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id2 
rwtTask[tKouDaiMercenary.task21]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task21]["AwardGroupId"] = 5
rwtTask[tKouDaiMercenary.task21]["TaskQuality"] = 1

rwtTask[tKouDaiMercenary.task22] = {}
rwtTask[tKouDaiMercenary.task22]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["21_25"]]
rwtTask[tKouDaiMercenary.task22]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task22]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task22]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task22]["ReqCollectId1"] =  tCollect.Id2 
rwtTask[tKouDaiMercenary.task22]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task22]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task22]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tKouDaiMercenary.task22]["DialogId"] = tDialog.nTask5_2
rwtTask[tKouDaiMercenary.task22]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task22]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task22]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task22]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task22]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task22]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task22]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task22]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task22]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id2 
rwtTask[tKouDaiMercenary.task22]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task22]["AwardGroupId"] = 5
rwtTask[tKouDaiMercenary.task22]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task23] = {}
rwtTask[tKouDaiMercenary.task23]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["21_25"]]
rwtTask[tKouDaiMercenary.task23]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task23]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task23]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task23]["ReqCollectId1"] =  tCollect.Id2 
rwtTask[tKouDaiMercenary.task23]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task23]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task23]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tKouDaiMercenary.task23]["DialogId"] = tDialog.nTask5_2
rwtTask[tKouDaiMercenary.task23]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task23]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task23]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task23]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task23]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task23]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task23]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task23]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task23]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id2 
rwtTask[tKouDaiMercenary.task23]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task23]["AwardGroupId"] = 5
rwtTask[tKouDaiMercenary.task23]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task24] = {}
rwtTask[tKouDaiMercenary.task24]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["21_25"]]
rwtTask[tKouDaiMercenary.task24]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task24]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task24]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task24]["ReqCollectId1"] =  tCollect.Id2 
rwtTask[tKouDaiMercenary.task24]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task24]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task24]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tKouDaiMercenary.task24]["DialogId"] = tDialog.nTask5_2
rwtTask[tKouDaiMercenary.task24]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task24]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task24]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task24]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task24]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task24]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task24]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task24]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task24]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id2 
rwtTask[tKouDaiMercenary.task24]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task24]["AwardGroupId"] = 5
rwtTask[tKouDaiMercenary.task24]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task25] = {}
rwtTask[tKouDaiMercenary.task25]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["21_25"]]
rwtTask[tKouDaiMercenary.task25]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task25]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task25]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task25]["ReqCollectId1"] =  tCollect.Id2 
rwtTask[tKouDaiMercenary.task25]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task25]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task25]["AcceptDialogId"] = tDialog.nTask5_1
rwtTask[tKouDaiMercenary.task25]["DialogId"] = tDialog.nTask5_2
rwtTask[tKouDaiMercenary.task25]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task25]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task25]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task25]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task25]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task25]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task25]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task25]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task25]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id2 
rwtTask[tKouDaiMercenary.task25]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId2 
rwtTask[tKouDaiMercenary.task25]["AwardGroupId"] = 5
rwtTask[tKouDaiMercenary.task25]["TaskQuality"] = 5


----------------------------------珍奇宝矿-----------------------------------
rwtTask[tKouDaiMercenary.task26] = {}
rwtTask[tKouDaiMercenary.task26]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["26_30"]]
rwtTask[tKouDaiMercenary.task26]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task26]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task26]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task26]["ReqCollectId1"] =   tCollect.Id3 
rwtTask[tKouDaiMercenary.task26]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task26]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task26]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tKouDaiMercenary.task26]["DialogId"] = tDialog.nTask6_2
rwtTask[tKouDaiMercenary.task26]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task26]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task26]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task26]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task26]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task26]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task26]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task26]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task26]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id3 
rwtTask[tKouDaiMercenary.task26]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task26]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task26]["TaskQuality"] = 1


rwtTask[tKouDaiMercenary.task27] = {}
rwtTask[tKouDaiMercenary.task27]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["26_30"]]
rwtTask[tKouDaiMercenary.task27]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task27]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task27]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task27]["ReqCollectId1"] =   tCollect.Id3 
rwtTask[tKouDaiMercenary.task27]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task27]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task27]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tKouDaiMercenary.task27]["DialogId"] = tDialog.nTask6_2
rwtTask[tKouDaiMercenary.task27]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task27]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task27]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task27]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task27]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task27]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task27]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task27]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task27]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id3 
rwtTask[tKouDaiMercenary.task27]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task27]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task27]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task28] = {}
rwtTask[tKouDaiMercenary.task28]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["26_30"]]
rwtTask[tKouDaiMercenary.task28]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task28]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task28]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task28]["ReqCollectId1"] =   tCollect.Id3 
rwtTask[tKouDaiMercenary.task28]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task28]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task28]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tKouDaiMercenary.task28]["DialogId"] = tDialog.nTask6_2
rwtTask[tKouDaiMercenary.task28]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task28]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task28]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task28]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task28]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task28]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task28]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task28]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task28]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id3 
rwtTask[tKouDaiMercenary.task28]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task28]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task28]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task29] = {}
rwtTask[tKouDaiMercenary.task29]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["26_30"]]
rwtTask[tKouDaiMercenary.task29]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task29]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task29]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task29]["ReqCollectId1"] =   tCollect.Id3 
rwtTask[tKouDaiMercenary.task29]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task29]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task29]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tKouDaiMercenary.task29]["DialogId"] = tDialog.nTask6_2
rwtTask[tKouDaiMercenary.task29]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task29]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task29]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task29]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task29]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task29]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task29]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task29]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task29]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id3 
rwtTask[tKouDaiMercenary.task29]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task29]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task29]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task30] = {}
rwtTask[tKouDaiMercenary.task30]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["26_30"]]
rwtTask[tKouDaiMercenary.task30]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task30]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task30]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tKouDaiMercenary.task30]["ReqCollectId1"] =   tCollect.Id3 
rwtTask[tKouDaiMercenary.task30]["ReqCollectOnceNum"] = 1
rwtTask[tKouDaiMercenary.task30]["ReqCollectCount1"] =  1
rwtTask[tKouDaiMercenary.task30]["AcceptDialogId"] = tDialog.nTask6_1
rwtTask[tKouDaiMercenary.task30]["DialogId"] = tDialog.nTask6_2
rwtTask[tKouDaiMercenary.task30]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task30]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task30]["DynaNpcGroupGen"][1]["GenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task30]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task30]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task30]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task30]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tKouDaiMercenary.task30]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task30]["StartAutoWay"]["FindWayGroupId"] = tCollect.Id3 
rwtTask[tKouDaiMercenary.task30]["StartAutoWay"]["FindWayGenId"] = tCollect.GenId3 
rwtTask[tKouDaiMercenary.task30]["AwardGroupId"] = 1
rwtTask[tKouDaiMercenary.task30]["TaskQuality"] = 5

---------------------------------铲除余党-----------------------------------
rwtTask[tKouDaiMercenary.task31] = {}
rwtTask[tKouDaiMercenary.task31]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["31_35"]]
rwtTask[tKouDaiMercenary.task31]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task31]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task31]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task31]["KillMonsterGroup1"] =  tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task31]["MonsterGroupGenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task31]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tKouDaiMercenary.task31]["DialogId"] = tDialog.nTask7_2
rwtTask[tKouDaiMercenary.task31]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task31]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task31]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task31]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task31]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task31]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task31]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task31]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task31]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task31]["StartAutoWay"]["FindWayGenId"] =tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task31]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task31]["TaskQuality"] = 1


rwtTask[tKouDaiMercenary.task32] = {}
rwtTask[tKouDaiMercenary.task32]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["31_35"]]
rwtTask[tKouDaiMercenary.task32]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task32]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task32]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task32]["KillMonsterGroup1"] =  tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task32]["MonsterGroupGenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task32]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tKouDaiMercenary.task32]["DialogId"] = tDialog.nTask7_2
rwtTask[tKouDaiMercenary.task32]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task32]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task32]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task32]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task32]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task32]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task32]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task32]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task32]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task32]["StartAutoWay"]["FindWayGenId"] =tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task32]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task32]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task33] = {}
rwtTask[tKouDaiMercenary.task33]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["31_35"]]
rwtTask[tKouDaiMercenary.task33]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task33]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task33]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task33]["KillMonsterGroup1"] =  tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task33]["MonsterGroupGenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task33]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tKouDaiMercenary.task33]["DialogId"] = tDialog.nTask7_2
rwtTask[tKouDaiMercenary.task33]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task33]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task33]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task33]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task33]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task33]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task33]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task33]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task33]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task33]["StartAutoWay"]["FindWayGenId"] =tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task33]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task33]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task34] = {}
rwtTask[tKouDaiMercenary.task34]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["31_35"]]
rwtTask[tKouDaiMercenary.task34]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task34]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task34]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task34]["KillMonsterGroup1"] =  tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task34]["MonsterGroupGenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task34]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tKouDaiMercenary.task34]["DialogId"] = tDialog.nTask7_2
rwtTask[tKouDaiMercenary.task34]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task34]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task34]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task34]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task34]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task34]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task34]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task34]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task34]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task34]["StartAutoWay"]["FindWayGenId"] =tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task34]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task34]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task35] = {}
rwtTask[tKouDaiMercenary.task35]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["31_35"]]
rwtTask[tKouDaiMercenary.task35]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task35]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task35]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task35]["KillMonsterGroup1"] =  tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task35]["MonsterGroupGenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task35]["AcceptDialogId"] = tDialog.nTask7_1
rwtTask[tKouDaiMercenary.task35]["DialogId"] = tDialog.nTask7_2
rwtTask[tKouDaiMercenary.task35]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task35]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task35]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task35]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task35]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task35]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task35]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task35]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task35]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id1 
rwtTask[tKouDaiMercenary.task35]["StartAutoWay"]["FindWayGenId"] =tMonsterGroup.GenId1 
rwtTask[tKouDaiMercenary.task35]["AwardGroupId"] = 2
rwtTask[tKouDaiMercenary.task35]["TaskQuality"] = 5

------------------------打黑除恶-------------------------
rwtTask[tKouDaiMercenary.task36] = {}
rwtTask[tKouDaiMercenary.task36]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["36_40"]]
rwtTask[tKouDaiMercenary.task36]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task36]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task36]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task36]["KillMonsterGroup1"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task36]["MonsterGroupGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task36]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task36]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task36]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task36]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task36]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task36]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tKouDaiMercenary.task36]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task36]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task36]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task36]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task36]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task36]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task36]["TaskQuality"] = 1

rwtTask[tKouDaiMercenary.task37] = {}
rwtTask[tKouDaiMercenary.task37]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["36_40"]]
rwtTask[tKouDaiMercenary.task37]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task37]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task37]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task37]["KillMonsterGroup1"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task37]["MonsterGroupGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task37]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task37]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task37]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task37]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task37]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task37]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tKouDaiMercenary.task37]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task37]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task37]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task37]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task37]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task37]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task37]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task38] = {}
rwtTask[tKouDaiMercenary.task38]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["36_40"]]
rwtTask[tKouDaiMercenary.task38]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task38]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task38]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task38]["KillMonsterGroup1"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task38]["MonsterGroupGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task38]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task38]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task38]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task38]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task38]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task38]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tKouDaiMercenary.task38]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task38]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task38]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task38]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task38]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task38]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task38]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task39] = {}
rwtTask[tKouDaiMercenary.task39]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["36_40"]]
rwtTask[tKouDaiMercenary.task39]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task39]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task39]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task39]["KillMonsterGroup1"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task39]["MonsterGroupGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task39]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task39]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task39]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task39]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task39]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task39]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tKouDaiMercenary.task39]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task39]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task39]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task39]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task39]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task39]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task39]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task40] = {}
rwtTask[tKouDaiMercenary.task40]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["36_40"]]
rwtTask[tKouDaiMercenary.task40]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task40]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task40]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task40]["KillMonsterGroup1"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task40]["MonsterGroupGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task40]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task40]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task40]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task40]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task40]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task40]["AcceptDialogId"] = tDialog.nTask8_1
rwtTask[tKouDaiMercenary.task40]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task40]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task40]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task40]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id2
rwtTask[tKouDaiMercenary.task40]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId2
rwtTask[tKouDaiMercenary.task40]["AwardGroupId"] = 3
rwtTask[tKouDaiMercenary.task40]["TaskQuality"] = 5

-----------------------------机械狂乱---------------------------------------
rwtTask[tKouDaiMercenary.task41] = {}
rwtTask[tKouDaiMercenary.task41]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["41_45"]]
rwtTask[tKouDaiMercenary.task41]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task41]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task41]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task41]["KillMonsterGroup1"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task41]["MonsterGroupGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task41]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task41]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task41]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task41]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task41]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task41]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tKouDaiMercenary.task41]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task41]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task41]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task41]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task41]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task41]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task41]["TaskQuality"] = 1

rwtTask[tKouDaiMercenary.task42] = {}
rwtTask[tKouDaiMercenary.task42]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["41_45"]]
rwtTask[tKouDaiMercenary.task42]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task42]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task42]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task42]["KillMonsterGroup1"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task42]["MonsterGroupGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task42]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task42]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task42]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task42]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task42]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task42]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tKouDaiMercenary.task42]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task42]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task42]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task42]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task42]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task42]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task42]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task43] = {}
rwtTask[tKouDaiMercenary.task43]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["41_45"]]
rwtTask[tKouDaiMercenary.task43]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task43]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task43]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task43]["KillMonsterGroup1"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task43]["MonsterGroupGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task43]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task43]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task43]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task43]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task43]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task43]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tKouDaiMercenary.task43]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task43]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task43]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task43]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task43]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task43]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task43]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task44] = {}
rwtTask[tKouDaiMercenary.task44]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["41_45"]]
rwtTask[tKouDaiMercenary.task44]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task44]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task44]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task44]["KillMonsterGroup1"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task44]["MonsterGroupGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task44]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task44]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task44]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task44]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task44]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task44]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tKouDaiMercenary.task44]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task44]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task44]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task44]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task44]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task44]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task44]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task45] = {}
rwtTask[tKouDaiMercenary.task45]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["41_45"]]
rwtTask[tKouDaiMercenary.task45]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task45]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task45]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task45]["KillMonsterGroup1"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task45]["MonsterGroupGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task45]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task45]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task45]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task45]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task45]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task45]["AcceptDialogId"] = tDialog.nTask9_1
rwtTask[tKouDaiMercenary.task45]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task45]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task45]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task45]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id3
rwtTask[tKouDaiMercenary.task45]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId3 
rwtTask[tKouDaiMercenary.task45]["AwardGroupId"] = 4
rwtTask[tKouDaiMercenary.task45]["TaskQuality"] = 5

---------------------------------------联盟通缉令--------------------------------------
rwtTask[tKouDaiMercenary.task46] = {}
rwtTask[tKouDaiMercenary.task46]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["46_50"]]
rwtTask[tKouDaiMercenary.task46]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task46]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task46]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task46]["KillMonsterGroup1"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task46]["MonsterGroupGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task46]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tKouDaiMercenary.task46]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task46]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task46]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task46]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task46]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task46]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task46]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task46]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task46]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task46]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task46]["AwardGroupId"] = 6
rwtTask[tKouDaiMercenary.task46]["TaskQuality"] = 1

rwtTask[tKouDaiMercenary.task47] = {}
rwtTask[tKouDaiMercenary.task47]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["46_50"]]
rwtTask[tKouDaiMercenary.task47]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task47]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task47]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task47]["KillMonsterGroup1"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task47]["MonsterGroupGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task47]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tKouDaiMercenary.task47]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task47]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task47]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task47]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task47]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task47]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task47]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task47]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task47]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task47]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task47]["AwardGroupId"] = 6
rwtTask[tKouDaiMercenary.task47]["TaskQuality"] = 2

rwtTask[tKouDaiMercenary.task48] = {}
rwtTask[tKouDaiMercenary.task48]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["46_50"]]
rwtTask[tKouDaiMercenary.task48]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task48]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task48]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task48]["KillMonsterGroup1"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task48]["MonsterGroupGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task48]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tKouDaiMercenary.task48]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task48]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task48]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task48]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task48]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task48]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task48]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task48]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task48]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task48]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task48]["AwardGroupId"] = 6
rwtTask[tKouDaiMercenary.task48]["TaskQuality"] = 3

rwtTask[tKouDaiMercenary.task49] = {}
rwtTask[tKouDaiMercenary.task49]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["46_50"]]
rwtTask[tKouDaiMercenary.task49]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task49]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task49]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task49]["KillMonsterGroup1"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task49]["MonsterGroupGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task49]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tKouDaiMercenary.task49]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task49]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task49]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task49]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task49]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task49]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task49]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task49]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task49]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task49]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task49]["AwardGroupId"] = 6
rwtTask[tKouDaiMercenary.task49]["TaskQuality"] = 4

rwtTask[tKouDaiMercenary.task50] = {}
rwtTask[tKouDaiMercenary.task50]["Title"] = tLuaText[LANGUAGE_CONFIG][tTaskTitle["46_50"]]
rwtTask[tKouDaiMercenary.task50]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tKouDaiMercenary.task50]["MercenaryTownId"] = nTownId
rwtTask[tKouDaiMercenary.task50]["TaskDetailType"] =  CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tKouDaiMercenary.task50]["KillMonsterGroup1"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task50]["MonsterGroupGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task50]["AcceptDialogId"] = tDialog.nTask10_1
rwtTask[tKouDaiMercenary.task50]["DynaNpcGroupGen"] = {}
rwtTask[tKouDaiMercenary.task50]["DynaNpcGroupGen"][1] = {}
rwtTask[tKouDaiMercenary.task50]["DynaNpcGroupGen"][1]["GenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task50]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tKouDaiMercenary.task50]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tKouDaiMercenary.task50]["StartAutoWay"] = {}
rwtTask[tKouDaiMercenary.task50]["StartAutoWay"]["FindWayTypeId"] = 2
rwtTask[tKouDaiMercenary.task50]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tKouDaiMercenary.task50]["StartAutoWay"]["FindWayGroupId"] = tMonsterGroup.Id4 
rwtTask[tKouDaiMercenary.task50]["StartAutoWay"]["FindWayGenId"] = tMonsterGroup.GenId4
rwtTask[tKouDaiMercenary.task50]["AwardGroupId"] = 6
rwtTask[tKouDaiMercenary.task50]["TaskQuality"] = 5
