--region *.lua
--Date
--此文件由[BabeLua]插件自动生成
--阿克莱斯佣兵任务


--endregion
local tYongYeSenLinMercenary1 = {}         --转达情报
local tYongYeSenLinMercenary2 = {}         --木匠的订单
local tYongYeSenLinMercenary3 = {}         --篝火狂欢
local tYongYeSenLinMercenary4 = {}         --狂暴
local tYongYeSenLinMercenary5 = {}         --收集萤火熊骨
local tYongYeSenLinMercenary6 = {}         --惹事的萤火熊
local tYongYeSenLinMercenary7 = {}         --联盟通缉令
local tYongYeSenLinMercenary8 = {}         --了解银月湖奥秘
local tYongYeSenLinMercenary9 = {}         --采集辉夜魔晶
local tYongYeSenLinMercenary10 = {}        --驱赶狂化魔灵


tYongYeSenLinMercenary1.task1 =	20537	--转达情报
tYongYeSenLinMercenary1.task2 =	20538
tYongYeSenLinMercenary1.task3 =	20539
tYongYeSenLinMercenary1.task4 =	20540
tYongYeSenLinMercenary1.task5 =	20541

tYongYeSenLinMercenary2.task1 =	20542	--木匠的订单
tYongYeSenLinMercenary2.task2 =	20543
tYongYeSenLinMercenary2.task3 =	20544
tYongYeSenLinMercenary2.task4 =	20545
tYongYeSenLinMercenary2.task5 =	20546

tYongYeSenLinMercenary3.task1 =	20547	--篝火狂欢
tYongYeSenLinMercenary3.task2 =	20548	
tYongYeSenLinMercenary3.task3 =	20549	
tYongYeSenLinMercenary3.task4 =	20550	
tYongYeSenLinMercenary3.task5 =	20551	

tYongYeSenLinMercenary4.task1 =	20552	--狂暴
tYongYeSenLinMercenary4.task2 =	20553	
tYongYeSenLinMercenary4.task3 =	20554	
tYongYeSenLinMercenary4.task4 =	20555	
tYongYeSenLinMercenary4.task5 =	20556

tYongYeSenLinMercenary5.task1 =	20557	--收集萤火熊骨
tYongYeSenLinMercenary5.task2 =	20558	
tYongYeSenLinMercenary5.task3 =	20559	
tYongYeSenLinMercenary5.task4 =	20560
tYongYeSenLinMercenary5.task5 =	20561

tYongYeSenLinMercenary6.task1 =	20562	--惹事的萤火熊
tYongYeSenLinMercenary6.task2 =	20563	
tYongYeSenLinMercenary6.task3 =	20564
tYongYeSenLinMercenary6.task4 =	20565
tYongYeSenLinMercenary6.task5 =	20566

tYongYeSenLinMercenary7.task1 =	20567	--联盟通缉令
tYongYeSenLinMercenary7.task2 =	20568
tYongYeSenLinMercenary7.task3 =	20569
tYongYeSenLinMercenary7.task4 =	20570
tYongYeSenLinMercenary7.task5 =	20571

tYongYeSenLinMercenary8.task1 =	20662	--银月湖的成因
tYongYeSenLinMercenary8.task2 =	20663	
tYongYeSenLinMercenary8.task3 =	20664	
tYongYeSenLinMercenary8.task4 =	20665
tYongYeSenLinMercenary8.task5 =	20666

tYongYeSenLinMercenary9.task1 =	20667	--辉夜魔晶
tYongYeSenLinMercenary9.task2 =	20668	
tYongYeSenLinMercenary9.task3 =	20669
tYongYeSenLinMercenary9.task4 =	20670
tYongYeSenLinMercenary9.task5 =	20671

tYongYeSenLinMercenary10.task1 = 20672	--不安的永夜
tYongYeSenLinMercenary10.task2 = 20673
tYongYeSenLinMercenary10.task3 = 20674
tYongYeSenLinMercenary10.task4 = 20675
tYongYeSenLinMercenary10.task5 = 20676


------------------------------------------------------------------------------------
--怪物

local nMonsterGroup_1 = 900346
local nMonsterGroup_2 = 900347
local nMonsterGroup_3 = 900348
local nMonsterGroup_4 = 900349
local nMonsterGroup_5 = 900377

local nMonsterGroup_1_gen = 20030407      
local nMonsterGroup_2_gen = 20030408      
local nMonsterGroup_3_gen = 20030409      
local nMonsterGroup_4_gen = 20030410 
local nMonsterGroup_5_gen = 20030507       

--采集物

local nCollect_1 = 60229
local nCollect_1_gen = 20030406    
rwtNpcGroup[nCollect_1] = rwtNpcGroup[nCollect_1] or {}
rwtNpcGroup[nCollect_1]["Type"] = CONST_NPCGROUP_TYPE.Collect

local nCollect_2 = 60295
local nCollect_2_gen = 20030506    
rwtNpcGroup[nCollect_2] = rwtNpcGroup[nCollect_2] or {}
rwtNpcGroup[nCollect_2]["Type"] = CONST_NPCGROUP_TYPE.Collect
---------------------------------------------------------------------------------
-------------------------------------任务----------------------------------------
---------------------------------------------------------------------------------

rwtTask[tYongYeSenLinMercenary1.task1] = {}
rwtTask[tYongYeSenLinMercenary1.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21129]
rwtTask[tYongYeSenLinMercenary1.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary1.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary1.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary1.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary1.task1]["TaskNpc"] = 3164
rwtTask[tYongYeSenLinMercenary1.task1]["AcceptDialogId"] = 11363
rwtTask[tYongYeSenLinMercenary1.task1]["DialogId"] = 11364
rwtTask[tYongYeSenLinMercenary1.task1]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary1.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary1.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary1.task1]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary1.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary1.task1]["StartAutoWay"]["FindWayGroupId"] = 20206
rwtTask[tYongYeSenLinMercenary1.task1]["StartAutoWay"]["FindWayGenId"] =  20030157

rwtTask[tYongYeSenLinMercenary1.task2] = {}
rwtTask[tYongYeSenLinMercenary1.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21129]
rwtTask[tYongYeSenLinMercenary1.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary1.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary1.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary1.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary1.task2]["TaskNpc"] = 3164
rwtTask[tYongYeSenLinMercenary1.task2]["AcceptDialogId"] = 11363
rwtTask[tYongYeSenLinMercenary1.task2]["DialogId"] = 11364
rwtTask[tYongYeSenLinMercenary1.task2]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary1.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary1.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary1.task2]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary1.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary1.task2]["StartAutoWay"]["FindWayGroupId"] = 20206
rwtTask[tYongYeSenLinMercenary1.task2]["StartAutoWay"]["FindWayGenId"] =  20030157

rwtTask[tYongYeSenLinMercenary1.task3] = {}
rwtTask[tYongYeSenLinMercenary1.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21129]
rwtTask[tYongYeSenLinMercenary1.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary1.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary1.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary1.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary1.task3]["TaskNpc"] = 3164
rwtTask[tYongYeSenLinMercenary1.task3]["AcceptDialogId"] = 11363
rwtTask[tYongYeSenLinMercenary1.task3]["DialogId"] = 11364
rwtTask[tYongYeSenLinMercenary1.task3]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary1.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary1.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary1.task3]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary1.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary1.task3]["StartAutoWay"]["FindWayGroupId"] = 20206
rwtTask[tYongYeSenLinMercenary1.task3]["StartAutoWay"]["FindWayGenId"] =  20030157

rwtTask[tYongYeSenLinMercenary1.task4] = {}
rwtTask[tYongYeSenLinMercenary1.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21129]
rwtTask[tYongYeSenLinMercenary1.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary1.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary1.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary1.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary1.task4]["TaskNpc"] = 3164
rwtTask[tYongYeSenLinMercenary1.task4]["AcceptDialogId"] = 11363
rwtTask[tYongYeSenLinMercenary1.task4]["DialogId"] = 11364
rwtTask[tYongYeSenLinMercenary1.task4]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary1.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary1.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary1.task4]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary1.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary1.task4]["StartAutoWay"]["FindWayGroupId"] = 20206
rwtTask[tYongYeSenLinMercenary1.task4]["StartAutoWay"]["FindWayGenId"] =  20030157

rwtTask[tYongYeSenLinMercenary1.task5] = {}
rwtTask[tYongYeSenLinMercenary1.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21129]
rwtTask[tYongYeSenLinMercenary1.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary1.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary1.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary1.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary1.task5]["TaskNpc"] = 3164
rwtTask[tYongYeSenLinMercenary1.task5]["AcceptDialogId"] = 11363
rwtTask[tYongYeSenLinMercenary1.task5]["DialogId"] = 11364
rwtTask[tYongYeSenLinMercenary1.task5]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary1.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary1.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary1.task5]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary1.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary1.task5]["StartAutoWay"]["FindWayGroupId"] = 20206
rwtTask[tYongYeSenLinMercenary1.task5]["StartAutoWay"]["FindWayGenId"] =  20030157
---------------------------------------------------------------------------------

rwtTask[tYongYeSenLinMercenary2.task1] = {}
rwtTask[tYongYeSenLinMercenary2.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21130]
rwtTask[tYongYeSenLinMercenary2.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary2.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary2.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary2.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary2.task1]["TaskNpc"] = 3167
rwtTask[tYongYeSenLinMercenary2.task1]["AcceptDialogId"] = 11365
rwtTask[tYongYeSenLinMercenary2.task1]["DialogId"] = 11366
rwtTask[tYongYeSenLinMercenary2.task1]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary2.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary2.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary2.task1]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[tYongYeSenLinMercenary2.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary2.task1]["StartAutoWay"]["FindWayPos"] = "-160.86,0.09,-240.38"

rwtTask[tYongYeSenLinMercenary2.task2] = {}
rwtTask[tYongYeSenLinMercenary2.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21130]
rwtTask[tYongYeSenLinMercenary2.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary2.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary2.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary2.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary2.task2]["TaskNpc"] = 3167
rwtTask[tYongYeSenLinMercenary2.task2]["AcceptDialogId"] = 11365
rwtTask[tYongYeSenLinMercenary2.task2]["DialogId"] = 11366
rwtTask[tYongYeSenLinMercenary2.task2]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary2.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary2.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary2.task2]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[tYongYeSenLinMercenary2.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary2.task2]["StartAutoWay"]["FindWayPos"] = "-160.86,0.09,-240.38"

rwtTask[tYongYeSenLinMercenary2.task3] = {}
rwtTask[tYongYeSenLinMercenary2.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21130]
rwtTask[tYongYeSenLinMercenary2.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary2.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary2.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary2.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary2.task3]["TaskNpc"] = 3167
rwtTask[tYongYeSenLinMercenary2.task3]["AcceptDialogId"] = 11365
rwtTask[tYongYeSenLinMercenary2.task3]["DialogId"] = 11366
rwtTask[tYongYeSenLinMercenary2.task3]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary2.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary2.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary2.task3]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[tYongYeSenLinMercenary2.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary2.task3]["StartAutoWay"]["FindWayPos"] = "-160.86,0.09,-240.38"

rwtTask[tYongYeSenLinMercenary2.task4] = {}
rwtTask[tYongYeSenLinMercenary2.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21130]
rwtTask[tYongYeSenLinMercenary2.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary2.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary2.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary2.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary2.task4]["TaskNpc"] = 3167
rwtTask[tYongYeSenLinMercenary2.task4]["AcceptDialogId"] = 11365
rwtTask[tYongYeSenLinMercenary2.task4]["DialogId"] = 11366
rwtTask[tYongYeSenLinMercenary2.task4]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary2.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary2.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary2.task4]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[tYongYeSenLinMercenary2.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary2.task4]["StartAutoWay"]["FindWayPos"] = "-160.86,0.09,-240.38"

rwtTask[tYongYeSenLinMercenary2.task5] = {}
rwtTask[tYongYeSenLinMercenary2.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21130]
rwtTask[tYongYeSenLinMercenary2.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary2.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary2.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary2.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary2.task5]["TaskNpc"] = 3167
rwtTask[tYongYeSenLinMercenary2.task5]["AcceptDialogId"] = 11365
rwtTask[tYongYeSenLinMercenary2.task5]["DialogId"] = 11366
rwtTask[tYongYeSenLinMercenary2.task5]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary2.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary2.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary2.task5]["StartAutoWay"]["FindWayTypeId"]= 0
rwtTask[tYongYeSenLinMercenary2.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary2.task5]["StartAutoWay"]["FindWayPos"] = "-160.86,0.09,-240.38"

---------------------------------------------------------------------------------
rwtTask[tYongYeSenLinMercenary3.task1] = {}
rwtTask[tYongYeSenLinMercenary3.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21131]
rwtTask[tYongYeSenLinMercenary3.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary3.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary3.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary3.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tYongYeSenLinMercenary3.task1]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary3.task1]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary3.task1]["DynaNpcGroupGen"][1]["GenId"] = nCollect_1_gen
rwtTask[tYongYeSenLinMercenary3.task1]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary3.task1]["AcceptDialogId"] = 11367
rwtTask[tYongYeSenLinMercenary3.task1]["DialogId"] = 11368
rwtTask[tYongYeSenLinMercenary3.task1]["ReqCollectId1"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task1]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary3.task1]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary3.task1]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary3.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary3.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary3.task1]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary3.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task1]["StartAutoWay"]["FindWayGroupId"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task1]["StartAutoWay"]["FindWayGenId"] =  nCollect_1_gen

rwtTask[tYongYeSenLinMercenary3.task2] = {}
rwtTask[tYongYeSenLinMercenary3.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21131]
rwtTask[tYongYeSenLinMercenary3.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary3.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary3.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary3.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tYongYeSenLinMercenary3.task2]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary3.task2]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary3.task2]["DynaNpcGroupGen"][1]["GenId"] = nCollect_1_gen
rwtTask[tYongYeSenLinMercenary3.task2]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary3.task2]["AcceptDialogId"] = 11367
rwtTask[tYongYeSenLinMercenary3.task2]["DialogId"] = 11368
rwtTask[tYongYeSenLinMercenary3.task2]["ReqCollectId1"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task2]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary3.task2]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary3.task2]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary3.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary3.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary3.task2]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary3.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task2]["StartAutoWay"]["FindWayGroupId"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task2]["StartAutoWay"]["FindWayGenId"] =  nCollect_1_gen


rwtTask[tYongYeSenLinMercenary3.task3] = {}
rwtTask[tYongYeSenLinMercenary3.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21131]
rwtTask[tYongYeSenLinMercenary3.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary3.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary3.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary3.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tYongYeSenLinMercenary3.task3]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary3.task3]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary3.task3]["DynaNpcGroupGen"][1]["GenId"] = nCollect_1_gen
rwtTask[tYongYeSenLinMercenary3.task3]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary3.task3]["AcceptDialogId"] = 11367
rwtTask[tYongYeSenLinMercenary3.task3]["DialogId"] = 11368
rwtTask[tYongYeSenLinMercenary3.task3]["ReqCollectId1"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task3]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary3.task3]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary3.task3]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary3.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary3.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary3.task3]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary3.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task3]["StartAutoWay"]["FindWayGroupId"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task3]["StartAutoWay"]["FindWayGenId"] =  nCollect_1_gen

rwtTask[tYongYeSenLinMercenary3.task4] = {}
rwtTask[tYongYeSenLinMercenary3.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21131]
rwtTask[tYongYeSenLinMercenary3.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary3.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary3.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary3.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tYongYeSenLinMercenary3.task4]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary3.task4]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary3.task4]["DynaNpcGroupGen"][1]["GenId"] = nCollect_1_gen
rwtTask[tYongYeSenLinMercenary3.task4]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary3.task4]["AcceptDialogId"] = 11367
rwtTask[tYongYeSenLinMercenary3.task4]["DialogId"] = 11368
rwtTask[tYongYeSenLinMercenary3.task4]["ReqCollectId1"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task4]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary3.task4]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary3.task4]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary3.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary3.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary3.task4]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary3.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task4]["StartAutoWay"]["FindWayGroupId"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task4]["StartAutoWay"]["FindWayGenId"] =  nCollect_1_gen

rwtTask[tYongYeSenLinMercenary3.task5] = {}
rwtTask[tYongYeSenLinMercenary3.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21131]
rwtTask[tYongYeSenLinMercenary3.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary3.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary3.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary3.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_COLLECT
rwtTask[tYongYeSenLinMercenary3.task5]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary3.task5]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary3.task5]["DynaNpcGroupGen"][1]["GenId"] = nCollect_1_gen
rwtTask[tYongYeSenLinMercenary3.task5]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary3.task5]["AcceptDialogId"] = 11367
rwtTask[tYongYeSenLinMercenary3.task5]["DialogId"] = 11368
rwtTask[tYongYeSenLinMercenary3.task5]["ReqCollectId1"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task5]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary3.task5]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary3.task5]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary3.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary3.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary3.task5]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary3.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary3.task5]["StartAutoWay"]["FindWayGroupId"] = nCollect_1
rwtTask[tYongYeSenLinMercenary3.task5]["StartAutoWay"]["FindWayGenId"] =  nCollect_1_gen

----------------------------------------------------------------------------------------------------

rwtTask[tYongYeSenLinMercenary4.task1] = {}
rwtTask[tYongYeSenLinMercenary4.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21132]
rwtTask[tYongYeSenLinMercenary4.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary4.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary4.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary4.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary4.task1]["AcceptDialogId"] = 11369
rwtTask[tYongYeSenLinMercenary4.task1]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary4.task1]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary4.task1]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_1_gen
rwtTask[tYongYeSenLinMercenary4.task1]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary4.task1]["KillMonsterGroup1"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task1]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary4.task1]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary4.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary4.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary4.task1]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary4.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task1]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task1]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_1_gen


rwtTask[tYongYeSenLinMercenary4.task2] = {}
rwtTask[tYongYeSenLinMercenary4.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21132]
rwtTask[tYongYeSenLinMercenary4.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary4.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary4.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary4.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary4.task2]["AcceptDialogId"] = 11369
rwtTask[tYongYeSenLinMercenary4.task2]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary4.task2]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary4.task2]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_1_gen
rwtTask[tYongYeSenLinMercenary4.task2]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary4.task2]["KillMonsterGroup1"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task2]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary4.task2]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary4.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary4.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary4.task2]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary4.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task2]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task2]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_1_gen


rwtTask[tYongYeSenLinMercenary4.task3] = {}
rwtTask[tYongYeSenLinMercenary4.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21132]
rwtTask[tYongYeSenLinMercenary4.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary4.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary4.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary4.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary4.task3]["AcceptDialogId"] = 11369
rwtTask[tYongYeSenLinMercenary4.task3]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary4.task3]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary4.task3]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_1_gen
rwtTask[tYongYeSenLinMercenary4.task3]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary4.task3]["KillMonsterGroup1"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task3]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary4.task3]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary4.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary4.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary4.task3]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary4.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task3]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task3]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_1_gen


rwtTask[tYongYeSenLinMercenary4.task4] = {}
rwtTask[tYongYeSenLinMercenary4.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21132]
rwtTask[tYongYeSenLinMercenary4.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary4.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary4.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary4.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary4.task4]["AcceptDialogId"] = 11369
rwtTask[tYongYeSenLinMercenary4.task4]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary4.task4]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary4.task4]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_1_gen
rwtTask[tYongYeSenLinMercenary4.task4]["DynaNpcGroupGen"][1]["MapId"] = 2001
rwtTask[tYongYeSenLinMercenary4.task4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary4.task4]["KillMonsterGroup1"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task4]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary4.task4]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary4.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary4.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary4.task4]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary4.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task4]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task4]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_1_gen

rwtTask[tYongYeSenLinMercenary4.task5] = {}
rwtTask[tYongYeSenLinMercenary4.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21132]
rwtTask[tYongYeSenLinMercenary4.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary4.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary4.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary4.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary4.task5]["AcceptDialogId"] = 11369
rwtTask[tYongYeSenLinMercenary4.task5]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary4.task5]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary4.task5]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_1_gen
rwtTask[tYongYeSenLinMercenary4.task5]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary4.task5]["KillMonsterGroup1"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task5]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary4.task5]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary4.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary4.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary4.task5]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary4.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary4.task5]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_1
rwtTask[tYongYeSenLinMercenary4.task5]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_1_gen

-----------------------------------------------------------------------------------------------------------
rwtTask[tYongYeSenLinMercenary5.task1] = {}
rwtTask[tYongYeSenLinMercenary5.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21133]
rwtTask[tYongYeSenLinMercenary5.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary5.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary5.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary5.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary5.task1]["AcceptDialogId"] = 11371
rwtTask[tYongYeSenLinMercenary5.task1]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary5.task1]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary5.task1]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_2_gen
rwtTask[tYongYeSenLinMercenary5.task1]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary5.task1]["KillMonsterGroup1"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task1]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary5.task1]["AwardGroupId"] = 5
rwtTask[tYongYeSenLinMercenary5.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary5.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary5.task1]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary5.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task1]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task1]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_2_gen

rwtTask[tYongYeSenLinMercenary5.task2] = {}
rwtTask[tYongYeSenLinMercenary5.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21133]
rwtTask[tYongYeSenLinMercenary5.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary5.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary5.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary5.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary5.task2]["AcceptDialogId"] = 11371
rwtTask[tYongYeSenLinMercenary5.task2]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary5.task2]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary5.task2]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_2_gen
rwtTask[tYongYeSenLinMercenary5.task2]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary5.task2]["KillMonsterGroup1"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task2]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary5.task2]["AwardGroupId"] = 5
rwtTask[tYongYeSenLinMercenary5.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary5.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary5.task2]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary5.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task2]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task2]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_2_gen

rwtTask[tYongYeSenLinMercenary5.task3] = {}
rwtTask[tYongYeSenLinMercenary5.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21133]
rwtTask[tYongYeSenLinMercenary5.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary5.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary5.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary5.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary5.task3]["AcceptDialogId"] = 11371
rwtTask[tYongYeSenLinMercenary5.task3]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary5.task3]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary5.task3]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_2_gen
rwtTask[tYongYeSenLinMercenary5.task3]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary5.task3]["KillMonsterGroup1"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task3]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary5.task3]["AwardGroupId"] = 5
rwtTask[tYongYeSenLinMercenary5.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary5.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary5.task3]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary5.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task3]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task3]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_2_gen

rwtTask[tYongYeSenLinMercenary5.task4] = {}
rwtTask[tYongYeSenLinMercenary5.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21133]
rwtTask[tYongYeSenLinMercenary5.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary5.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary5.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary5.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary5.task4]["AcceptDialogId"] = 11371
rwtTask[tYongYeSenLinMercenary5.task4]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary5.task4]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary5.task4]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_2_gen
rwtTask[tYongYeSenLinMercenary5.task4]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary5.task4]["KillMonsterGroup1"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task4]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary5.task4]["AwardGroupId"] = 5
rwtTask[tYongYeSenLinMercenary5.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary5.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary5.task4]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary5.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task4]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task4]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_2_gen

rwtTask[tYongYeSenLinMercenary5.task5] = {}
rwtTask[tYongYeSenLinMercenary5.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21133]
rwtTask[tYongYeSenLinMercenary5.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary5.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary5.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary5.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary5.task5]["AcceptDialogId"] = 11371
rwtTask[tYongYeSenLinMercenary5.task5]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary5.task5]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary5.task5]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_2_gen
rwtTask[tYongYeSenLinMercenary5.task5]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary5.task5]["KillMonsterGroup1"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task5]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary5.task5]["AwardGroupId"] = 5
rwtTask[tYongYeSenLinMercenary5.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary5.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary5.task5]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary5.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary5.task5]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_2
rwtTask[tYongYeSenLinMercenary5.task5]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_2_gen

--------------------------------------------------------------------------------------------------------
rwtTask[tYongYeSenLinMercenary6.task1] = {}
rwtTask[tYongYeSenLinMercenary6.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21134]
rwtTask[tYongYeSenLinMercenary6.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary6.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary6.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary6.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary6.task1]["AcceptDialogId"] = 11374
rwtTask[tYongYeSenLinMercenary6.task1]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary6.task1]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary6.task1]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_3_gen
rwtTask[tYongYeSenLinMercenary6.task1]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary6.task1]["KillMonsterGroup1"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task1]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary6.task1]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary6.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary6.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary6.task1]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary6.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task1]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task1]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_3_gen

rwtTask[tYongYeSenLinMercenary6.task2] = {}
rwtTask[tYongYeSenLinMercenary6.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21134]
rwtTask[tYongYeSenLinMercenary6.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary6.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary6.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary6.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary6.task2]["AcceptDialogId"] = 11374
rwtTask[tYongYeSenLinMercenary6.task2]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary6.task2]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary6.task2]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_3_gen
rwtTask[tYongYeSenLinMercenary6.task2]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary6.task2]["KillMonsterGroup1"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task2]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary6.task2]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary6.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary6.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary6.task2]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary6.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task2]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task2]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_3_gen

rwtTask[tYongYeSenLinMercenary6.task3] = {}
rwtTask[tYongYeSenLinMercenary6.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21134]
rwtTask[tYongYeSenLinMercenary6.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary6.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary6.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary6.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary6.task3]["AcceptDialogId"] = 11374
rwtTask[tYongYeSenLinMercenary6.task3]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary6.task3]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary6.task3]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_3_gen
rwtTask[tYongYeSenLinMercenary6.task3]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary6.task3]["KillMonsterGroup1"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task3]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary6.task3]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary6.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary6.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary6.task3]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary6.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task3]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task3]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_3_gen

rwtTask[tYongYeSenLinMercenary6.task4] = {}
rwtTask[tYongYeSenLinMercenary6.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21134]
rwtTask[tYongYeSenLinMercenary6.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary6.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary6.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary6.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary6.task4]["AcceptDialogId"] = 11374
rwtTask[tYongYeSenLinMercenary6.task4]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary6.task4]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary6.task4]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_3_gen
rwtTask[tYongYeSenLinMercenary6.task4]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary6.task4]["KillMonsterGroup1"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task4]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary6.task4]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary6.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary6.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary6.task4]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary6.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task4]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task4]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_3_gen

rwtTask[tYongYeSenLinMercenary6.task5] = {}
rwtTask[tYongYeSenLinMercenary6.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21134]
rwtTask[tYongYeSenLinMercenary6.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary6.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary6.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary6.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary6.task5]["AcceptDialogId"] = 11374
rwtTask[tYongYeSenLinMercenary6.task5]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary6.task5]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary6.task5]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_3_gen
rwtTask[tYongYeSenLinMercenary6.task5]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary6.task5]["KillMonsterGroup1"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task5]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary6.task5]["AwardGroupId"] = 1
rwtTask[tYongYeSenLinMercenary6.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary6.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary6.task5]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary6.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary6.task5]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_3
rwtTask[tYongYeSenLinMercenary6.task5]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_3_gen
----------------------------------------------------------------------------------------------------------
rwtTask[tYongYeSenLinMercenary7.task1] = {}
rwtTask[tYongYeSenLinMercenary7.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21135]
rwtTask[tYongYeSenLinMercenary7.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary7.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary7.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary7.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary7.task1]["AcceptDialogId"] = 11376
rwtTask[tYongYeSenLinMercenary7.task1]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary7.task1]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary7.task1]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_4_gen
rwtTask[tYongYeSenLinMercenary7.task1]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary7.task1]["KillMonsterGroup1"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task1]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary7.task1]["AwardGroupId"] = 6
rwtTask[tYongYeSenLinMercenary7.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary7.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary7.task1]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary7.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task1]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task1]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_4_gen

rwtTask[tYongYeSenLinMercenary7.task2] = {}
rwtTask[tYongYeSenLinMercenary7.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21135]
rwtTask[tYongYeSenLinMercenary7.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary7.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary7.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary7.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary7.task2]["AcceptDialogId"] = 11376
rwtTask[tYongYeSenLinMercenary7.task2]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary7.task2]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary7.task2]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_4_gen
rwtTask[tYongYeSenLinMercenary7.task2]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary7.task2]["KillMonsterGroup1"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task2]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary7.task2]["AwardGroupId"] = 6
rwtTask[tYongYeSenLinMercenary7.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary7.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary7.task2]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary7.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task2]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task2]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_4_gen

rwtTask[tYongYeSenLinMercenary7.task3] = {}
rwtTask[tYongYeSenLinMercenary7.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21135]
rwtTask[tYongYeSenLinMercenary7.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary7.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary7.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary7.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary7.task3]["AcceptDialogId"] = 11376
rwtTask[tYongYeSenLinMercenary7.task3]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary7.task3]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary7.task3]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_4_gen
rwtTask[tYongYeSenLinMercenary7.task3]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary7.task3]["KillMonsterGroup1"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task3]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary7.task3]["AwardGroupId"] = 6
rwtTask[tYongYeSenLinMercenary7.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary7.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary7.task3]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary7.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task3]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task3]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_4_gen

rwtTask[tYongYeSenLinMercenary7.task4] = {}
rwtTask[tYongYeSenLinMercenary7.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21135]
rwtTask[tYongYeSenLinMercenary7.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary7.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary7.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary7.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary7.task4]["AcceptDialogId"] = 11376
rwtTask[tYongYeSenLinMercenary7.task4]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary7.task4]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary7.task4]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_4_gen
rwtTask[tYongYeSenLinMercenary7.task4]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary7.task4]["KillMonsterGroup1"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task4]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary7.task4]["AwardGroupId"] = 6
rwtTask[tYongYeSenLinMercenary7.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary7.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary7.task4]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary7.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task4]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task4]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_4_gen

rwtTask[tYongYeSenLinMercenary7.task5] = {}
rwtTask[tYongYeSenLinMercenary7.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21135]
rwtTask[tYongYeSenLinMercenary7.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary7.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary7.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary7.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary7.task5]["AcceptDialogId"] = 11376
rwtTask[tYongYeSenLinMercenary7.task5]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary7.task5]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary7.task5]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_4_gen
rwtTask[tYongYeSenLinMercenary7.task5]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary7.task5]["KillMonsterGroup1"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task5]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary7.task5]["AwardGroupId"] = 6
rwtTask[tYongYeSenLinMercenary7.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary7.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary7.task5]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary7.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary7.task5]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_4
rwtTask[tYongYeSenLinMercenary7.task5]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_4_gen

-------------------------------------------------------------------------------------------------
rwtTask[tYongYeSenLinMercenary8.task1] = {}
rwtTask[tYongYeSenLinMercenary8.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21352]
rwtTask[tYongYeSenLinMercenary8.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary8.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary8.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary8.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary8.task1]["TaskNpc"] = 3455
rwtTask[tYongYeSenLinMercenary8.task1]["AcceptDialogId"] = 11600
rwtTask[tYongYeSenLinMercenary8.task1]["DialogId"] = 11604
rwtTask[tYongYeSenLinMercenary8.task1]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary8.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary8.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary8.task1]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary8.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary8.task1]["StartAutoWay"]["FindWayGroupId"] = 70009
rwtTask[tYongYeSenLinMercenary8.task1]["StartAutoWay"]["FindWayGenId"] =  20030477

rwtTask[tYongYeSenLinMercenary8.task2] = {}
rwtTask[tYongYeSenLinMercenary8.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21352]
rwtTask[tYongYeSenLinMercenary8.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary8.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary8.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary8.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary8.task2]["TaskNpc"] = 3455
rwtTask[tYongYeSenLinMercenary8.task2]["AcceptDialogId"] = 11600
rwtTask[tYongYeSenLinMercenary8.task2]["DialogId"] = 11604
rwtTask[tYongYeSenLinMercenary8.task2]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary8.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary8.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary8.task2]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary8.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary8.task2]["StartAutoWay"]["FindWayGroupId"] = 70009
rwtTask[tYongYeSenLinMercenary8.task2]["StartAutoWay"]["FindWayGenId"] =  20030477

rwtTask[tYongYeSenLinMercenary8.task3] = {}
rwtTask[tYongYeSenLinMercenary8.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21352]
rwtTask[tYongYeSenLinMercenary8.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary8.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary8.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary8.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary8.task3]["TaskNpc"] = 3455
rwtTask[tYongYeSenLinMercenary8.task3]["AcceptDialogId"] = 11600
rwtTask[tYongYeSenLinMercenary8.task3]["DialogId"] = 11604
rwtTask[tYongYeSenLinMercenary8.task3]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary8.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary8.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary8.task3]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary8.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary8.task3]["StartAutoWay"]["FindWayGroupId"] = 70009
rwtTask[tYongYeSenLinMercenary8.task3]["StartAutoWay"]["FindWayGenId"] =  20030477

rwtTask[tYongYeSenLinMercenary8.task4] = {}
rwtTask[tYongYeSenLinMercenary8.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21352]
rwtTask[tYongYeSenLinMercenary8.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary8.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary8.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary8.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary8.task4]["TaskNpc"] = 3455
rwtTask[tYongYeSenLinMercenary8.task4]["AcceptDialogId"] = 11600
rwtTask[tYongYeSenLinMercenary8.task4]["DialogId"] = 11604
rwtTask[tYongYeSenLinMercenary8.task4]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary8.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary8.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary8.task4]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary8.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary8.task4]["StartAutoWay"]["FindWayGroupId"] = 70009
rwtTask[tYongYeSenLinMercenary8.task4]["StartAutoWay"]["FindWayGenId"] =  20030477

rwtTask[tYongYeSenLinMercenary8.task5] = {}
rwtTask[tYongYeSenLinMercenary8.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21352]
rwtTask[tYongYeSenLinMercenary8.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary8.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary8.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary8.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tYongYeSenLinMercenary8.task5]["TaskNpc"] = 3455
rwtTask[tYongYeSenLinMercenary8.task5]["AcceptDialogId"] = 11600
rwtTask[tYongYeSenLinMercenary8.task5]["DialogId"] = 11604
rwtTask[tYongYeSenLinMercenary8.task5]["AwardGroupId"] = 2
rwtTask[tYongYeSenLinMercenary8.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary8.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary8.task5]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary8.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary8.task5]["StartAutoWay"]["FindWayGroupId"] = 70009
rwtTask[tYongYeSenLinMercenary8.task5]["StartAutoWay"]["FindWayGenId"] =  20030477

--------------------------------------------------------------------------------------------------
rwtTask[tYongYeSenLinMercenary9.task1] = {}
rwtTask[tYongYeSenLinMercenary9.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21353]
rwtTask[tYongYeSenLinMercenary9.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary9.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary9.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary9.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tYongYeSenLinMercenary9.task1]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary9.task1]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary9.task1]["DynaNpcGroupGen"][1]["GenId"] = nCollect_2_gen
rwtTask[tYongYeSenLinMercenary9.task1]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary9.task1]["AcceptDialogId"] = 11601
--rwtTask[tYongYeSenLinMercenary9.task1]["DialogId"] = 10603
rwtTask[tYongYeSenLinMercenary9.task1]["ReqCollectId1"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task1]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary9.task1]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary9.task1]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary9.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary9.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary9.task1]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary9.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task1]["StartAutoWay"]["FindWayGroupId"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task1]["StartAutoWay"]["FindWayGenId"] =  nCollect_2_gen

rwtTask[tYongYeSenLinMercenary9.task2] = {}
rwtTask[tYongYeSenLinMercenary9.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21353]
rwtTask[tYongYeSenLinMercenary9.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary9.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary9.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary9.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tYongYeSenLinMercenary9.task2]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary9.task2]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary9.task2]["DynaNpcGroupGen"][1]["GenId"] = nCollect_2_gen
rwtTask[tYongYeSenLinMercenary9.task2]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary9.task2]["AcceptDialogId"] = 11601
--rwtTask[tYongYeSenLinMercenary9.task2]["DialogId"] = 10603
rwtTask[tYongYeSenLinMercenary9.task2]["ReqCollectId1"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task2]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary9.task2]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary9.task2]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary9.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary9.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary9.task2]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary9.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task2]["StartAutoWay"]["FindWayGroupId"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task2]["StartAutoWay"]["FindWayGenId"] =  nCollect_2_gen

rwtTask[tYongYeSenLinMercenary9.task3] = {}
rwtTask[tYongYeSenLinMercenary9.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21353]
rwtTask[tYongYeSenLinMercenary9.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary9.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary9.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary9.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tYongYeSenLinMercenary9.task3]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary9.task3]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary9.task3]["DynaNpcGroupGen"][1]["GenId"] = nCollect_2_gen
rwtTask[tYongYeSenLinMercenary9.task3]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary9.task3]["AcceptDialogId"] = 11601
--rwtTask[tYongYeSenLinMercenary9.task3]["DialogId"] = 10603
rwtTask[tYongYeSenLinMercenary9.task3]["ReqCollectId1"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task3]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary9.task3]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary9.task3]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary9.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary9.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary9.task3]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary9.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task3]["StartAutoWay"]["FindWayGroupId"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task3]["StartAutoWay"]["FindWayGenId"] =  nCollect_2_gen

rwtTask[tYongYeSenLinMercenary9.task4] = {}
rwtTask[tYongYeSenLinMercenary9.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21353]
rwtTask[tYongYeSenLinMercenary9.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary9.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary9.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary9.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tYongYeSenLinMercenary9.task4]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary9.task4]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary9.task4]["DynaNpcGroupGen"][1]["GenId"] = nCollect_2_gen
rwtTask[tYongYeSenLinMercenary9.task4]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary9.task4]["AcceptDialogId"] = 11601
--rwtTask[tYongYeSenLinMercenary9.task4]["DialogId"] = 10603
rwtTask[tYongYeSenLinMercenary9.task4]["ReqCollectId1"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task4]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary9.task4]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary9.task4]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary9.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary9.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary9.task4]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary9.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task4]["StartAutoWay"]["FindWayGroupId"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task4]["StartAutoWay"]["FindWayGenId"] =  nCollect_2_gen

rwtTask[tYongYeSenLinMercenary9.task5] = {}
rwtTask[tYongYeSenLinMercenary9.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21353]
rwtTask[tYongYeSenLinMercenary9.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary9.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary9.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary9.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.COLLECT
rwtTask[tYongYeSenLinMercenary9.task5]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary9.task5]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary9.task5]["DynaNpcGroupGen"][1]["GenId"] = nCollect_2_gen
rwtTask[tYongYeSenLinMercenary9.task5]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary9.task5]["AcceptDialogId"] = 11601
--rwtTask[tYongYeSenLinMercenary9.task5]["DialogId"] = 10603
rwtTask[tYongYeSenLinMercenary9.task5]["ReqCollectId1"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task5]["ReqCollectCount1"] = 1
rwtTask[tYongYeSenLinMercenary9.task5]["ReqCollectOnceNum"] = 1
rwtTask[tYongYeSenLinMercenary9.task5]["AwardGroupId"] = 3
rwtTask[tYongYeSenLinMercenary9.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary9.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary9.task5]["StartAutoWay"]["FindWayTypeId"]= 1
rwtTask[tYongYeSenLinMercenary9.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary9.task5]["StartAutoWay"]["FindWayGroupId"] = nCollect_2
rwtTask[tYongYeSenLinMercenary9.task5]["StartAutoWay"]["FindWayGenId"] =  nCollect_2_gen

---------------------------------------------------------------------------------------------
rwtTask[tYongYeSenLinMercenary10.task1] = {}
rwtTask[tYongYeSenLinMercenary10.task1]["Title"] = tLuaText[LANGUAGE_CONFIG][21354]
rwtTask[tYongYeSenLinMercenary10.task1]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary10.task1]["TaskQuality"] = 1
rwtTask[tYongYeSenLinMercenary10.task1]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary10.task1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary10.task1]["AcceptDialogId"] = 11602
rwtTask[tYongYeSenLinMercenary10.task1]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary10.task1]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary10.task1]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_5_gen
rwtTask[tYongYeSenLinMercenary10.task1]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary10.task1]["KillMonsterGroup1"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task1]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary10.task1]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary10.task1]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary10.task1]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary10.task1]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary10.task1]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task1]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task1]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_5_gen

rwtTask[tYongYeSenLinMercenary10.task2] = {}
rwtTask[tYongYeSenLinMercenary10.task2]["Title"] = tLuaText[LANGUAGE_CONFIG][21354]
rwtTask[tYongYeSenLinMercenary10.task2]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary10.task2]["TaskQuality"] = 2
rwtTask[tYongYeSenLinMercenary10.task2]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary10.task2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary10.task2]["AcceptDialogId"] = 11602
rwtTask[tYongYeSenLinMercenary10.task2]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary10.task2]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary10.task2]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_5_gen
rwtTask[tYongYeSenLinMercenary10.task2]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary10.task2]["KillMonsterGroup1"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task2]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary10.task2]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary10.task2]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary10.task2]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary10.task2]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary10.task2]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task2]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task2]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_5_gen

rwtTask[tYongYeSenLinMercenary10.task3] = {}
rwtTask[tYongYeSenLinMercenary10.task3]["Title"] = tLuaText[LANGUAGE_CONFIG][21354]
rwtTask[tYongYeSenLinMercenary10.task3]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary10.task3]["TaskQuality"] = 3
rwtTask[tYongYeSenLinMercenary10.task3]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary10.task3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary10.task3]["AcceptDialogId"] = 11602
rwtTask[tYongYeSenLinMercenary10.task3]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary10.task3]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary10.task3]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_5_gen
rwtTask[tYongYeSenLinMercenary10.task3]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary10.task3]["KillMonsterGroup1"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task3]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary10.task3]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary10.task3]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary10.task3]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary10.task3]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary10.task3]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task3]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task3]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_5_gen

rwtTask[tYongYeSenLinMercenary10.task4] = {}
rwtTask[tYongYeSenLinMercenary10.task4]["Title"] = tLuaText[LANGUAGE_CONFIG][21354]
rwtTask[tYongYeSenLinMercenary10.task4]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary10.task4]["TaskQuality"] = 4
rwtTask[tYongYeSenLinMercenary10.task4]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary10.task4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary10.task4]["AcceptDialogId"] = 11602
rwtTask[tYongYeSenLinMercenary10.task4]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary10.task4]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary10.task4]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_5_gen
rwtTask[tYongYeSenLinMercenary10.task4]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task4]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary10.task4]["KillMonsterGroup1"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task4]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary10.task4]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary10.task4]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary10.task4]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary10.task4]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary10.task4]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task4]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task4]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_5_gen

rwtTask[tYongYeSenLinMercenary10.task5] = {}
rwtTask[tYongYeSenLinMercenary10.task5]["Title"] = tLuaText[LANGUAGE_CONFIG][21354]
rwtTask[tYongYeSenLinMercenary10.task5]["TaskType"] = CONST_TASK_TYPE.MERCENARY
rwtTask[tYongYeSenLinMercenary10.task5]["TaskQuality"] = 5
rwtTask[tYongYeSenLinMercenary10.task5]["MercenaryTownId"] = 200304
rwtTask[tYongYeSenLinMercenary10.task5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.KILLMONSTER
rwtTask[tYongYeSenLinMercenary10.task5]["AcceptDialogId"] = 11602
rwtTask[tYongYeSenLinMercenary10.task5]["DynaNpcGroupGen"] = {}
rwtTask[tYongYeSenLinMercenary10.task5]["DynaNpcGroupGen"][1] = {}
rwtTask[tYongYeSenLinMercenary10.task5]["DynaNpcGroupGen"][1]["GenId"] = nMonsterGroup_5_gen
rwtTask[tYongYeSenLinMercenary10.task5]["DynaNpcGroupGen"][1]["MapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task5]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tYongYeSenLinMercenary10.task5]["KillMonsterGroup1"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task5]["KillMonsterGroupCount1"]= 1
rwtTask[tYongYeSenLinMercenary10.task5]["AwardGroupId"] = 4
rwtTask[tYongYeSenLinMercenary10.task5]["IsClickComplete"] = 0
rwtTask[tYongYeSenLinMercenary10.task5]["StartAutoWay"] = {}
rwtTask[tYongYeSenLinMercenary10.task5]["StartAutoWay"]["FindWayTypeId"]= 2
rwtTask[tYongYeSenLinMercenary10.task5]["StartAutoWay"]["FindWayMapId"] = 2003
rwtTask[tYongYeSenLinMercenary10.task5]["StartAutoWay"]["FindWayGroupId"] = nMonsterGroup_5
rwtTask[tYongYeSenLinMercenary10.task5]["StartAutoWay"]["FindWayGenId"] =  nMonsterGroup_5_gen