--region *.lua
--Date
--此文件由[BabeLua]插件自动生成



--endregion
local nMapId = 2001

local tQSTask_HuPan = {}
tQSTask_HuPan.Normal_1 = 90093
tQSTask_HuPan.Normal_2 = 90094
tQSTask_HuPan.Normal_3 = 90095
tQSTask_HuPan.Normal_4 = 90096
tQSTask_HuPan.Normal_5 = 90097
tQSTask_HuPan.Normal_6 = 90098
tQSTask_HuPan.Normal_7 = 90099
tQSTask_HuPan.Normal_8 = 90100
tQSTask_HuPan.Normal_9 = 90101
tQSTask_HuPan.Normal_10 = 90102
tQSTask_HuPan.Normal_11 = 90122

--tQSTask_HuPan.Option_1 = 90103
--tQSTask_HuPan.Option_1_1_1 = 90104
--tQSTask_HuPan.Option_1_2_1 = 90106
--tQSTask_HuPan.Option_2 = 90108
--tQSTask_HuPan.Option_2_1_1 = 90109
--tQSTask_HuPan.Option_2_2_1 = 90111
--tQSTask_HuPan.Option_3 = 90113
--tQSTask_HuPan.Option_3_1_1 = 90114
--tQSTask_HuPan.Option_3_2_1 = 90116

--tQSTask_HuPan.Option_1_1_2 = 90105
--tQSTask_HuPan.Option_1_2_2 = 90107
--tQSTask_HuPan.Option_2_1_2 = 90110
--tQSTask_HuPan.Option_2_2_2 = 90112
--tQSTask_HuPan.Option_3_1_2 = 90115
--tQSTask_HuPan.Option_3_2_2 = 90121

local tDialog = {}
tDialog.Normal_1_1 = 12562 
tDialog.Normal_1_2 = 12563 
tDialog.Normal_2_1 = 12564 
tDialog.Normal_2_2 = 12565 
tDialog.Normal_3_1 = 12566 
tDialog.Normal_3_2 = 12567 
tDialog.Normal_4_1 = 12568 
tDialog.Normal_4_2 = 12569 
tDialog.Normal_5_1 = 12570
tDialog.Normal_5_2 = 12571
tDialog.Normal_6_1 = 12572
tDialog.Normal_6_2 = 12573
tDialog.Normal_7_1 = 12574
tDialog.Normal_7_2 = 12575
tDialog.Normal_8_1 = 12576
tDialog.Normal_8_2 = 12577
tDialog.Normal_9_1 = 12578
tDialog.Normal_9_2 = 12579
tDialog.Normal_10_1 = 12580
tDialog.Normal_10_2 = 12581
tDialog.Normal_11_1 = 12658
tDialog.Normal_11_2 = 12659

tDialog.Option_1_1 = 12582
tDialog.Option_1_2 = 12583
tDialog.Option_1_3 = 12584
tDialog.Option_2_1 = 12587
tDialog.Option_2_2 = 12588
tDialog.Option_2_3 = 12589
tDialog.Option_3_1 = 12592
tDialog.Option_3_2 = 12593
tDialog.Option_3_3 = 12594

tDialog.NpcKeLiSiChat = 12660

--tDialog.Option_1_2_1 = 12654
--tDialog.Option_1_4 = 12585
--tDialog.Option_1_4_1 = 12655
--tDialog.Option_1_5 = 12586
--tDialog.Option_2_4 = 12590
--tDialog.Option_2_5 = 12591
--tDialog.Option_3_2_1 = 12656
--tDialog.Option_3_2_2 = 12657
--tDialog.Option_3_4 = 12595
--tDialog.Option_3_5 = 12596

local tNpc = {}
tNpc.XiaoHua = 3781  --少女小花
tNpc.XiaLuoKe = 3782 --探员夏洛克
tNpc.KeLiSi = 3783   --克丽丝
tNpc.XiEr = 3048     --希尔
tNpc.HaiLi = 3036    --海莉
tNpc.ZhenMin = 3037  --镇民
tNpc.QiNa = 3095     --齐娜
tNpc.RuiXi = 3096    --瑞茜
tNpc.DaDa = 3448     --吟游诗人达达
tNpc.JiaLu = 3447    --码头工人加鲁
tNpc.AiLi = 3186	 --旅行者艾力
tNpc.LvGuan = 3044	 --旅馆老板
tNpc.SangNi = 2035   --桑妮

local tNpcGroup = {}
tNpcGroup.XiaoHua  = 20880
tNpcGroup.XiaLuoKe = 20881
tNpcGroup.KeLiSi = 20882
tNpcGroup.XiEr  = 20079
tNpcGroup.HaiLi = 20047
tNpcGroup.ZhenMin  = 20048
tNpcGroup.QiNa  = 20139
tNpcGroup.RuiXi  = 20143
tNpcGroup.DaDa = 20449
tNpcGroup.JiaLu = 20448
tNpcGroup.Collect_1 = 60387
tNpcGroup.Collect_2 = 60388 
tNpcGroup.Collect_3 = 60389
tNpcGroup.AiLi = 20141
tNpcGroup.LvGuan = 10006

local tMonsterGroup = {}
tMonsterGroup.Hukesi = 900560
tMonsterGroup.Yuren = 900561

local tGenId = {}
tGenId.XiaoHua   = 20010240
tGenId.XiaLuoKe  = 20010241
tGenId.KeLiSi    = 20010242
tGenId.Collect_1 = 20010243
tGenId.Collect_2 = 20010244
tGenId.Collect_3 = 20010245
tGenId.Hukesi    = 20010246
tGenId.Yuren     = 20010247
tGenId.XiEr = 2001125
tGenId.HaiLi = 2001104
tGenId.ZhenMin = 2001105
tGenId.QiNa = 2001716
tGenId.RuiXi = 2001720
tGenId.DaDa = 20010131
tGenId.JiaLu = 20010130
tGenId.AiLi = 2001718
tGenId.LvGuan = 2001134

rwtNpcGroup[tNpcGroup.Collect_1] = rwtNpcGroup[tNpcGroup.Collect_1] or {}    
rwtNpcGroup[tNpcGroup.Collect_1]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[tNpcGroup.Collect_2] = rwtNpcGroup[tNpcGroup.Collect_2] or {}    
rwtNpcGroup[tNpcGroup.Collect_2]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[tNpcGroup.Collect_3] = rwtNpcGroup[tNpcGroup.Collect_3] or {}    
rwtNpcGroup[tNpcGroup.Collect_3]["Type"] = CONST_NPCGROUP_TYPE.Collect
--rwtNpcGroup[tNpcGroup.Collect_3]["DialogId"] = tDialog.Option_3_3

rwtNpcGroup[tNpcGroup.XiaoHua] = rwtNpcGroup[tNpcGroup.XiaoHua] or {}    
rwtNpcGroup[tNpcGroup.XiaoHua]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[tNpcGroup.XiaoHua]["NpcId"]= tNpc.XiaoHua
rwtNpcGroup[tNpcGroup.XiaLuoKe] = rwtNpcGroup[tNpcGroup.XiaLuoKe] or {}    
rwtNpcGroup[tNpcGroup.XiaLuoKe]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[tNpcGroup.XiaLuoKe]["NpcId"]= tNpc.XiaLuoKe
rwtNpcGroup[tNpcGroup.KeLiSi] = rwtNpcGroup[tNpcGroup.KeLiSi] or {}    
rwtNpcGroup[tNpcGroup.KeLiSi]["Type"] = CONST_NPCGROUP_TYPE.SingleNpc
rwtNpcGroup[tNpcGroup.KeLiSi]["NpcId"]= tNpc.KeLiSi

rwtNpc[tNpc.XiaoHua]  = rwtNpc[tNpc.XiaoHua] or {}
rwtNpc[tNpc.XiaLuoKe] = rwtNpc[tNpc.XiaLuoKe] or {}
rwtNpc[tNpc.KeLiSi]   = rwtNpc[tNpc.KeLiSi] or {}
rwtNpc[tNpc.KeLiSi]["DialogId"] = {tDialog.NpcKeLiSiChat}

local tPos = {}
tPos.SangNi = "8.73,0.05,-17.75"


rwtTask[tQSTask_HuPan.Normal_1] = {}
rwtTask[tQSTask_HuPan.Normal_1]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_1]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_1]["TaskNpc"] = tNpc.XiEr
rwtTask[tQSTask_HuPan.Normal_1]["AcceptDialogId"] = tDialog.Normal_1_1
rwtTask[tQSTask_HuPan.Normal_1]["DialogId"] = tDialog.Normal_1_2
rwtTask[tQSTask_HuPan.Normal_1]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_1]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_1]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_1]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_1]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_1]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.XiEr
rwtTask[tQSTask_HuPan.Normal_1]["StartAutoWay"]["FindWayGenId"] = tGenId.XiEr

rwtTask[tQSTask_HuPan.Normal_2] = {}
rwtTask[tQSTask_HuPan.Normal_2]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_2]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_2]["TaskNpc"] = tNpc.HaiLi
--rwtTask[tQSTask_HuPan.Normal_2]["isPreOption"] = 1
--rwtTask[tQSTask_HuPan.Normal_2]["NextOptionTask"] = tQSTask_HuPan.Option_2
rwtTask[tQSTask_HuPan.Normal_2]["AcceptDialogId"] = tDialog.Normal_2_1
rwtTask[tQSTask_HuPan.Normal_2]["DialogId"] = tDialog.Normal_2_2
rwtTask[tQSTask_HuPan.Normal_2]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_2]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_2]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_2]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_2]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_2]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.HaiLi
rwtTask[tQSTask_HuPan.Normal_2]["StartAutoWay"]["FindWayGenId"] = tGenId.HaiLi

rwtTask[tQSTask_HuPan.Normal_3] = {}
rwtTask[tQSTask_HuPan.Normal_3]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_3]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_3]["TaskNpc"] = tNpc.ZhenMin
rwtTask[tQSTask_HuPan.Normal_3]["AcceptDialogId"] = tDialog.Normal_3_1
rwtTask[tQSTask_HuPan.Normal_3]["DialogId"] = tDialog.Normal_3_2
rwtTask[tQSTask_HuPan.Normal_3]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_3]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_3]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_3]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_3]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_3]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.ZhenMin
rwtTask[tQSTask_HuPan.Normal_3]["StartAutoWay"]["FindWayGenId"] = tGenId.ZhenMin

rwtTask[tQSTask_HuPan.Normal_4] = {}
rwtTask[tQSTask_HuPan.Normal_4]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_4]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_4]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_4]["TaskNpc"] = tNpc.QiNa
rwtTask[tQSTask_HuPan.Normal_4]["AcceptDialogId"] = tDialog.Normal_4_1
rwtTask[tQSTask_HuPan.Normal_4]["DialogId"] = tDialog.Normal_4_2
rwtTask[tQSTask_HuPan.Normal_4]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_4]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_4]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_4]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_4]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_4]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.QiNa
rwtTask[tQSTask_HuPan.Normal_4]["StartAutoWay"]["FindWayGenId"] = tGenId.QiNa

rwtTask[tQSTask_HuPan.Normal_5] = {}
rwtTask[tQSTask_HuPan.Normal_5]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_5]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_5]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_5]["TaskNpc"] = tNpc.RuiXi
rwtTask[tQSTask_HuPan.Normal_5]["AcceptDialogId"] = tDialog.Normal_5_1
rwtTask[tQSTask_HuPan.Normal_5]["DialogId"] = tDialog.Normal_5_2
rwtTask[tQSTask_HuPan.Normal_5]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_5]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_5]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_5]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_5]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_5]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.RuiXi
rwtTask[tQSTask_HuPan.Normal_5]["StartAutoWay"]["FindWayGenId"] = tGenId.RuiXi

rwtTask[tQSTask_HuPan.Normal_6] = {}
rwtTask[tQSTask_HuPan.Normal_6]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_6]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_6]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_6]["TaskNpc"] = tNpc.DaDa
rwtTask[tQSTask_HuPan.Normal_6]["AcceptDialogId"] = tDialog.Normal_6_1
rwtTask[tQSTask_HuPan.Normal_6]["DialogId"] = tDialog.Normal_6_2
rwtTask[tQSTask_HuPan.Normal_6]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_6]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_6]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_6]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_6]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_6]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.DaDa
rwtTask[tQSTask_HuPan.Normal_6]["StartAutoWay"]["FindWayGenId"] = tGenId.DaDa

rwtTask[tQSTask_HuPan.Normal_7] = {}
rwtTask[tQSTask_HuPan.Normal_7]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_7]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_7]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_7]["TaskNpc"] = tNpc.JiaLu
rwtTask[tQSTask_HuPan.Normal_7]["AcceptDialogId"] = tDialog.Normal_7_1
rwtTask[tQSTask_HuPan.Normal_7]["DialogId"] = tDialog.Normal_7_2
rwtTask[tQSTask_HuPan.Normal_7]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_7]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_7]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_7]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_7]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_7]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.JiaLu
rwtTask[tQSTask_HuPan.Normal_7]["StartAutoWay"]["FindWayGenId"] = tGenId.JiaLu

rwtTask[tQSTask_HuPan.Normal_8] = {}
rwtTask[tQSTask_HuPan.Normal_8]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_8]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_8]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_8]["TaskNpc"] = tNpc.XiaoHua
rwtTask[tQSTask_HuPan.Normal_8]["AcceptDialogId"] = tDialog.Normal_8_1
rwtTask[tQSTask_HuPan.Normal_8]["DialogId"] = tDialog.Normal_8_2
--rwtTask[tQSTask_HuPan.Normal_8]["isPreOption"] = 1
--rwtTask[tQSTask_HuPan.Normal_8]["NextOptionTask"] = tQSTask_HuPan.Option_1
rwtTask[tQSTask_HuPan.Normal_8]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_8]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_8]["DynaNpcGroupGen"] = {}
rwtTask[tQSTask_HuPan.Normal_8]["DynaNpcGroupGen"][1] = {}
rwtTask[tQSTask_HuPan.Normal_8]["DynaNpcGroupGen"][1]["GenId"] = tGenId.XiaoHua
rwtTask[tQSTask_HuPan.Normal_8]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_8]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.NotDel
rwtTask[tQSTask_HuPan.Normal_8]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_8]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_8]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_8]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.XiaoHua
rwtTask[tQSTask_HuPan.Normal_8]["StartAutoWay"]["FindWayGenId"] = tGenId.XiaoHua

rwtTask[tQSTask_HuPan.Normal_9] = {}
rwtTask[tQSTask_HuPan.Normal_9]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_9]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_9]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_9]["TaskNpc"] = tNpc.XiaLuoKe
rwtTask[tQSTask_HuPan.Normal_9]["AcceptDialogId"] = tDialog.Normal_9_1
rwtTask[tQSTask_HuPan.Normal_9]["DialogId"] = tDialog.Normal_9_2
rwtTask[tQSTask_HuPan.Normal_9]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_9]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_9]["DynaNpcGroupGen"] = {}
rwtTask[tQSTask_HuPan.Normal_9]["DynaNpcGroupGen"][1] = {}
rwtTask[tQSTask_HuPan.Normal_9]["DynaNpcGroupGen"][1]["GenId"] = tGenId.XiaLuoKe
rwtTask[tQSTask_HuPan.Normal_9]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_9]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tQSTask_HuPan.Normal_9]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_9]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_9]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_9]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.XiaLuoKe
rwtTask[tQSTask_HuPan.Normal_9]["StartAutoWay"]["FindWayGenId"] = tGenId.XiaLuoKe

rwtTask[tQSTask_HuPan.Normal_10] = {}
rwtTask[tQSTask_HuPan.Normal_10]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_10]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_10]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_10]["TaskNpc"] = tNpc.KeLiSi
rwtTask[tQSTask_HuPan.Normal_10]["AcceptDialogId"] = tDialog.Normal_10_1
rwtTask[tQSTask_HuPan.Normal_10]["DialogId"] = tDialog.Normal_10_2
rwtTask[tQSTask_HuPan.Normal_10]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_10]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_10]["DynaNpcGroupGen"] = {}
rwtTask[tQSTask_HuPan.Normal_10]["DynaNpcGroupGen"][1] = {}
rwtTask[tQSTask_HuPan.Normal_10]["DynaNpcGroupGen"][1]["GenId"] = tGenId.KeLiSi
rwtTask[tQSTask_HuPan.Normal_10]["DynaNpcGroupGen"][1]["MapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_10]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
rwtTask[tQSTask_HuPan.Normal_10]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_10]["StartAutoWay"]["FindWayTypeId"] = 1
rwtTask[tQSTask_HuPan.Normal_10]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_10]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.KeLiSi
rwtTask[tQSTask_HuPan.Normal_10]["StartAutoWay"]["FindWayGenId"] = tGenId.KeLiSi

rwtTask[tQSTask_HuPan.Normal_11] = {}
rwtTask[tQSTask_HuPan.Normal_11]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
rwtTask[tQSTask_HuPan.Normal_11]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
rwtTask[tQSTask_HuPan.Normal_11]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
rwtTask[tQSTask_HuPan.Normal_11]["TaskNpc"] = tNpc.SangNi
rwtTask[tQSTask_HuPan.Normal_11]["AcceptDialogId"] = tDialog.Normal_11_1
rwtTask[tQSTask_HuPan.Normal_11]["DialogId"] = tDialog.Normal_11_2
--rwtTask[tQSTask_HuPan.Normal_11]["isPreOption"] = 1
--rwtTask[tQSTask_HuPan.Normal_11]["NextOptionTask"] = tQSTask_HuPan.Option_3
rwtTask[tQSTask_HuPan.Normal_11]["QuickSendAreaId"] = 2001    
rwtTask[tQSTask_HuPan.Normal_11]["QuickSendTownId"] = 200101  --任务城镇
rwtTask[tQSTask_HuPan.Normal_11]["StartAutoWay"] = {}
rwtTask[tQSTask_HuPan.Normal_11]["StartAutoWay"]["FindWayTypeId"] = 0
rwtTask[tQSTask_HuPan.Normal_11]["StartAutoWay"]["FindWayMapId"] = nMapId
rwtTask[tQSTask_HuPan.Normal_11]["StartAutoWay"]["FindWayPos"] = tPos.SangNi

--rwtTask[tQSTask_HuPan.Option_1] = {}
--rwtTask[tQSTask_HuPan.Option_1]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_1]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.CHOOSE_OPTION
--rwtTask[tQSTask_HuPan.Option_1]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_1]["isFirstOptionTask"] = 1  --是第一个选项任务 （配了这个的选项任务才会加入任务池）
--rwtTask[tQSTask_HuPan.Option_1]["TaskNpc"] = tNpc.XiaoHua        
--rwtTask[tQSTask_HuPan.Option_1]["DialogId"] = tDialog.Option_1_1
----rwtTask[tQSTask_HuPan.Option_1]["AcceptDialogId"] = tDialog.Option_1_1
--rwtTask[tQSTask_HuPan.Option_1]["DynaNpcGroupGen"] = {}
--rwtTask[tQSTask_HuPan.Option_1]["DynaNpcGroupGen"][1] = {}
--rwtTask[tQSTask_HuPan.Option_1]["DynaNpcGroupGen"][1]["GenId"] = tGenId.XiaoHua
--rwtTask[tQSTask_HuPan.Option_1]["DynaNpcGroupGen"][1]["MapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.NotDel
--rwtTask[tQSTask_HuPan.Option_1]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_1]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_1]["OptionTask1"] = tQSTask_HuPan.Option_1_1_1  --选项1任务
--rwtTask[tQSTask_HuPan.Option_1]["OptionTask2"] = tQSTask_HuPan.Option_1_2_1  --选项2任务

--rwtTask[tQSTask_HuPan.Option_1_1_1] = {}
--rwtTask[tQSTask_HuPan.Option_1_1_1]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_1_1_1]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_1_1_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_1_1_1]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_1_1_1]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_1_1_1]["AcceptDialogId"] = tDialog.Option_1_2
--rwtTask[tQSTask_HuPan.Option_1_1_1]["DynaNpcGroupGen"] = {}
--rwtTask[tQSTask_HuPan.Option_1_1_1]["DynaNpcGroupGen"][1] = {}
--rwtTask[tQSTask_HuPan.Option_1_1_1]["DynaNpcGroupGen"][1]["GenId"] = tGenId.XiaoHua
--rwtTask[tQSTask_HuPan.Option_1_1_1]["DynaNpcGroupGen"][1]["MapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_1_1_1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[tQSTask_HuPan.Option_1_1_1]["TaskNpc"] = tNpc.XiaoHua        
--rwtTask[tQSTask_HuPan.Option_1_1_1]["DialogId"] = tDialog.Option_1_2
--rwtTask[tQSTask_HuPan.Option_1_1_1]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_1_1_1]["QuickSendTownId"] = 200101  --任务城镇

--rwtTask[tQSTask_HuPan.Option_1_2_1] = {}
--rwtTask[tQSTask_HuPan.Option_1_2_1]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_1_2_1]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_1_2_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_1_2_1]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_1_2_1]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_1_2_1]["AcceptDialogId"] = tDialog.Option_1_3
--rwtTask[tQSTask_HuPan.Option_1_2_1]["DynaNpcGroupGen"] = {}
--rwtTask[tQSTask_HuPan.Option_1_2_1]["DynaNpcGroupGen"][1] = {}
--rwtTask[tQSTask_HuPan.Option_1_2_1]["DynaNpcGroupGen"][1]["GenId"] = tGenId.XiaoHua
--rwtTask[tQSTask_HuPan.Option_1_2_1]["DynaNpcGroupGen"][1]["MapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_1_2_1]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[tQSTask_HuPan.Option_1_2_1]["TaskNpc"] = tNpc.XiaoHua        
--rwtTask[tQSTask_HuPan.Option_1_2_1]["DialogId"] = tDialog.Option_1_3
--rwtTask[tQSTask_HuPan.Option_1_2_1]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_1_2_1]["QuickSendTownId"] = 200101  --任务城镇

--rwtTask[tQSTask_HuPan.Option_1_1_2] = {}
--rwtTask[tQSTask_HuPan.Option_1_1_2]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_1_1_2]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_1_1_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_1_1_2]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_1_1_2]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_1_1_2]["TaskNpc"] = tNpc.XiEr        
--rwtTask[tQSTask_HuPan.Option_1_1_2]["DialogId"] = tDialog.Option_1_3
--rwtTask[tQSTask_HuPan.Option_1_1_2]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_1_1_2]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_1_1_2]["StartAutoWay"] = {}
--rwtTask[tQSTask_HuPan.Option_1_1_2]["StartAutoWay"]["FindWayTypeId"] = 1
--rwtTask[tQSTask_HuPan.Option_1_1_2]["StartAutoWay"]["FindWayMapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_1_1_2]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.XiEr        
--rwtTask[tQSTask_HuPan.Option_1_1_2]["StartAutoWay"]["FindWayGenId"] = tGenId.XiEr      
    

--rwtTask[tQSTask_HuPan.Option_1_2_2] = {}
--rwtTask[tQSTask_HuPan.Option_1_2_2]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_1_2_2]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_1_2_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_1_2_2]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_1_2_2]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_1_2_2]["TaskNpc"] = tNpc.XiEr        
--rwtTask[tQSTask_HuPan.Option_1_2_2]["DialogId"] = tDialog.Option_1_5
--rwtTask[tQSTask_HuPan.Option_1_2_2]["QuickSendAreaId"] = 2001
--rwtTask[tQSTask_HuPan.Option_1_2_2]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_1_2_2]["StartAutoWay"] = {}
--rwtTask[tQSTask_HuPan.Option_1_2_2]["StartAutoWay"]["FindWayTypeId"] = 1
--rwtTask[tQSTask_HuPan.Option_1_2_2]["StartAutoWay"]["FindWayMapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_1_2_2]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.XiEr        
--rwtTask[tQSTask_HuPan.Option_1_2_2]["StartAutoWay"]["FindWayGenId"] = tGenId.XiEr      


--rwtTask[tQSTask_HuPan.Option_2] = {}
--rwtTask[tQSTask_HuPan.Option_2]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_2]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.CHOOSE_OPTION
--rwtTask[tQSTask_HuPan.Option_2]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_2]["isFirstOptionTask"] = 1  --是第一个选项任务 （配了这个的选项任务才会加入任务池）
--rwtTask[tQSTask_HuPan.Option_2]["TaskNpc"] = tNpc.HaiLi        
--rwtTask[tQSTask_HuPan.Option_2]["DialogId"] = tDialog.Option_2_1
----rwtTask[tQSTask_HuPan.Option_2]["AcceptDialogId"] = tDialog.Option_2_1
--rwtTask[tQSTask_HuPan.Option_2]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_2]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_2]["OptionTask1"] = tQSTask_HuPan.Option_2_1_1  --选项1任务
--rwtTask[tQSTask_HuPan.Option_2]["OptionTask2"] = tQSTask_HuPan.Option_2_2_1  --选项2任务

--rwtTask[tQSTask_HuPan.Option_2_1_1] = {}
--rwtTask[tQSTask_HuPan.Option_2_1_1]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_2_1_1]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_2_1_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_2_1_1]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_2_1_1]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_2_1_1]["TaskNpc"] = tNpc.HaiLi        
--rwtTask[tQSTask_HuPan.Option_2_1_1]["DialogId"] = tDialog.Option_2_2
--rwtTask[tQSTask_HuPan.Option_2_1_1]["AcceptDialogId"] = tDialog.Option_2_2
--rwtTask[tQSTask_HuPan.Option_2_1_1]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_2_1_1]["QuickSendTownId"] = 200101  --任务城镇

--rwtTask[tQSTask_HuPan.Option_2_2_1] = {}
--rwtTask[tQSTask_HuPan.Option_2_2_1]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_2_2_1]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_2_2_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_2_2_1]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_2_2_1]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_2_2_1]["TaskNpc"] = tNpc.HaiLi        
--rwtTask[tQSTask_HuPan.Option_2_2_1]["DialogId"] = tDialog.Option_2_3
--rwtTask[tQSTask_HuPan.Option_2_2_1]["AcceptDialogId"] = tDialog.Option_2_3
--rwtTask[tQSTask_HuPan.Option_2_2_1]["QuickSendAreaId"] = 2001
--rwtTask[tQSTask_HuPan.Option_2_2_1]["QuickSendTownId"] = 200101  --任务城镇  

--rwtTask[tQSTask_HuPan.Option_2_1_2] = {}
--rwtTask[tQSTask_HuPan.Option_2_1_2]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_2_1_2]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_2_1_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_2_1_2]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_2_1_2]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_2_1_2]["TaskNpc"] = tNpc.HaiLi        
--rwtTask[tQSTask_HuPan.Option_2_1_2]["DialogId"] = tDialog.Option_2_3
--rwtTask[tQSTask_HuPan.Option_2_1_2]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_2_1_2]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_2_1_2]["StartAutoWay"] = {}
--rwtTask[tQSTask_HuPan.Option_2_1_2]["StartAutoWay"]["FindWayTypeId"] = 1
--rwtTask[tQSTask_HuPan.Option_2_1_2]["StartAutoWay"]["FindWayMapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_2_1_2]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.HaiLi        
--rwtTask[tQSTask_HuPan.Option_2_1_2]["StartAutoWay"]["FindWayGenId"] = tGenId.HaiLi      
  

--rwtTask[tQSTask_HuPan.Option_2_2_2] = {}
--rwtTask[tQSTask_HuPan.Option_2_2_2]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_2_2_2]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_2_2_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_2_2_2]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_2_2_2]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_2_2_2]["TaskNpc"] = tNpc.HaiLi        
--rwtTask[tQSTask_HuPan.Option_2_2_2]["DialogId"] = tDialog.Option_2_5
--rwtTask[tQSTask_HuPan.Option_2_2_2]["QuickSendAreaId"] = 2001
--rwtTask[tQSTask_HuPan.Option_2_2_2]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_2_2_2]["StartAutoWay"] = {}
--rwtTask[tQSTask_HuPan.Option_2_2_2]["StartAutoWay"]["FindWayTypeId"] = 1
--rwtTask[tQSTask_HuPan.Option_2_2_2]["StartAutoWay"]["FindWayMapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_2_2_2]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.HaiLi        
--rwtTask[tQSTask_HuPan.Option_2_2_2]["StartAutoWay"]["FindWayGenId"] = tGenId.HaiLi      

--rwtTask[tQSTask_HuPan.Option_3] = {}
--rwtTask[tQSTask_HuPan.Option_3]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_3]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.CHOOSE_OPTION
--rwtTask[tQSTask_HuPan.Option_3]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_3]["isFirstOptionTask"] = 1  --是第一个选项任务 （配了这个的选项任务才会加入任务池）
--rwtTask[tQSTask_HuPan.Option_3]["TaskNpc"] = tNpc.SangNi        
--rwtTask[tQSTask_HuPan.Option_3]["DialogId"] = tDialog.Option_3_1
--rwtTask[tQSTask_HuPan.Option_3]["AcceptDialogId"] = tDialog.Option_3_1
--rwtTask[tQSTask_HuPan.Option_3]["CloseDialog"] = 0
--rwtTask[tQSTask_HuPan.Option_3]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_3]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_3]["OptionTask1"] = tQSTask_HuPan.Option_3_1_1  --选项1任务
--rwtTask[tQSTask_HuPan.Option_3]["OptionTask2"] = tQSTask_HuPan.Option_3_2_1  --选项2任务   

--rwtTask[tQSTask_HuPan.Option_3_1_1] = {}
--rwtTask[tQSTask_HuPan.Option_3_1_1]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_3_1_1]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_3_1_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_3_1_1]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_3_1_1]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_3_1_1]["TaskNpc"] = tNpc.HaiLi        
--rwtTask[tQSTask_HuPan.Option_3_1_1]["DialogId"] = tDialog.Option_3_2
--rwtTask[tQSTask_HuPan.Option_3_1_1]["AcceptDialogId"] = tDialog.Option_3_2
--rwtTask[tQSTask_HuPan.Option_3_1_1]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_3_1_1]["QuickSendTownId"] = 200101  --任务城镇

--rwtTask[tQSTask_HuPan.Option_3_2_1] = {}
--rwtTask[tQSTask_HuPan.Option_3_2_1]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_3_2_1]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_3_2_1]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_3_2_1]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_3_2_1]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_3_2_1]["TaskNpc"] = tNpc.HaiLi        
--rwtTask[tQSTask_HuPan.Option_3_2_1]["DialogId"] = tDialog.Option_3_3
--rwtTask[tQSTask_HuPan.Option_3_2_1]["AcceptDialogId"] = tDialog.Option_3_3
--rwtTask[tQSTask_HuPan.Option_3_2_1]["QuickSendAreaId"] = 2001
--rwtTask[tQSTask_HuPan.Option_3_2_1]["QuickSendTownId"] = 200101  --任务城镇  

--rwtTask[tQSTask_HuPan.Option_3_1_2] = {}
--rwtTask[tQSTask_HuPan.Option_3_1_2]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_3_1_2]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_3_1_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_3_1_2]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_3_1_2]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_3_1_2]["TaskNpc"] = tNpc.KeLiSi        
--rwtTask[tQSTask_HuPan.Option_3_1_2]["DialogId"] = tDialog.Option_3_3
--rwtTask[tQSTask_HuPan.Option_3_1_2]["QuickSendAreaId"] = 2001    
--rwtTask[tQSTask_HuPan.Option_3_1_2]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_3_1_2]["DynaNpcGroupGen"] = {}
--rwtTask[tQSTask_HuPan.Option_3_1_2]["DynaNpcGroupGen"][1] = {}
--rwtTask[tQSTask_HuPan.Option_3_1_2]["DynaNpcGroupGen"][1]["GenId"] = tGenId.KeLiSi
--rwtTask[tQSTask_HuPan.Option_3_1_2]["DynaNpcGroupGen"][1]["MapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_3_1_2]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[tQSTask_HuPan.Option_3_1_2]["StartAutoWay"] = {}
--rwtTask[tQSTask_HuPan.Option_3_1_2]["StartAutoWay"]["FindWayTypeId"] = 1
--rwtTask[tQSTask_HuPan.Option_3_1_2]["StartAutoWay"]["FindWayMapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_3_1_2]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.KeLiSi        
--rwtTask[tQSTask_HuPan.Option_3_1_2]["StartAutoWay"]["FindWayGenId"] = tGenId.KeLiSi      
 

--rwtTask[tQSTask_HuPan.Option_3_2_2] = {}
--rwtTask[tQSTask_HuPan.Option_3_2_2]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_3_2_2]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_3_2_2]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_3_2_2]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_3_2_2]["NextTaskId"] = tQSTask_HuPan.Option_3_2_3
--rwtTask[tQSTask_HuPan.Option_3_2_2]["TaskNpc"] = tNpc.LvGuan        
--rwtTask[tQSTask_HuPan.Option_3_2_2]["DialogId"] = tDialog.Option_3_4_2
--rwtTask[tQSTask_HuPan.Option_3_2_2]["QuickSendAreaId"] = 2001
--rwtTask[tQSTask_HuPan.Option_3_2_2]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_3_2_2]["StartAutoWay"] = {}
--rwtTask[tQSTask_HuPan.Option_3_2_2]["StartAutoWay"]["FindWayTypeId"] = 0
--rwtTask[tQSTask_HuPan.Option_3_2_2]["StartAutoWay"]["FindWayMapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_3_2_2]["StartAutoWay"]["FindWayPos"] = "-2.33,0.05,-1.83"         

--rwtTask[tQSTask_HuPan.Option_3_2_3] = {}
--rwtTask[tQSTask_HuPan.Option_3_2_3]["Title"] = tLuaText[LANGUAGE_CONFIG][21608]
--rwtTask[tQSTask_HuPan.Option_3_2_3]["TaskType"] = CONST_TASK_TYPE.QUICKSEND
--rwtTask[tQSTask_HuPan.Option_3_2_3]["TaskDetailType"] = CONST_TASK_DETAIL_TYPE.TALK_BY_NPC
--rwtTask[tQSTask_HuPan.Option_3_2_3]["isOptionTask"] = 1   --是选项系列任务
--rwtTask[tQSTask_HuPan.Option_3_2_3]["isFinalOptionTask"] = 1 --是选项任务的结束任务
--rwtTask[tQSTask_HuPan.Option_3_2_3]["TaskNpc"] = tNpc.KeLiSi        
--rwtTask[tQSTask_HuPan.Option_3_2_3]["DynaNpcGroupGen"] = {}
--rwtTask[tQSTask_HuPan.Option_3_2_3]["DynaNpcGroupGen"][1] = {}
--rwtTask[tQSTask_HuPan.Option_3_2_3]["DynaNpcGroupGen"][1]["GenId"] = tGenId.KeLiSi
--rwtTask[tQSTask_HuPan.Option_3_2_3]["DynaNpcGroupGen"][1]["MapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_3_2_3]["DynaNpcGroupGen"][1]["DelType"] = CONST_TASK_INFO_DELTYPE.Complete
--rwtTask[tQSTask_HuPan.Option_3_2_3]["DialogId"] = tDialog.Option_3_5
--rwtTask[tQSTask_HuPan.Option_3_2_3]["QuickSendAreaId"] = 2001
--rwtTask[tQSTask_HuPan.Option_3_2_3]["QuickSendTownId"] = 200101  --任务城镇
--rwtTask[tQSTask_HuPan.Option_3_2_3]["StartAutoWay"] = {}
--rwtTask[tQSTask_HuPan.Option_3_2_3]["StartAutoWay"]["FindWayTypeId"] = 1
--rwtTask[tQSTask_HuPan.Option_3_2_3]["StartAutoWay"]["FindWayMapId"] = nMapId
--rwtTask[tQSTask_HuPan.Option_3_2_3]["StartAutoWay"]["FindWayGroupId"] = tNpcGroup.KeLiSi        
--rwtTask[tQSTask_HuPan.Option_3_2_3]["StartAutoWay"]["FindWayGenId"] = tGenId.KeLiSi     