--region *.lua
--Date
--此文件由[BabeLua]插件自动生成
--by zy
--endregion
local nCopyMapId = 3134
local nTempDataId = 1226
local nTempDataId_Normal = 1225
local nTarget = 60302

local tNpcGroup = {}
tNpcGroup.Stone = 60442
tNpcGroup.Box = 60443
tNpcGroup.Egg = 60444
tNpcGroup.EnterNpc = 20927
tNpcGroup.Npc_1 = 20928
tNpcGroup.Npc_2 = 20929
tNpcGroup.Npc_3 = 20930

local tAward = {}
tAward.Egg_Normal = 1000560
tAward.Box = 1000561
tAward.Stone = 1000562
tAward.Egg_Crit = 1000563
tAward.Stone_Super = 1000564
tAward.GetItem = 1000565
tAward.GetItem_5 = 1000566

local nItemId = 7000361
rwtItem[nItemId] = rwtItem[nItemId] or {}

local tNpcPos = {}
tNpcPos.Npc_1 = "33.4,0.0814085,43.5"
tNpcPos.Npc_2 = "16.5,0.0814085,62"
tNpcPos.Npc_3 = "43.31,0.113575,45.26"
local tNpcRotation = {}
tNpcRotation.Npc_1 = 140
tNpcRotation.Npc_2 = 180
tNpcRotation.Npc_3 = 120

local tGenID = {}
tGenID.Npc_1 = 3134002
tGenID.Npc_2 = 3134003
tGenID.Npc_3 = 3134004

local tDialog = {}
tDialog.Enter_First = 6863
tDialog.Enter_NotFirst = 6864
tDialog.NoItem_CollectBefore  = 6865
tDialog.NoItem_CollectEnd  = 6866
tDialog.Npc_1 = 6867
tDialog.Npc_2 = 6868
tDialog.Npc_3 = 6869
tDialog.Stone_Super = 6870
tDialog.Egg_Super = 6871
tDialog.Box_Super = 6872
tDialog.AbiDan_1 = 6873
tDialog.AbiDan_2 = 6874
tDialog.AbiDan_3 = 6875
tDialog.AbiDan_4 = 6876


rwtNpcGroup[tNpcGroup.Egg] = rwtNpcGroup[tNpcGroup.Egg] or {}    
rwtNpcGroup[tNpcGroup.Egg]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[tNpcGroup.Egg]["CollectTime"] = 2
rwtNpcGroup[tNpcGroup.Egg]["NotDel"] = 1
rwtNpcGroup[tNpcGroup.Egg]["Func"] = function(nGenEventId,nRandom)
	if rwUserGetItemCount(nItemId) <= 0 then
		rwOpenNpcChatDialog(tDialog.NoItem_CollectEnd)
	end
end
rwtNpcGroup[tNpcGroup.Egg]["Awards"] = {}  
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["CostItems"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["CostItems"][1] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["CostItems"][1]["id"] = nItemId
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["CostItems"][1]["num"] = 1
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["ErrorMsg"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum]["MsgType"] = CONST_MSG_SHOW.Msg_ShowLocalDialog
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum]["Param"] = tDialog.NoItem_CollectBefore
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"] = {}   
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["MinRate"] = 0
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["MaxRate"] = 8000
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["AwardId"] = tAward.Egg_Normal
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.TIPS
--rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["ActionId"] = tNpcGroup.Egg
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["MinRate"] = 8001
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["MaxRate"] = 10000
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["Record"] = nTempDataId
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["DataValue"] = CONST_TEMP_DATA.Data1
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["Value"] = {0,1,2}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["TempDataID"] = nTempDataId
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["AddValue"] = 1
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["DataIndex"] = CONST_TEMP_DATA.Data1
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["AwardId"] = tAward.Egg_Crit
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.GIFT
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["ActionId"] = tNpcGroup.Egg
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["OpenDialog"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["OpenDialog"]["DialogId"] = tDialog.Egg_Super
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"] = {}
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["AwardId"] = tAward.Egg_Normal
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Egg]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.TIPS

rwtNpcGroup[tNpcGroup.Box] = rwtNpcGroup[tNpcGroup.Box] or {}    
rwtNpcGroup[tNpcGroup.Box]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[tNpcGroup.Box]["CollectTime"] = 1
rwtNpcGroup[tNpcGroup.Box]["NotDel"] = 1
rwtNpcGroup[tNpcGroup.Box]["Func"] = function(nGenEventId,nRandom)
	if rwUserGetItemCount(nItemId) <= 0 then
		rwOpenNpcChatDialog(tDialog.NoItem_CollectEnd)
	end
end
rwtNpcGroup[tNpcGroup.Box]["Awards"] = {}  
rwtNpcGroup[tNpcGroup.Box]["Awards"]["CostItems"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["CostItems"][1] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["CostItems"][1]["id"] = nItemId
rwtNpcGroup[tNpcGroup.Box]["Awards"]["CostItems"][1]["num"] = 1
rwtNpcGroup[tNpcGroup.Box]["Awards"]["ErrorMsg"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum]["MsgType"] = CONST_MSG_SHOW.Msg_ShowLocalDialog
rwtNpcGroup[tNpcGroup.Box]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum]["Param"] = tDialog.NoItem_CollectBefore
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"] = {}   
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["MinRate"] = 0
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["MaxRate"] = 8000
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["AwardId"] = tAward.Box
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.TIPS
--rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["ActionId"] = tNpcGroup.Box
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["MinRate"] = 8001
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["MaxRate"] = 10000
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["Record"] = nTempDataId
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["DataValue"] = CONST_TEMP_DATA.Data2
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["Value"] = {0,1}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["TempDataID"] = nTempDataId
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["AddValue"] = 1
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["DataIndex"] = CONST_TEMP_DATA.Data2
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["AwardId"] = tAward.GetItem
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.GIFT
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["ActionId"] = tNpcGroup.Box
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["OpenDialog"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["OpenDialog"]["DialogId"] = tDialog.Box_Super
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"] = {}
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["AwardId"] = tAward.Box
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Box]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.TIPS

rwtNpcGroup[tNpcGroup.Stone] = rwtNpcGroup[tNpcGroup.Stone] or {}    
rwtNpcGroup[tNpcGroup.Stone]["Type"] = CONST_NPCGROUP_TYPE.Collect
rwtNpcGroup[tNpcGroup.Stone]["CollectTime"] = 3
rwtNpcGroup[tNpcGroup.Stone]["NotDel"] = 1
rwtNpcGroup[tNpcGroup.Stone]["Func"] = function(nGenEventId,nRandom)
	if rwUserGetItemCount(nItemId) <= 0 then
		rwOpenNpcChatDialog(tDialog.NoItem_CollectEnd)
	end
end
rwtNpcGroup[tNpcGroup.Stone]["Awards"] = {}  
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["CostItems"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["CostItems"][1] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["CostItems"][1]["id"] = nItemId
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["CostItems"][1]["num"] = 1
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["ErrorMsg"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum]["MsgType"] = CONST_MSG_SHOW.Msg_ShowLocalDialog
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["ErrorMsg"][CONST_CODE.Error_ChkItemNum]["Param"] = tDialog.NoItem_CollectBefore
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"] = {}   
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["MinRate"] = 0
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["MaxRate"] = 9000
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["AwardId"] = tAward.Stone
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.TIPS
--rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][1]["Events"]["GetServerAward"]["ActionId"] = tNpcGroup.Stone
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["MinRate"] = 9001
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["MaxRate"] = 10000
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["Record"] = nTempDataId
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["DataValue"] = CONST_TEMP_DATA.Data3
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["ChkUserTempData"][1]["Value"] = {0}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["TempDataID"] = nTempDataId
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["AddValue"] = 1
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["SetUserTempData"][1]["DataIndex"] = CONST_TEMP_DATA.Data3
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["AwardId"] = tAward.Stone_Super
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.GIFT
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["GetServerAward"]["ActionId"] = tNpcGroup.Stone
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["OpenDialog"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["OpenDialog"]["DialogId"] = tDialog.Stone_Super
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"] = {}
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"] = {}          
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["AwardId"] = tAward.Stone
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtNpcGroup[tNpcGroup.Stone]["Awards"]["RandomEvents"][1]["RandomToNormalEvents"][2]["Events"]["FailEvents"]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.TIPS

rwtNpcGroup[tNpcGroup.EnterNpc] = rwtNpcGroup[tNpcGroup.EnterNpc] or {}    
rwtNpcGroup[tNpcGroup.EnterNpc]["Type"] = CONST_NPCGROUP_TYPE.CheckEvent
rwtNpcGroup[tNpcGroup.EnterNpc]["Awards"] = {}
rwtNpcGroup[tNpcGroup.EnterNpc]["Awards"]["Events"] = {}
rwtNpcGroup[tNpcGroup.EnterNpc]["Awards"]["Events"][1] = {}
rwtNpcGroup[tNpcGroup.EnterNpc]["Awards"]["Events"][1]["OpenDialog"] = {}
rwtNpcGroup[tNpcGroup.EnterNpc]["Awards"]["Events"][1]["OpenDialog"]["tDialog"] = {tDialog.AbiDan_1,tDialog.AbiDan_2,tDialog.AbiDan_3,tDialog.AbiDan_4}

rwtNpcGroup[tNpcGroup.Npc_1] = rwtNpcGroup[tNpcGroup.Npc_1] or {}    
rwtNpcGroup[tNpcGroup.Npc_1]["Type"] = CONST_NPCGROUP_TYPE.CheckEvent
rwtNpcGroup[tNpcGroup.Npc_1]["Awards"] = {}
rwtNpcGroup[tNpcGroup.Npc_1]["Awards"]["Events"] = {}
rwtNpcGroup[tNpcGroup.Npc_1]["Awards"]["Events"][1] = {}
rwtNpcGroup[tNpcGroup.Npc_1]["Awards"]["Events"][1]["OpenDialog"] = {}
rwtNpcGroup[tNpcGroup.Npc_1]["Awards"]["Events"][1]["OpenDialog"]["tDialog"] = {tDialog.Npc_1}

rwtNpcGroup[tNpcGroup.Npc_2] = rwtNpcGroup[tNpcGroup.Npc_2] or {}    
rwtNpcGroup[tNpcGroup.Npc_2]["Type"] = CONST_NPCGROUP_TYPE.CheckEvent
rwtNpcGroup[tNpcGroup.Npc_2]["Awards"] = {}
rwtNpcGroup[tNpcGroup.Npc_2]["Awards"]["Events"] = {}
rwtNpcGroup[tNpcGroup.Npc_2]["Awards"]["Events"][1] = {}
rwtNpcGroup[tNpcGroup.Npc_2]["Awards"]["Events"][1]["OpenDialog"] = {}
rwtNpcGroup[tNpcGroup.Npc_2]["Awards"]["Events"][1]["OpenDialog"]["tDialog"] = {tDialog.Npc_2}

rwtNpcGroup[tNpcGroup.Npc_3] = rwtNpcGroup[tNpcGroup.Npc_3] or {}    
rwtNpcGroup[tNpcGroup.Npc_3]["Type"] = CONST_NPCGROUP_TYPE.CheckEvent
rwtNpcGroup[tNpcGroup.Npc_3]["Awards"] = {}
rwtNpcGroup[tNpcGroup.Npc_3]["Awards"]["Events"] = {}
rwtNpcGroup[tNpcGroup.Npc_3]["Awards"]["Events"][1] = {}
rwtNpcGroup[tNpcGroup.Npc_3]["Awards"]["Events"][1]["OpenDialog"] = {}
rwtNpcGroup[tNpcGroup.Npc_3]["Awards"]["Events"][1]["OpenDialog"]["tDialog"] = {tDialog.Npc_3}

rwtTarget[nTarget] = {}
rwtTarget[nTarget]["Title"] = tLuaText[LANGUAGE_CONFIG][21807]
rwtTarget[nTarget]["ReqDialogId"] = {tDialog.NoItem_CollectEnd}
rwtTarget[nTarget]["ReqCount"] = 1

rwtCopyMapMission[nCopyMapId] = rwtCopyMapMission[nCopyMapId] or {}
rwtCopyMapMission[nCopyMapId]["TimeLimit"] = CONST_USER_TIMESTYPE.Daily_CopyMap_PetExp
rwtCopyMapMission[nCopyMapId]["TimeLimitMsg"] = tLuaText[LANGUAGE_CONFIG][10044]
rwtCopyMapMission[nCopyMapId]["ReqLev"] = 1
rwtCopyMapMission[nCopyMapId]["Difficulty"] = 1
rwtCopyMapMission[nCopyMapId]["TargetStepNum"] = 1
rwtCopyMapMission[nCopyMapId]["Target1"] = {nTarget}
rwtCopyMapMission[nCopyMapId]["Target99"] = {60072}
rwtCopyMapMission[nCopyMapId]["PassSetTemp"] = {}
rwtCopyMapMission[nCopyMapId]["PassSetTemp"]["TempDataId"] = nTempDataId_Normal
rwtCopyMapMission[nCopyMapId]["PassSetTemp"]["SetValue"] = 1
rwtCopyMapMission[nCopyMapId]["CopyMapInit"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["ChkUserTempData"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["ChkUserTempData"][1] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["ChkUserTempData"][1]["Record"] = nTempDataId_Normal
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["ChkUserTempData"][1]["DataValue"] = CONST_TEMP_DATA.Data1
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["ChkUserTempData"][1]["Value"] = {0}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["OpenDialog"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["OpenDialog"]["DialogId"] = tDialog.Enter_First
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["FailEvents"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["FailEvents"]["OpenDialog"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][1]["FailEvents"]["OpenDialog"]["DialogId"] = tDialog.Enter_NotFirst
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][1] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][1]["TempDataID"] = nTempDataId
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][1]["SetValue"] = 0
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][1]["DataIndex"] = CONST_TEMP_DATA.Data1
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][2] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][2]["TempDataID"] = nTempDataId
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][2]["SetValue"] = 0
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][2]["DataIndex"] = CONST_TEMP_DATA.Data2
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][3] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][3]["TempDataID"] = nTempDataId
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][3]["SetValue"] = 0
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["SetUserTempData"][3]["DataIndex"] = CONST_TEMP_DATA.Data3
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["GetServerAward"] = {}          
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["GetServerAward"]["AwardId"] = tAward.GetItem_5
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["GetServerAward"]["AwardType"] = CONST_AWARD_TYPE.MEMORY_AWARD
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["Events"][2]["GetServerAward"]["ActionType"] = CONST_ACTION_TYPE.TIPS
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["RandomType"] = CONST_RANDOM_EVENT_TYPE.COMBINATION
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["RandomNum"] = 0
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][1] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][1]["Pos"] = tNpcPos.Npc_1
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][1]["RotationY"] = tNpcRotation.Npc_1
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][2] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][2]["Pos"] = tNpcPos.Npc_2
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][2]["RotationY"] = tNpcRotation.Npc_2
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][3] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][3]["Pos"] = tNpcPos.Npc_3
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tGenId"][3]["RotationY"] = tNpcRotation.Npc_3
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["RemainRandomNum"] = 3
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tOtherGenId"] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tOtherGenId"][1] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tOtherGenId"][1]["GenId"] = tGenID.Npc_1
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tOtherGenId"][2] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tOtherGenId"][2]["GenId"] = tGenID.Npc_2
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tOtherGenId"][3] = {}
rwtCopyMapMission[nCopyMapId]["CopyMapInit"]["RandomEvents"][1]["RandomCreare"][1]["tOtherGenId"][3]["GenId"] = tGenID.Npc_3